// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/contracts/kafka/match_event.proto

package kafka

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	battle "proto/battle"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// battle -> match:对局结果(评分回流,二期 MMR)。
// Kafka 投递:topic = match-results(全局,无 zone 段),key = battle_id(同局保序即可);
// 无目标实例语义(任一 match 实例消费即可,消费组 match-rating)。
// battle 作废(DestroyBattle / AbortAllRooms)不发本事件:评分只按真实打完的局更新。
type BattleResultTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamIndex     uint32                 `protobuf:"varint,1,opt,name=team_index,json=teamIndex,proto3" json:"team_index,omitempty"`
	PlayerIds     []uint64               `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultTeam) Reset() {
	*x = BattleResultTeam{}
	mi := &file_proto_contracts_kafka_match_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultTeam) ProtoMessage() {}

func (x *BattleResultTeam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contracts_kafka_match_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultTeam.ProtoReflect.Descriptor instead.
func (*BattleResultTeam) Descriptor() ([]byte, []int) {
	return file_proto_contracts_kafka_match_event_proto_rawDescGZIP(), []int{0}
}

func (x *BattleResultTeam) GetTeamIndex() uint32 {
	if x != nil {
		return x.TeamIndex
	}
	return 0
}

func (x *BattleResultTeam) GetPlayerIds() []uint64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type BattleResultEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BattleId        uint64                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	MatchMode       uint32                 `protobuf:"varint,2,opt,name=match_mode,json=matchMode,proto3" json:"match_mode,omitempty"` // MatchMode 数值(PVE 模式 match 侧忽略评分)
	BattleConfigId  uint32                 `protobuf:"varint,3,opt,name=battle_config_id,json=battleConfigId,proto3" json:"battle_config_id,omitempty"`
	Outcome         battle.EBattleOutcome  `protobuf:"varint,4,opt,name=outcome,proto3,enum=EBattleOutcome" json:"outcome,omitempty"`                      // A 胜 / B 胜 / 平局 / 逃跑等
	WinnerTeamIndex uint32                 `protobuf:"varint,5,opt,name=winner_team_index,json=winnerTeamIndex,proto3" json:"winner_team_index,omitempty"` // outcome 为胜负时有效;平局时忽略
	Teams           []*BattleResultTeam    `protobuf:"bytes,6,rep,name=teams,proto3" json:"teams,omitempty"`
	TotalRounds     uint32                 `protobuf:"varint,7,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	FinishedAtMs    uint64                 `protobuf:"varint,8,opt,name=finished_at_ms,json=finishedAtMs,proto3" json:"finished_at_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BattleResultEvent) Reset() {
	*x = BattleResultEvent{}
	mi := &file_proto_contracts_kafka_match_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultEvent) ProtoMessage() {}

func (x *BattleResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_contracts_kafka_match_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultEvent.ProtoReflect.Descriptor instead.
func (*BattleResultEvent) Descriptor() ([]byte, []int) {
	return file_proto_contracts_kafka_match_event_proto_rawDescGZIP(), []int{1}
}

func (x *BattleResultEvent) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleResultEvent) GetMatchMode() uint32 {
	if x != nil {
		return x.MatchMode
	}
	return 0
}

func (x *BattleResultEvent) GetBattleConfigId() uint32 {
	if x != nil {
		return x.BattleConfigId
	}
	return 0
}

func (x *BattleResultEvent) GetOutcome() battle.EBattleOutcome {
	if x != nil {
		return x.Outcome
	}
	return battle.EBattleOutcome(0)
}

func (x *BattleResultEvent) GetWinnerTeamIndex() uint32 {
	if x != nil {
		return x.WinnerTeamIndex
	}
	return 0
}

func (x *BattleResultEvent) GetTeams() []*BattleResultTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *BattleResultEvent) GetTotalRounds() uint32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *BattleResultEvent) GetFinishedAtMs() uint64 {
	if x != nil {
		return x.FinishedAtMs
	}
	return 0
}

var File_proto_contracts_kafka_match_event_proto protoreflect.FileDescriptor

const file_proto_contracts_kafka_match_event_proto_rawDesc = "" +
	"\n" +
	"'proto/contracts/kafka/match_event.proto\x12\x0fcontracts.kafka\x1a\x1eproto/battle/battle_data.proto\"P\n" +
	"\x10BattleResultTeam\x12\x1d\n" +
	"\n" +
	"team_index\x18\x01 \x01(\rR\tteamIndex\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x04R\tplayerIds\"\xd2\x02\n" +
	"\x11BattleResultEvent\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x04R\bbattleId\x12\x1d\n" +
	"\n" +
	"match_mode\x18\x02 \x01(\rR\tmatchMode\x12(\n" +
	"\x10battle_config_id\x18\x03 \x01(\rR\x0ebattleConfigId\x12)\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x0f.eBattleOutcomeR\aoutcome\x12*\n" +
	"\x11winner_team_index\x18\x05 \x01(\rR\x0fwinnerTeamIndex\x127\n" +
	"\x05teams\x18\x06 \x03(\v2!.contracts.kafka.BattleResultTeamR\x05teams\x12!\n" +
	"\ftotal_rounds\x18\a \x01(\rR\vtotalRounds\x12$\n" +
	"\x0efinished_at_ms\x18\b \x01(\x04R\ffinishedAtMsB\x17Z\x15proto/contracts/kafkab\x06proto3"

var (
	file_proto_contracts_kafka_match_event_proto_rawDescOnce sync.Once
	file_proto_contracts_kafka_match_event_proto_rawDescData []byte
)

func file_proto_contracts_kafka_match_event_proto_rawDescGZIP() []byte {
	file_proto_contracts_kafka_match_event_proto_rawDescOnce.Do(func() {
		file_proto_contracts_kafka_match_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_contracts_kafka_match_event_proto_rawDesc), len(file_proto_contracts_kafka_match_event_proto_rawDesc)))
	})
	return file_proto_contracts_kafka_match_event_proto_rawDescData
}

var file_proto_contracts_kafka_match_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_contracts_kafka_match_event_proto_goTypes = []any{
	(*BattleResultTeam)(nil),   // 0: contracts.kafka.BattleResultTeam
	(*BattleResultEvent)(nil),  // 1: contracts.kafka.BattleResultEvent
	(battle.EBattleOutcome)(0), // 2: eBattleOutcome
}
var file_proto_contracts_kafka_match_event_proto_depIdxs = []int32{
	2, // 0: contracts.kafka.BattleResultEvent.outcome:type_name -> eBattleOutcome
	0, // 1: contracts.kafka.BattleResultEvent.teams:type_name -> contracts.kafka.BattleResultTeam
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_contracts_kafka_match_event_proto_init() }
func file_proto_contracts_kafka_match_event_proto_init() {
	if File_proto_contracts_kafka_match_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_contracts_kafka_match_event_proto_rawDesc), len(file_proto_contracts_kafka_match_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_contracts_kafka_match_event_proto_goTypes,
		DependencyIndexes: file_proto_contracts_kafka_match_event_proto_depIdxs,
		MessageInfos:      file_proto_contracts_kafka_match_event_proto_msgTypes,
	}.Build()
	File_proto_contracts_kafka_match_event_proto = out.File
	file_proto_contracts_kafka_match_event_proto_goTypes = nil
	file_proto_contracts_kafka_match_event_proto_depIdxs = nil
}
