// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/guild/guild_db.proto

package guild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "proto/db"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 与 assetop.Status 语义一一映射;数值由本枚举定(1 基:0 留给"漏写状态列的行",它不会被当成未决行领走)。
// guild.proto 的 GuildAssetOrderStatus 是它的客户端镜像,数值逐项相同,新增状态两边同加。
type GuildAssetOpStatus int32

const (
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_UNSPECIFIED     GuildAssetOpStatus = 0
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_PENDING         GuildAssetOpStatus = 1
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_APPLIED         GuildAssetOpStatus = 2
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_REJECTED        GuildAssetOpStatus = 3
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_ABORTED         GuildAssetOpStatus = 4
	GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_APPLIED_PARTIAL GuildAssetOpStatus = 5 // 只终结:不做对侧账、不自动清理,转人工补偿(X-15)
)

// Enum value maps for GuildAssetOpStatus.
var (
	GuildAssetOpStatus_name = map[int32]string{
		0: "GUILD_ASSET_OP_STATUS_UNSPECIFIED",
		1: "GUILD_ASSET_OP_STATUS_PENDING",
		2: "GUILD_ASSET_OP_STATUS_APPLIED",
		3: "GUILD_ASSET_OP_STATUS_REJECTED",
		4: "GUILD_ASSET_OP_STATUS_ABORTED",
		5: "GUILD_ASSET_OP_STATUS_APPLIED_PARTIAL",
	}
	GuildAssetOpStatus_value = map[string]int32{
		"GUILD_ASSET_OP_STATUS_UNSPECIFIED":     0,
		"GUILD_ASSET_OP_STATUS_PENDING":         1,
		"GUILD_ASSET_OP_STATUS_APPLIED":         2,
		"GUILD_ASSET_OP_STATUS_REJECTED":        3,
		"GUILD_ASSET_OP_STATUS_ABORTED":         4,
		"GUILD_ASSET_OP_STATUS_APPLIED_PARTIAL": 5,
	}
)

func (x GuildAssetOpStatus) Enum() *GuildAssetOpStatus {
	p := new(GuildAssetOpStatus)
	*p = x
	return p
}

func (x GuildAssetOpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildAssetOpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_guild_db_proto_enumTypes[0].Descriptor()
}

func (GuildAssetOpStatus) Type() protoreflect.EnumType {
	return &file_proto_guild_guild_db_proto_enumTypes[0]
}

func (x GuildAssetOpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildAssetOpStatus.Descriptor instead.
func (GuildAssetOpStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{0}
}

type GuildAssetOpKind int32

const (
	GuildAssetOpKind_GUILD_ASSET_OP_KIND_UNSPECIFIED     GuildAssetOpKind = 0
	GuildAssetOpKind_GUILD_ASSET_OP_KIND_DONATE          GuildAssetOpKind = 1 // 捐献:GUILD_DEBIT 流扣货币
	GuildAssetOpKind_GUILD_ASSET_OP_KIND_SHOP            GuildAssetOpKind = 2 // 商店:GUILD_CREDIT 流发物品
	GuildAssetOpKind_GUILD_ASSET_OP_KIND_ACTIVITY_REWARD GuildAssetOpKind = 3 // 活动发奖(B6):GUILD_CREDIT 流
)

// Enum value maps for GuildAssetOpKind.
var (
	GuildAssetOpKind_name = map[int32]string{
		0: "GUILD_ASSET_OP_KIND_UNSPECIFIED",
		1: "GUILD_ASSET_OP_KIND_DONATE",
		2: "GUILD_ASSET_OP_KIND_SHOP",
		3: "GUILD_ASSET_OP_KIND_ACTIVITY_REWARD",
	}
	GuildAssetOpKind_value = map[string]int32{
		"GUILD_ASSET_OP_KIND_UNSPECIFIED":     0,
		"GUILD_ASSET_OP_KIND_DONATE":          1,
		"GUILD_ASSET_OP_KIND_SHOP":            2,
		"GUILD_ASSET_OP_KIND_ACTIVITY_REWARD": 3,
	}
)

func (x GuildAssetOpKind) Enum() *GuildAssetOpKind {
	p := new(GuildAssetOpKind)
	*p = x
	return p
}

func (x GuildAssetOpKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildAssetOpKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_guild_db_proto_enumTypes[1].Descriptor()
}

func (GuildAssetOpKind) Type() protoreflect.EnumType {
	return &file_proto_guild_guild_db_proto_enumTypes[1]
}

func (x GuildAssetOpKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildAssetOpKind.Descriptor instead.
func (GuildAssetOpKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{1}
}

type GuildDailyCounterKind int32

const (
	GuildDailyCounterKind_GUILD_DAILY_COUNTER_KIND_UNSPECIFIED GuildDailyCounterKind = 0
	GuildDailyCounterKind_GUILD_DAILY_COUNTER_KIND_DONATE      GuildDailyCounterKind = 1
	GuildDailyCounterKind_GUILD_DAILY_COUNTER_KIND_SHOP        GuildDailyCounterKind = 2
	GuildDailyCounterKind_GUILD_DAILY_COUNTER_KIND_ACTIVITY    GuildDailyCounterKind = 3 // B6
)

// Enum value maps for GuildDailyCounterKind.
var (
	GuildDailyCounterKind_name = map[int32]string{
		0: "GUILD_DAILY_COUNTER_KIND_UNSPECIFIED",
		1: "GUILD_DAILY_COUNTER_KIND_DONATE",
		2: "GUILD_DAILY_COUNTER_KIND_SHOP",
		3: "GUILD_DAILY_COUNTER_KIND_ACTIVITY",
	}
	GuildDailyCounterKind_value = map[string]int32{
		"GUILD_DAILY_COUNTER_KIND_UNSPECIFIED": 0,
		"GUILD_DAILY_COUNTER_KIND_DONATE":      1,
		"GUILD_DAILY_COUNTER_KIND_SHOP":        2,
		"GUILD_DAILY_COUNTER_KIND_ACTIVITY":    3,
	}
)

func (x GuildDailyCounterKind) Enum() *GuildDailyCounterKind {
	p := new(GuildDailyCounterKind)
	*p = x
	return p
}

func (x GuildDailyCounterKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildDailyCounterKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_guild_db_proto_enumTypes[2].Descriptor()
}

func (GuildDailyCounterKind) Type() protoreflect.EnumType {
	return &file_proto_guild_guild_db_proto_enumTypes[2]
}

func (x GuildDailyCounterKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildDailyCounterKind.Descriptor instead.
func (GuildDailyCounterKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{2}
}

// 一局历练在 guild 侧的状态。SETTLED 是唯一的终态,也是结算的幂等闸门。
type GuildTrialBattleState int32

const (
	GuildTrialBattleState_GUILD_TRIAL_BATTLE_STATE_UNSPECIFIED GuildTrialBattleState = 0
	GuildTrialBattleState_GUILD_TRIAL_BATTLE_STATE_STARTED     GuildTrialBattleState = 1 // 已开战、未结算
	GuildTrialBattleState_GUILD_TRIAL_BATTLE_STATE_SETTLED     GuildTrialBattleState = 2 // 已结算(终态;重复的结果事件到这里即止)
	GuildTrialBattleState_GUILD_TRIAL_BATTLE_STATE_EXPIRED     GuildTrialBattleState = 3 // 巡检判定长时间无结果(gather 失败 / 战斗作废);不是终态,迟到的结果仍可把它结算成 SETTLED
)

// Enum value maps for GuildTrialBattleState.
var (
	GuildTrialBattleState_name = map[int32]string{
		0: "GUILD_TRIAL_BATTLE_STATE_UNSPECIFIED",
		1: "GUILD_TRIAL_BATTLE_STATE_STARTED",
		2: "GUILD_TRIAL_BATTLE_STATE_SETTLED",
		3: "GUILD_TRIAL_BATTLE_STATE_EXPIRED",
	}
	GuildTrialBattleState_value = map[string]int32{
		"GUILD_TRIAL_BATTLE_STATE_UNSPECIFIED": 0,
		"GUILD_TRIAL_BATTLE_STATE_STARTED":     1,
		"GUILD_TRIAL_BATTLE_STATE_SETTLED":     2,
		"GUILD_TRIAL_BATTLE_STATE_EXPIRED":     3,
	}
)

func (x GuildTrialBattleState) Enum() *GuildTrialBattleState {
	p := new(GuildTrialBattleState)
	*p = x
	return p
}

func (x GuildTrialBattleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildTrialBattleState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_guild_db_proto_enumTypes[3].Descriptor()
}

func (GuildTrialBattleState) Type() protoreflect.EnumType {
	return &file_proto_guild_guild_db_proto_enumTypes[3]
}

func (x GuildTrialBattleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildTrialBattleState.Descriptor instead.
func (GuildTrialBattleState) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{3}
}

// 结算结论,只在 state = SETTLED 时有意义(其余状态恒为 UNSPECIFIED)。
type GuildTrialSettleResult int32

const (
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_UNSPECIFIED GuildTrialSettleResult = 0
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_WIN         GuildTrialSettleResult = 1
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_LOSS        GuildTrialSettleResult = 2 // 失败 / 平局
	// 保留值,当前代码不写入:历练行只在持有该帮 guild 行锁时才写(见 GuildTrialBattleRecord 注释),帮会已解散就什么都不落,
	// 结果只进日志与指标 guild_trial_result_total{result="guild_gone"}。数值留着是为了日后要落审计时不必改号。
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_GUILD_GONE     GuildTrialSettleResult = 3
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_CONFIG_MISSING GuildTrialSettleResult = 4 // 活动行被删或类型不符,不发奖
	GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_POISON         GuildTrialSettleResult = 5 // 确定性失败(溢出 / 奖励包构建失败 / 结果过旧),不发奖,转人工审计与补发
)

// Enum value maps for GuildTrialSettleResult.
var (
	GuildTrialSettleResult_name = map[int32]string{
		0: "GUILD_TRIAL_SETTLE_RESULT_UNSPECIFIED",
		1: "GUILD_TRIAL_SETTLE_RESULT_WIN",
		2: "GUILD_TRIAL_SETTLE_RESULT_LOSS",
		3: "GUILD_TRIAL_SETTLE_RESULT_GUILD_GONE",
		4: "GUILD_TRIAL_SETTLE_RESULT_CONFIG_MISSING",
		5: "GUILD_TRIAL_SETTLE_RESULT_POISON",
	}
	GuildTrialSettleResult_value = map[string]int32{
		"GUILD_TRIAL_SETTLE_RESULT_UNSPECIFIED":    0,
		"GUILD_TRIAL_SETTLE_RESULT_WIN":            1,
		"GUILD_TRIAL_SETTLE_RESULT_LOSS":           2,
		"GUILD_TRIAL_SETTLE_RESULT_GUILD_GONE":     3,
		"GUILD_TRIAL_SETTLE_RESULT_CONFIG_MISSING": 4,
		"GUILD_TRIAL_SETTLE_RESULT_POISON":         5,
	}
)

func (x GuildTrialSettleResult) Enum() *GuildTrialSettleResult {
	p := new(GuildTrialSettleResult)
	*p = x
	return p
}

func (x GuildTrialSettleResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuildTrialSettleResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_guild_guild_db_proto_enumTypes[4].Descriptor()
}

func (GuildTrialSettleResult) Type() protoreflect.EnumType {
	return &file_proto_guild_guild_db_proto_enumTypes[4]
}

func (x GuildTrialSettleResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuildTrialSettleResult.Descriptor instead.
func (GuildTrialSettleResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{4}
}

type GuildRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`    // data_service 号段 biz_tag=guild
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                          // 展示名:TrimSpace 后原样保存,不建索引;≤ MaxGuildNameRunes=24
	LeaderId      uint64                 `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"` // 与 guild_member.role=3 同事务维护
	Level         uint32                 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                       // 建帮写 1;B5 升级改写
	Announcement  string                 `protobuf:"bytes,5,opt,name=announcement,proto3" json:"announcement,omitempty"`          // ≤ MaxAnnouncementBytes=600
	CreateTimeMs  uint64                 `protobuf:"varint,6,opt,name=create_time_ms,json=createTimeMs,proto3" json:"create_time_ms,omitempty"`
	MaxMembers    uint32                 `protobuf:"varint,7,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"` // 建帮写入;B5 起按 GuildLevel.max_members 改写
	ZoneId        uint32                 `protobuf:"varint,8,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`             // 帮会归属 zone;merge_zone 步骤 3 改写
	Score         int64                  `protobuf:"varint,9,opt,name=score,proto3" json:"score,omitempty"`                             // 排行分权威副本;Redis ZSET 由 RebuildRanks 重建
	Funds         uint64                 `protobuf:"varint,10,opt,name=funds,proto3" json:"funds,omitempty"`                            // 帮会资金;B1 恒为 0,B5 起写入
	NameNorm      string                 `protobuf:"bytes,11,opt,name=name_norm,json=nameNorm,proto3" json:"name_norm,omitempty"`       // data.GuildNameNorm(name):NFKC → TrimSpace → 小写;≤ 48 rune(远小于列长 VARCHAR(191),uk_guild 是整列索引)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildRecord) Reset() {
	*x = GuildRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildRecord) ProtoMessage() {}

func (x *GuildRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildRecord.ProtoReflect.Descriptor instead.
func (*GuildRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{0}
}

func (x *GuildRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuildRecord) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GuildRecord) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GuildRecord) GetAnnouncement() string {
	if x != nil {
		return x.Announcement
	}
	return ""
}

func (x *GuildRecord) GetCreateTimeMs() uint64 {
	if x != nil {
		return x.CreateTimeMs
	}
	return 0
}

func (x *GuildRecord) GetMaxMembers() uint32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *GuildRecord) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *GuildRecord) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GuildRecord) GetFunds() uint64 {
	if x != nil {
		return x.Funds
	}
	return 0
}

func (x *GuildRecord) GetNameNorm() string {
	if x != nil {
		return x.NameNorm
	}
	return ""
}

type GuildPlayerStateRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`    // 每玩家一行,只作串行化锁行(§2.1 规则 3);INSERT IGNORE 于事务外建行
	UpdatedMs     uint64                 `protobuf:"varint,2,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"` // 最近一次加锁写入的时刻,仅诊断用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildPlayerStateRecord) Reset() {
	*x = GuildPlayerStateRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildPlayerStateRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildPlayerStateRecord) ProtoMessage() {}

func (x *GuildPlayerStateRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildPlayerStateRecord.ProtoReflect.Descriptor instead.
func (*GuildPlayerStateRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{1}
}

func (x *GuildPlayerStateRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildPlayerStateRecord) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

type GuildMemberRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GuildId             uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	PlayerId            uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role                uint32                 `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"` // 0 成员 / 1 长老 / 3 帮主(D-4;权限比较走 constants.Rank)
	JoinTimeMs          uint64                 `protobuf:"varint,4,opt,name=join_time_ms,json=joinTimeMs,proto3" json:"join_time_ms,omitempty"`
	LastActiveMs        uint64                 `protobuf:"varint,5,opt,name=last_active_ms,json=lastActiveMs,proto3" json:"last_active_ms,omitempty"`                    // 目前只在入帮时写入
	ContributionTotal   uint64                 `protobuf:"varint,6,opt,name=contribution_total,json=contributionTotal,proto3" json:"contribution_total,omitempty"`       // 累计帮贡,只增;B5 起写入
	ContributionBalance uint64                 `protobuf:"varint,7,opt,name=contribution_balance,json=contributionBalance,proto3" json:"contribution_balance,omitempty"` // 可消费帮贡;商店扣减;B5 起写入
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GuildMemberRecord) Reset() {
	*x = GuildMemberRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildMemberRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildMemberRecord) ProtoMessage() {}

func (x *GuildMemberRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildMemberRecord.ProtoReflect.Descriptor instead.
func (*GuildMemberRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{2}
}

func (x *GuildMemberRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildMemberRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildMemberRecord) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GuildMemberRecord) GetJoinTimeMs() uint64 {
	if x != nil {
		return x.JoinTimeMs
	}
	return 0
}

func (x *GuildMemberRecord) GetLastActiveMs() uint64 {
	if x != nil {
		return x.LastActiveMs
	}
	return 0
}

func (x *GuildMemberRecord) GetContributionTotal() uint64 {
	if x != nil {
		return x.ContributionTotal
	}
	return 0
}

func (x *GuildMemberRecord) GetContributionBalance() uint64 {
	if x != nil {
		return x.ContributionBalance
	}
	return 0
}

type GuildApplicationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GuildId       uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 申请人
	ApplyMs       uint64                 `protobuf:"varint,3,opt,name=apply_ms,json=applyMs,proto3" json:"apply_ms,omitempty"`    // 最近一次申请(重复申请会刷新)的时刻
	ExpireMs      uint64                 `protobuf:"varint,4,opt,name=expire_ms,json=expireMs,proto3" json:"expire_ms,omitempty"` // apply_ms + GuildRule.application_expire_hours × 3600000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildApplicationRecord) Reset() {
	*x = GuildApplicationRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildApplicationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildApplicationRecord) ProtoMessage() {}

func (x *GuildApplicationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildApplicationRecord.ProtoReflect.Descriptor instead.
func (*GuildApplicationRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{3}
}

func (x *GuildApplicationRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildApplicationRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildApplicationRecord) GetApplyMs() uint64 {
	if x != nil {
		return x.ApplyMs
	}
	return 0
}

func (x *GuildApplicationRecord) GetExpireMs() uint64 {
	if x != nil {
		return x.ExpireMs
	}
	return 0
}

type GuildPlayerOpSeqRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Stream        uint32                 `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"` // AssetOpStream 数值(本文件不 import asset_op.proto,避免库表定义依赖通道协议)
	NextSeq       uint64                 `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	UpdatedMs     uint64                 `protobuf:"varint,4,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"`
	Epoch         uint64                 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"` // 建行毫秒,>0;库恢复手册显式抬高(04-asset-channel.md §4.31)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildPlayerOpSeqRecord) Reset() {
	*x = GuildPlayerOpSeqRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildPlayerOpSeqRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildPlayerOpSeqRecord) ProtoMessage() {}

func (x *GuildPlayerOpSeqRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildPlayerOpSeqRecord.ProtoReflect.Descriptor instead.
func (*GuildPlayerOpSeqRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{4}
}

func (x *GuildPlayerOpSeqRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildPlayerOpSeqRecord) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *GuildPlayerOpSeqRecord) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *GuildPlayerOpSeqRecord) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

func (x *GuildPlayerOpSeqRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type GuildAssetOpRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpId              uint64                 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"` // data_service 号段 biz_tag=guild_asset_op;同时作资产通道的 correlation_id
	PlayerId          uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Stream            uint32                 `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"` // AssetOpStream 数值
	Seq               uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	GuildId           uint64                 `protobuf:"varint,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"` // 发起时绑定的帮会;结算一律记给它,不看结算时玩家在哪个帮(D2)
	Kind              GuildAssetOpKind       `protobuf:"varint,6,opt,name=kind,proto3,enum=guildpb.GuildAssetOpKind" json:"kind,omitempty"`
	Status            GuildAssetOpStatus     `protobuf:"varint,7,opt,name=status,proto3,enum=guildpb.GuildAssetOpStatus" json:"status,omitempty"`
	Durable           uint32                 `protobuf:"varint,8,opt,name=durable,proto3" json:"durable,omitempty"` // 0/1:scene 是否已确认落盘
	Attempts          uint32                 `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	NextAttemptMs     uint64                 `protobuf:"varint,10,opt,name=next_attempt_ms,json=nextAttemptMs,proto3" json:"next_attempt_ms,omitempty"`           // 未决:下次重投时刻;终态:终结时刻(清理与回档检查按它判龄)
	DeadlineMs        uint64                 `protobuf:"varint,11,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`                      // 只有 DONATE 非 0;到期改发中止。商店 / 活动发奖恒 0,永不中止
	Payload           []byte                 `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`                                               // AssetBundle 序列化字节
	RefId             uint32                 `protobuf:"varint,13,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`                                     // donate_id / goods_id / activity_id
	RefCount          uint32                 `protobuf:"varint,14,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`                            // 捐献恒 1;商店为份数
	PeriodKey         uint32                 `protobuf:"varint,15,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`                         // 占用的计数行周期键(gameday.DayKey / WeekKey);0 = 未占计数行,退回时跳过
	ContributionDelta uint64                 `protobuf:"varint,16,opt,name=contribution_delta,json=contributionDelta,proto3" json:"contribution_delta,omitempty"` // 捐献:应得帮贡;商店:已扣帮贡(永久拒绝时退回)
	FundsDelta        uint64                 `protobuf:"varint,17,opt,name=funds_delta,json=fundsDelta,proto3" json:"funds_delta,omitempty"`                      // 捐献:应记帮会资金
	ReasonTipId       uint32                 `protobuf:"varint,18,opt,name=reason_tip_id,json=reasonTipId,proto3" json:"reason_tip_id,omitempty"`                 // 终态原因,只在终结时写一次(APPLIED / ABORTED 写 0)
	CreatedMs         uint64                 `protobuf:"varint,19,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`
	UpdatedMs         uint64                 `protobuf:"varint,20,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"`
	LeaseUntilMs      uint64                 `protobuf:"varint,21,opt,name=lease_until_ms,json=leaseUntilMs,proto3" json:"lease_until_ms,omitempty"` // 领取租约截止;0 = 未被领取
	LeaseToken        uint64                 `protobuf:"varint,22,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`         // 领取令牌;Reschedule 须匹配,不匹配 = 租约已被别的副本接走
	TxType            uint32                 `protobuf:"varint,23,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`                     // TransactionType 数值,重投时原样带上
	LastOutcome       uint32                 `protobuf:"varint,24,opt,name=last_outcome,json=lastOutcome,proto3" json:"last_outcome,omitempty"`      // 最近一次 AssetOpOutcome(诊断)
	LastReason        uint32                 `protobuf:"varint,25,opt,name=last_reason,json=lastReason,proto3" json:"last_reason,omitempty"`         // 最近一次 scene 回的 reason:每次 Reschedule / Finalize 覆盖;PENDING 视图展示它;兼作部分发放粘性标记
	StreamEpoch       uint64                 `protobuf:"varint,26,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`      // = 分号时 guild_player_op_seq.epoch
	ResolvedBy        string                 `protobuf:"bytes,27,opt,name=resolved_by,json=resolvedBy,proto3" json:"resolved_by,omitempty"`          // 人工终结(assetopfix)写:操作人,代码侧限 ≤64
	ResolveReason     string                 `protobuf:"bytes,28,opt,name=resolve_reason,json=resolveReason,proto3" json:"resolve_reason,omitempty"` // 人工终结原因,代码侧限 ≤191
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GuildAssetOpRecord) Reset() {
	*x = GuildAssetOpRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildAssetOpRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildAssetOpRecord) ProtoMessage() {}

func (x *GuildAssetOpRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildAssetOpRecord.ProtoReflect.Descriptor instead.
func (*GuildAssetOpRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{5}
}

func (x *GuildAssetOpRecord) GetOpId() uint64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *GuildAssetOpRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildAssetOpRecord) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *GuildAssetOpRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GuildAssetOpRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildAssetOpRecord) GetKind() GuildAssetOpKind {
	if x != nil {
		return x.Kind
	}
	return GuildAssetOpKind_GUILD_ASSET_OP_KIND_UNSPECIFIED
}

func (x *GuildAssetOpRecord) GetStatus() GuildAssetOpStatus {
	if x != nil {
		return x.Status
	}
	return GuildAssetOpStatus_GUILD_ASSET_OP_STATUS_UNSPECIFIED
}

func (x *GuildAssetOpRecord) GetDurable() uint32 {
	if x != nil {
		return x.Durable
	}
	return 0
}

func (x *GuildAssetOpRecord) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *GuildAssetOpRecord) GetNextAttemptMs() uint64 {
	if x != nil {
		return x.NextAttemptMs
	}
	return 0
}

func (x *GuildAssetOpRecord) GetDeadlineMs() uint64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *GuildAssetOpRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GuildAssetOpRecord) GetRefId() uint32 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *GuildAssetOpRecord) GetRefCount() uint32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *GuildAssetOpRecord) GetPeriodKey() uint32 {
	if x != nil {
		return x.PeriodKey
	}
	return 0
}

func (x *GuildAssetOpRecord) GetContributionDelta() uint64 {
	if x != nil {
		return x.ContributionDelta
	}
	return 0
}

func (x *GuildAssetOpRecord) GetFundsDelta() uint64 {
	if x != nil {
		return x.FundsDelta
	}
	return 0
}

func (x *GuildAssetOpRecord) GetReasonTipId() uint32 {
	if x != nil {
		return x.ReasonTipId
	}
	return 0
}

func (x *GuildAssetOpRecord) GetCreatedMs() uint64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *GuildAssetOpRecord) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

func (x *GuildAssetOpRecord) GetLeaseUntilMs() uint64 {
	if x != nil {
		return x.LeaseUntilMs
	}
	return 0
}

func (x *GuildAssetOpRecord) GetLeaseToken() uint64 {
	if x != nil {
		return x.LeaseToken
	}
	return 0
}

func (x *GuildAssetOpRecord) GetTxType() uint32 {
	if x != nil {
		return x.TxType
	}
	return 0
}

func (x *GuildAssetOpRecord) GetLastOutcome() uint32 {
	if x != nil {
		return x.LastOutcome
	}
	return 0
}

func (x *GuildAssetOpRecord) GetLastReason() uint32 {
	if x != nil {
		return x.LastReason
	}
	return 0
}

func (x *GuildAssetOpRecord) GetStreamEpoch() uint64 {
	if x != nil {
		return x.StreamEpoch
	}
	return 0
}

func (x *GuildAssetOpRecord) GetResolvedBy() string {
	if x != nil {
		return x.ResolvedBy
	}
	return ""
}

func (x *GuildAssetOpRecord) GetResolveReason() string {
	if x != nil {
		return x.ResolveReason
	}
	return ""
}

type GuildDailyCounterRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CounterKind   GuildDailyCounterKind  `protobuf:"varint,2,opt,name=counter_kind,json=counterKind,proto3,enum=guildpb.GuildDailyCounterKind" json:"counter_kind,omitempty"`
	RefId         uint32                 `protobuf:"varint,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`             // donate_id / goods_id / activity_id
	PeriodKey     uint32                 `protobuf:"varint,4,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"` // gameday.DayKey(8 位)或 WeekKey(6 位);两个数值域不相交
	UsedCount     uint32                 `protobuf:"varint,5,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"` // 含结算中的占用;REJECTED / ABORTED 时退回
	UpdatedMs     uint64                 `protobuf:"varint,6,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"` // 追加区:从 7 起。计数一律用带上限的 upsert 改写,不得"锁不存在的行再插入"(X-13)。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildDailyCounterRecord) Reset() {
	*x = GuildDailyCounterRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildDailyCounterRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildDailyCounterRecord) ProtoMessage() {}

func (x *GuildDailyCounterRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildDailyCounterRecord.ProtoReflect.Descriptor instead.
func (*GuildDailyCounterRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{6}
}

func (x *GuildDailyCounterRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildDailyCounterRecord) GetCounterKind() GuildDailyCounterKind {
	if x != nil {
		return x.CounterKind
	}
	return GuildDailyCounterKind_GUILD_DAILY_COUNTER_KIND_UNSPECIFIED
}

func (x *GuildDailyCounterRecord) GetRefId() uint32 {
	if x != nil {
		return x.RefId
	}
	return 0
}

func (x *GuildDailyCounterRecord) GetPeriodKey() uint32 {
	if x != nil {
		return x.PeriodKey
	}
	return 0
}

func (x *GuildDailyCounterRecord) GetUsedCount() uint32 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *GuildDailyCounterRecord) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

// ── 帮会活动(B6a)────────────────────────────────────────────────
// 设计:docs/design/guild-phase2/06-activities.md §6.5(表)、§6.11–§6.14(事务与解散)。
// 周期口径(README §3 U1):个人次数不在本表,挂在 guild_daily_counter(counter_kind = ACTIVITY,按游戏日,
// 换帮不重置);本表只记**帮会级**进度,按活动档期 —— 点灯阈值、团圆锁存、资金只发一次,都以这一行为准。
//
// 锁序位置 8:guild_daily_counter(7)之后,B6b 的 guild_trial_battle(9)/ guild_trial_reward_owed(10)之前。
// 本表任一行的锁定者 / 写者都必须先持有同一 guild_id 的 guild 行锁(灯会、团圆、历练结算、解散的第一把锁都是它),
// 本表的行因此在帮会粒度上被 guild 行串行。取锁序列与理由见 go/guild/internal/data/tables.go。
//
// 刻意没有二级索引:读写都是完整主键点操作或 guild_id 主键前缀(视图读、解散删)。v1 不清理旧期行
// (每帮每天至多 3 行);v1.1 若按 period_key 清理需要加 OptionIndex = "period_key" —— schemamigrate 对已存在的表
// 不补建普通索引(只告警),上线前要么定下来、要么开发期删库重建。
type GuildActivityProgressRecord struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	GuildId    uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	ActivityId uint32                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // GuildActivity.id
	// 帮会期键 activity.GuildPeriodKey:灯会 / 团圆 = 档期 start_at_ms 当天的游戏日键(一届活动跨多天仍是同一行);
	// start / end 都为 0 的常开行(仅开发)退化为当天游戏日键;历练 = 开战时的游戏日键(每日计资金胜场上限)。
	PeriodKey          uint32 `protobuf:"varint,3,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`
	ProgressCount      uint32 `protobuf:"varint,4,opt,name=progress_count,json=progressCount,proto3" json:"progress_count,omitempty"`                  // 灯会:本档期点灯人次;历练:本游戏日已计资金胜场;团圆不用(恒 0)
	ThresholdReachedMs uint64 `protobuf:"varint,5,opt,name=threshold_reached_ms,json=thresholdReachedMs,proto3" json:"threshold_reached_ms,omitempty"` // 0 = 未达;非 0 = 首次达成时刻。锁存:写一次后不再改,团圆据此跨游戏日仍可领
	FundsGranted       uint32 `protobuf:"varint,6,opt,name=funds_granted,json=fundsGranted,proto3" json:"funds_granted,omitempty"`                     // 0/1:本期帮会资金已发。与阈值判定在同一把 guild 行锁下读改,保证只发一次
	UpdatedMs          uint64 `protobuf:"varint,7,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"`                              // 追加区:从 8 起。
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GuildActivityProgressRecord) Reset() {
	*x = GuildActivityProgressRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildActivityProgressRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildActivityProgressRecord) ProtoMessage() {}

func (x *GuildActivityProgressRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildActivityProgressRecord.ProtoReflect.Descriptor instead.
func (*GuildActivityProgressRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{7}
}

func (x *GuildActivityProgressRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetPeriodKey() uint32 {
	if x != nil {
		return x.PeriodKey
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetProgressCount() uint32 {
	if x != nil {
		return x.ProgressCount
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetThresholdReachedMs() uint64 {
	if x != nil {
		return x.ThresholdReachedMs
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetFundsGranted() uint32 {
	if x != nil {
		return x.FundsGranted
	}
	return 0
}

func (x *GuildActivityProgressRecord) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

// 一局历练一行:开战时登记(STARTED),结果到达时结算(SETTLED),巡检器把长时间无结果的判为 EXPIRED。
//
// 锁序位置 9(guild_activity_progress 之后)。与 guild_activity_progress 同一条不变量:
// **本表任一行的插入者 / 锁定者 / 写者,都先持有该行 guild_id 对应的 guild 行锁(FOR UPDATE)** ——
// 登记、结算、毒消息标记、巡检判 EXPIRED、解散删在途行的第一把锁都是它;不持 guild 行锁的路径只许普通读。
// 帮会已解散(guild 行不存在)时没有任何路径写本表:解散在同一事务里已删掉该帮全部 STARTED 行,
// 剩下的 SETTLED / EXPIRED 行此后不可变,作历史保留(v1 不清理)。
//
// idx_guild_trial_battle_0 (guild_id, state):解散按"本帮 + STARTED"取候选(在途对局数有上界,与帮会历史长短无关);
// idx_guild_trial_battle_1 (state, created_ms):巡检扫超时的 STARTED 行。
// 06 §6.5 原写 idx_0 = (guild_id):解散改为只删在途行后补上 state 列,候选读才是索引内的范围读,不必回表过滤全部历史行。
type GuildTrialBattleRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BattleId          uint64                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                     // match 发的雪花 id;与 BattleResultEvent.battle_id、SharedRedis 结果键同值
	GuildId           uint64                 `protobuf:"varint,2,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`                        // 发起帮会;插入后不变(本表的守卫行就按它取)
	ActivityId        uint32                 `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`               // GuildActivity.id
	PeriodKey         uint32                 `protobuf:"varint,4,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`                  // 开战时的游戏日键(个人每日次数记在这一天)
	GuildPeriodKey    uint32                 `protobuf:"varint,5,opt,name=guild_period_key,json=guildPeriodKey,proto3" json:"guild_period_key,omitempty"` // 开战时的帮会期键(历练 = 游戏日键;每日计资金胜场上限记在这一期)
	InitiatorPlayerId uint64                 `protobuf:"varint,6,opt,name=initiator_player_id,json=initiatorPlayerId,proto3" json:"initiator_player_id,omitempty"`
	State             GuildTrialBattleState  `protobuf:"varint,7,opt,name=state,proto3,enum=guildpb.GuildTrialBattleState" json:"state,omitempty"`
	SettleResult      GuildTrialSettleResult `protobuf:"varint,8,opt,name=settle_result,json=settleResult,proto3,enum=guildpb.GuildTrialSettleResult" json:"settle_result,omitempty"`
	RewardedCount     uint32                 `protobuf:"varint,9,opt,name=rewarded_count,json=rewardedCount,proto3" json:"rewarded_count,omitempty"` // 得帮贡人数(审计)
	CreatedMs         uint64                 `protobuf:"varint,10,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`            // 登记时刻;结算时补登记的行取对局结束时刻
	SettledMs         uint64                 `protobuf:"varint,11,opt,name=settled_ms,json=settledMs,proto3" json:"settled_ms,omitempty"`            // 进入 SETTLED / EXPIRED 的时刻;STARTED 为 0
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GuildTrialBattleRecord) Reset() {
	*x = GuildTrialBattleRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildTrialBattleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildTrialBattleRecord) ProtoMessage() {}

func (x *GuildTrialBattleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildTrialBattleRecord.ProtoReflect.Descriptor instead.
func (*GuildTrialBattleRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{8}
}

func (x *GuildTrialBattleRecord) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetPeriodKey() uint32 {
	if x != nil {
		return x.PeriodKey
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetGuildPeriodKey() uint32 {
	if x != nil {
		return x.GuildPeriodKey
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetInitiatorPlayerId() uint64 {
	if x != nil {
		return x.InitiatorPlayerId
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetState() GuildTrialBattleState {
	if x != nil {
		return x.State
	}
	return GuildTrialBattleState_GUILD_TRIAL_BATTLE_STATE_UNSPECIFIED
}

func (x *GuildTrialBattleRecord) GetSettleResult() GuildTrialSettleResult {
	if x != nil {
		return x.SettleResult
	}
	return GuildTrialSettleResult_GUILD_TRIAL_SETTLE_RESULT_UNSPECIFIED
}

func (x *GuildTrialBattleRecord) GetRewardedCount() uint32 {
	if x != nil {
		return x.RewardedCount
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetCreatedMs() uint64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

func (x *GuildTrialBattleRecord) GetSettledMs() uint64 {
	if x != nil {
		return x.SettledMs
	}
	return 0
}

// 历练结算时某位得奖者的 GUILD_CREDIT 流未决指令已满(assetop.ErrTooManyPending):物品先记在这里,
// 由后台循环等窗口有空位再转成 guild_asset_op 行(同一事务里删本行)。**绝不跳过** —— 帮贡当场已发,物品只是晚到。
//
// 锁序位置 10(全序末尾)。行的写者:结算(插新行,位置 9 之后)、转换(持该玩家 GUILD_CREDIT 流的 seq 行 → 插指令行 → 点删本行)、
// 诊断计数(自动提交,只改无索引列 attempts)。解散不删:物品属于玩家。
// 有本行就一定有该玩家 GUILD_CREDIT 流的 seq 行(本行正是因为 seq 分配被守卫拒绝才产生的),转换不必再建 seq 行。
//
// idx_guild_trial_reward_owed_0 (created_ms):后台循环按先来后到翻页。
type GuildTrialRewardOwedRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BattleId      uint64                 `protobuf:"varint,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	GuildId       uint64                 `protobuf:"varint,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`          // 结算时的帮会;转入指令行的 guild_id,此外只作审计
	ActivityId    uint32                 `protobuf:"varint,4,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 转入指令行的 ref_id
	PeriodKey     uint32                 `protobuf:"varint,5,opt,name=period_key,json=periodKey,proto3" json:"period_key,omitempty"`    // 转入指令行的 period_key(开战时的游戏日键,审计用)
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`                          // AssetBundle 序列化字节,原样转入指令行
	Attempts      uint32                 `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`                       // 因窗口仍满而跳过的轮数(诊断)
	CreatedMs     uint64                 `protobuf:"varint,8,opt,name=created_ms,json=createdMs,proto3" json:"created_ms,omitempty"`    // 追加区:从 9 起。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuildTrialRewardOwedRecord) Reset() {
	*x = GuildTrialRewardOwedRecord{}
	mi := &file_proto_guild_guild_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildTrialRewardOwedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildTrialRewardOwedRecord) ProtoMessage() {}

func (x *GuildTrialRewardOwedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildTrialRewardOwedRecord.ProtoReflect.Descriptor instead.
func (*GuildTrialRewardOwedRecord) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_db_proto_rawDescGZIP(), []int{9}
}

func (x *GuildTrialRewardOwedRecord) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetActivityId() uint32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetPeriodKey() uint32 {
	if x != nil {
		return x.PeriodKey
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GuildTrialRewardOwedRecord) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *GuildTrialRewardOwedRecord) GetCreatedMs() uint64 {
	if x != nil {
		return x.CreatedMs
	}
	return 0
}

var File_proto_guild_guild_db_proto protoreflect.FileDescriptor

const file_proto_guild_guild_db_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/guild/guild_db.proto\x12\aguildpb\x1a\x1bproto/db/proto_option.proto\"\x88\x03\n" +
	"\vGuildRecord\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\x04R\bleaderId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\rR\x05level\x12\"\n" +
	"\fannouncement\x18\x05 \x01(\tR\fannouncement\x12$\n" +
	"\x0ecreate_time_ms\x18\x06 \x01(\x04R\fcreateTimeMs\x12\x1f\n" +
	"\vmax_members\x18\a \x01(\rR\n" +
	"maxMembers\x12\x17\n" +
	"\azone_id\x18\b \x01(\rR\x06zoneId\x12\x14\n" +
	"\x05score\x18\t \x01(\x03R\x05score\x12\x14\n" +
	"\x05funds\x18\n" +
	" \x01(\x04R\x05funds\x12\x1b\n" +
	"\tname_norm\x18\v \x01(\tR\bnameNorm:J\x8a\x92\xf4\x01\x05guild\x92\x92\xf4\x01\bguild_idڒ\xf4\x01\x11zone_id;leader_id\xe2\x92\xf4\x01\tname_norm\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\x8a\x01\n" +
	"\x16GuildPlayerStateRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\x02 \x01(\x04R\tupdatedMs:4\x8a\x92\xf4\x01\x12guild_player_state\x92\x92\xf4\x01\tplayer_id\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xd0\x02\n" +
	"\x11GuildMemberRecord\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\rR\x04role\x12 \n" +
	"\fjoin_time_ms\x18\x04 \x01(\x04R\n" +
	"joinTimeMs\x12$\n" +
	"\x0elast_active_ms\x18\x05 \x01(\x04R\flastActiveMs\x12-\n" +
	"\x12contribution_total\x18\x06 \x01(\x04R\x11contributionTotal\x121\n" +
	"\x14contribution_balance\x18\a \x01(\x04R\x13contributionBalance:E\x8a\x92\xf4\x01\fguild_member\x92\x92\xf4\x01\x12guild_id,player_id\xe2\x92\xf4\x01\tplayer_id\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xde\x01\n" +
	"\x16GuildApplicationRecord\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bapply_ms\x18\x03 \x01(\x04R\aapplyMs\x12\x1b\n" +
	"\texpire_ms\x18\x04 \x01(\x04R\bexpireMs:T\x8a\x92\xf4\x01\x11guild_application\x92\x92\xf4\x01\x12guild_id,player_idڒ\xf4\x01\x13player_id;expire_ms\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xdb\x01\n" +
	"\x16GuildPlayerOpSeqRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\rR\x06stream\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x04R\anextSeq\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\x04 \x01(\x04R\tupdatedMs\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x04R\x05epoch:<\x8a\x92\xf4\x01\x13guild_player_op_seq\x92\x92\xf4\x01\x10player_id,stream\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xc4\b\n" +
	"\x12GuildAssetOpRecord\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\x04R\x04opId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\rR\x06stream\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x19\n" +
	"\bguild_id\x18\x05 \x01(\x04R\aguildId\x12-\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x19.guildpb.GuildAssetOpKindR\x04kind\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.guildpb.GuildAssetOpStatusR\x06status\x12\x18\n" +
	"\adurable\x18\b \x01(\rR\adurable\x12\x1a\n" +
	"\battempts\x18\t \x01(\rR\battempts\x12&\n" +
	"\x0fnext_attempt_ms\x18\n" +
	" \x01(\x04R\rnextAttemptMs\x12\x1f\n" +
	"\vdeadline_ms\x18\v \x01(\x04R\n" +
	"deadlineMs\x12\x18\n" +
	"\apayload\x18\f \x01(\fR\apayload\x12\x15\n" +
	"\x06ref_id\x18\r \x01(\rR\x05refId\x12\x1b\n" +
	"\tref_count\x18\x0e \x01(\rR\brefCount\x12\x1d\n" +
	"\n" +
	"period_key\x18\x0f \x01(\rR\tperiodKey\x12-\n" +
	"\x12contribution_delta\x18\x10 \x01(\x04R\x11contributionDelta\x12\x1f\n" +
	"\vfunds_delta\x18\x11 \x01(\x04R\n" +
	"fundsDelta\x12\"\n" +
	"\rreason_tip_id\x18\x12 \x01(\rR\vreasonTipId\x12\x1d\n" +
	"\n" +
	"created_ms\x18\x13 \x01(\x04R\tcreatedMs\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\x14 \x01(\x04R\tupdatedMs\x12$\n" +
	"\x0elease_until_ms\x18\x15 \x01(\x04R\fleaseUntilMs\x12\x1f\n" +
	"\vlease_token\x18\x16 \x01(\x04R\n" +
	"leaseToken\x12\x17\n" +
	"\atx_type\x18\x17 \x01(\rR\x06txType\x12!\n" +
	"\flast_outcome\x18\x18 \x01(\rR\vlastOutcome\x12\x1f\n" +
	"\vlast_reason\x18\x19 \x01(\rR\n" +
	"lastReason\x12!\n" +
	"\fstream_epoch\x18\x1a \x01(\x04R\vstreamEpoch\x12\x1f\n" +
	"\vresolved_by\x18\x1b \x01(\tR\n" +
	"resolvedBy\x12%\n" +
	"\x0eresolve_reason\x18\x1c \x01(\tR\rresolveReason:\xa5\x01\x8a\x92\xf4\x01\x0eguild_asset_op\x92\x92\xf4\x01\x05op_idڒ\xf4\x01Nstatus,next_attempt_ms;guild_id,op_id;player_id,stream,stream_epoch,status,seq\xe2\x92\xf4\x01!player_id,stream,stream_epoch,seq\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xd2\x02\n" +
	"\x17GuildDailyCounterRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12A\n" +
	"\fcounter_kind\x18\x02 \x01(\x0e2\x1e.guildpb.GuildDailyCounterKindR\vcounterKind\x12\x15\n" +
	"\x06ref_id\x18\x03 \x01(\rR\x05refId\x12\x1d\n" +
	"\n" +
	"period_key\x18\x04 \x01(\rR\tperiodKey\x12\x1d\n" +
	"\n" +
	"used_count\x18\x05 \x01(\rR\tusedCount\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\x06 \x01(\x04R\tupdatedMs:c\x8a\x92\xf4\x01\x13guild_daily_counter\x92\x92\xf4\x01(player_id,counter_kind,ref_id,period_keyڒ\xf4\x01\n" +
	"period_key\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xe6\x02\n" +
	"\x1bGuildActivityProgressRecord\x12\x19\n" +
	"\bguild_id\x18\x01 \x01(\x04R\aguildId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\rR\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"period_key\x18\x03 \x01(\rR\tperiodKey\x12%\n" +
	"\x0eprogress_count\x18\x04 \x01(\rR\rprogressCount\x120\n" +
	"\x14threshold_reached_ms\x18\x05 \x01(\x04R\x12thresholdReachedMs\x12#\n" +
	"\rfunds_granted\x18\x06 \x01(\rR\ffundsGranted\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\a \x01(\x04R\tupdatedMs:O\x8a\x92\xf4\x01\x17guild_activity_progress\x92\x92\xf4\x01\x1fguild_id,activity_id,period_key\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xa5\x04\n" +
	"\x16GuildTrialBattleRecord\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\x04R\bbattleId\x12\x19\n" +
	"\bguild_id\x18\x02 \x01(\x04R\aguildId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\rR\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"period_key\x18\x04 \x01(\rR\tperiodKey\x12(\n" +
	"\x10guild_period_key\x18\x05 \x01(\rR\x0eguildPeriodKey\x12.\n" +
	"\x13initiator_player_id\x18\x06 \x01(\x04R\x11initiatorPlayerId\x124\n" +
	"\x05state\x18\a \x01(\x0e2\x1e.guildpb.GuildTrialBattleStateR\x05state\x12D\n" +
	"\rsettle_result\x18\b \x01(\x0e2\x1f.guildpb.GuildTrialSettleResultR\fsettleResult\x12%\n" +
	"\x0erewarded_count\x18\t \x01(\rR\rrewardedCount\x12\x1d\n" +
	"\n" +
	"created_ms\x18\n" +
	" \x01(\x04R\tcreatedMs\x12\x1d\n" +
	"\n" +
	"settled_ms\x18\v \x01(\x04R\tsettledMs:X\x8a\x92\xf4\x01\x12guild_trial_battle\x92\x92\xf4\x01\tbattle_idڒ\xf4\x01\x1fguild_id,state;state,created_ms\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04\"\xda\x02\n" +
	"\x1aGuildTrialRewardOwedRecord\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\x04R\bbattleId\x12\x19\n" +
	"\bguild_id\x18\x03 \x01(\x04R\aguildId\x12\x1f\n" +
	"\vactivity_id\x18\x04 \x01(\rR\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"period_key\x18\x05 \x01(\rR\tperiodKey\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1a\n" +
	"\battempts\x18\a \x01(\rR\battempts\x12\x1d\n" +
	"\n" +
	"created_ms\x18\b \x01(\x04R\tcreatedMs:R\x8a\x92\xf4\x01\x17guild_trial_reward_owed\x92\x92\xf4\x01\x13player_id,battle_idڒ\xf4\x01\n" +
	"created_ms\xa8\x93\xf4\x01\x01\xb0\x93\xf4\x01\x04\xb8\x93\xf4\x01\x04*\xf3\x01\n" +
	"\x12GuildAssetOpStatus\x12%\n" +
	"!GUILD_ASSET_OP_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dGUILD_ASSET_OP_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dGUILD_ASSET_OP_STATUS_APPLIED\x10\x02\x12\"\n" +
	"\x1eGUILD_ASSET_OP_STATUS_REJECTED\x10\x03\x12!\n" +
	"\x1dGUILD_ASSET_OP_STATUS_ABORTED\x10\x04\x12)\n" +
	"%GUILD_ASSET_OP_STATUS_APPLIED_PARTIAL\x10\x05*\x9e\x01\n" +
	"\x10GuildAssetOpKind\x12#\n" +
	"\x1fGUILD_ASSET_OP_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGUILD_ASSET_OP_KIND_DONATE\x10\x01\x12\x1c\n" +
	"\x18GUILD_ASSET_OP_KIND_SHOP\x10\x02\x12'\n" +
	"#GUILD_ASSET_OP_KIND_ACTIVITY_REWARD\x10\x03*\xb0\x01\n" +
	"\x15GuildDailyCounterKind\x12(\n" +
	"$GUILD_DAILY_COUNTER_KIND_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fGUILD_DAILY_COUNTER_KIND_DONATE\x10\x01\x12!\n" +
	"\x1dGUILD_DAILY_COUNTER_KIND_SHOP\x10\x02\x12%\n" +
	"!GUILD_DAILY_COUNTER_KIND_ACTIVITY\x10\x03*\xb3\x01\n" +
	"\x15GuildTrialBattleState\x12(\n" +
	"$GUILD_TRIAL_BATTLE_STATE_UNSPECIFIED\x10\x00\x12$\n" +
	" GUILD_TRIAL_BATTLE_STATE_STARTED\x10\x01\x12$\n" +
	" GUILD_TRIAL_BATTLE_STATE_SETTLED\x10\x02\x12$\n" +
	" GUILD_TRIAL_BATTLE_STATE_EXPIRED\x10\x03*\x88\x02\n" +
	"\x16GuildTrialSettleResult\x12)\n" +
	"%GUILD_TRIAL_SETTLE_RESULT_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dGUILD_TRIAL_SETTLE_RESULT_WIN\x10\x01\x12\"\n" +
	"\x1eGUILD_TRIAL_SETTLE_RESULT_LOSS\x10\x02\x12(\n" +
	"$GUILD_TRIAL_SETTLE_RESULT_GUILD_GONE\x10\x03\x12,\n" +
	"(GUILD_TRIAL_SETTLE_RESULT_CONFIG_MISSING\x10\x04\x12$\n" +
	" GUILD_TRIAL_SETTLE_RESULT_POISON\x10\x05B\rZ\vproto/guildb\x06proto3"

var (
	file_proto_guild_guild_db_proto_rawDescOnce sync.Once
	file_proto_guild_guild_db_proto_rawDescData []byte
)

func file_proto_guild_guild_db_proto_rawDescGZIP() []byte {
	file_proto_guild_guild_db_proto_rawDescOnce.Do(func() {
		file_proto_guild_guild_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_guild_guild_db_proto_rawDesc), len(file_proto_guild_guild_db_proto_rawDesc)))
	})
	return file_proto_guild_guild_db_proto_rawDescData
}

var file_proto_guild_guild_db_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_guild_guild_db_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_guild_guild_db_proto_goTypes = []any{
	(GuildAssetOpStatus)(0),             // 0: guildpb.GuildAssetOpStatus
	(GuildAssetOpKind)(0),               // 1: guildpb.GuildAssetOpKind
	(GuildDailyCounterKind)(0),          // 2: guildpb.GuildDailyCounterKind
	(GuildTrialBattleState)(0),          // 3: guildpb.GuildTrialBattleState
	(GuildTrialSettleResult)(0),         // 4: guildpb.GuildTrialSettleResult
	(*GuildRecord)(nil),                 // 5: guildpb.GuildRecord
	(*GuildPlayerStateRecord)(nil),      // 6: guildpb.GuildPlayerStateRecord
	(*GuildMemberRecord)(nil),           // 7: guildpb.GuildMemberRecord
	(*GuildApplicationRecord)(nil),      // 8: guildpb.GuildApplicationRecord
	(*GuildPlayerOpSeqRecord)(nil),      // 9: guildpb.GuildPlayerOpSeqRecord
	(*GuildAssetOpRecord)(nil),          // 10: guildpb.GuildAssetOpRecord
	(*GuildDailyCounterRecord)(nil),     // 11: guildpb.GuildDailyCounterRecord
	(*GuildActivityProgressRecord)(nil), // 12: guildpb.GuildActivityProgressRecord
	(*GuildTrialBattleRecord)(nil),      // 13: guildpb.GuildTrialBattleRecord
	(*GuildTrialRewardOwedRecord)(nil),  // 14: guildpb.GuildTrialRewardOwedRecord
}
var file_proto_guild_guild_db_proto_depIdxs = []int32{
	1, // 0: guildpb.GuildAssetOpRecord.kind:type_name -> guildpb.GuildAssetOpKind
	0, // 1: guildpb.GuildAssetOpRecord.status:type_name -> guildpb.GuildAssetOpStatus
	2, // 2: guildpb.GuildDailyCounterRecord.counter_kind:type_name -> guildpb.GuildDailyCounterKind
	3, // 3: guildpb.GuildTrialBattleRecord.state:type_name -> guildpb.GuildTrialBattleState
	4, // 4: guildpb.GuildTrialBattleRecord.settle_result:type_name -> guildpb.GuildTrialSettleResult
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_guild_guild_db_proto_init() }
func file_proto_guild_guild_db_proto_init() {
	if File_proto_guild_guild_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_guild_guild_db_proto_rawDesc), len(file_proto_guild_guild_db_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_guild_guild_db_proto_goTypes,
		DependencyIndexes: file_proto_guild_guild_db_proto_depIdxs,
		EnumInfos:         file_proto_guild_guild_db_proto_enumTypes,
		MessageInfos:      file_proto_guild_guild_db_proto_msgTypes,
	}.Build()
	File_proto_guild_guild_db_proto = out.File
	file_proto_guild_guild_db_proto_goTypes = nil
	file_proto_guild_guild_db_proto_depIdxs = nil
}
