// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/guild/guild_internal.proto

package guild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已终结为"已应用"的资产操作摘要。只读,不含 payload。
type GuildAssetOpBrief struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OpId              uint64                 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	PlayerId          uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GuildId           uint64                 `protobuf:"varint,3,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"` // 发起时绑定的帮会;该帮会可能已解散
	Stream            uint32                 `protobuf:"varint,4,opt,name=stream,proto3" json:"stream,omitempty"`                  // AssetOpStream 数值(与 guild_db.proto 一致,不 import asset_op.proto)
	Kind              uint32                 `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`                      // GuildAssetOpKind 数值
	Status            uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                  // GuildAssetOpStatus 数值;只会是 APPLIED 或 APPLIED_PARTIAL
	FundsDelta        uint64                 `protobuf:"varint,7,opt,name=funds_delta,json=fundsDelta,proto3" json:"funds_delta,omitempty"`
	ContributionDelta uint64                 `protobuf:"varint,8,opt,name=contribution_delta,json=contributionDelta,proto3" json:"contribution_delta,omitempty"`
	UpdatedMs         uint64                 `protobuf:"varint,9,opt,name=updated_ms,json=updatedMs,proto3" json:"updated_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GuildAssetOpBrief) Reset() {
	*x = GuildAssetOpBrief{}
	mi := &file_proto_guild_guild_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuildAssetOpBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildAssetOpBrief) ProtoMessage() {}

func (x *GuildAssetOpBrief) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildAssetOpBrief.ProtoReflect.Descriptor instead.
func (*GuildAssetOpBrief) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_internal_proto_rawDescGZIP(), []int{0}
}

func (x *GuildAssetOpBrief) GetOpId() uint64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *GuildAssetOpBrief) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GuildAssetOpBrief) GetGuildId() uint64 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *GuildAssetOpBrief) GetStream() uint32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *GuildAssetOpBrief) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *GuildAssetOpBrief) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GuildAssetOpBrief) GetFundsDelta() uint64 {
	if x != nil {
		return x.FundsDelta
	}
	return 0
}

func (x *GuildAssetOpBrief) GetContributionDelta() uint64 {
	if x != nil {
		return x.ContributionDelta
	}
	return 0
}

func (x *GuildAssetOpBrief) GetUpdatedMs() uint64 {
	if x != nil {
		return x.UpdatedMs
	}
	return 0
}

type ListAppliedAssetOpsSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        uint32                 `protobuf:"varint,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                 // 0 = 不按 zone 收窄(data_service 恒传 0,理由见 07 §7.4.3)
	PlayerIds     []uint64               `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"` // 必填,1..100,不得含 0、不得重复
	SinceMs       uint64                 `protobuf:"varint,3,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`              // 必填 > 0;只返回终结时刻严格晚于它的行
	AfterOpId     uint64                 `protobuf:"varint,4,opt,name=after_op_id,json=afterOpId,proto3" json:"after_op_id,omitempty"`      // 游标;首页传 0
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                 // 0 → 500;> 500 → InvalidArgument
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppliedAssetOpsSinceRequest) Reset() {
	*x = ListAppliedAssetOpsSinceRequest{}
	mi := &file_proto_guild_guild_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppliedAssetOpsSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppliedAssetOpsSinceRequest) ProtoMessage() {}

func (x *ListAppliedAssetOpsSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppliedAssetOpsSinceRequest.ProtoReflect.Descriptor instead.
func (*ListAppliedAssetOpsSinceRequest) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ListAppliedAssetOpsSinceRequest) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *ListAppliedAssetOpsSinceRequest) GetPlayerIds() []uint64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *ListAppliedAssetOpsSinceRequest) GetSinceMs() uint64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *ListAppliedAssetOpsSinceRequest) GetAfterOpId() uint64 {
	if x != nil {
		return x.AfterOpId
	}
	return 0
}

func (x *ListAppliedAssetOpsSinceRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAppliedAssetOpsSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*GuildAssetOpBrief   `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`                                               // 按 op_id 升序
	NextAfterOpId uint64                 `protobuf:"varint,2,opt,name=next_after_op_id,json=nextAfterOpId,proto3" json:"next_after_op_id,omitempty"` // 0 = 已查尽;否则 = 本页最后一行的 op_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppliedAssetOpsSinceResponse) Reset() {
	*x = ListAppliedAssetOpsSinceResponse{}
	mi := &file_proto_guild_guild_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppliedAssetOpsSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppliedAssetOpsSinceResponse) ProtoMessage() {}

func (x *ListAppliedAssetOpsSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_guild_guild_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppliedAssetOpsSinceResponse.ProtoReflect.Descriptor instead.
func (*ListAppliedAssetOpsSinceResponse) Descriptor() ([]byte, []int) {
	return file_proto_guild_guild_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ListAppliedAssetOpsSinceResponse) GetOps() []*GuildAssetOpBrief {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *ListAppliedAssetOpsSinceResponse) GetNextAfterOpId() uint64 {
	if x != nil {
		return x.NextAfterOpId
	}
	return 0
}

var File_proto_guild_guild_internal_proto protoreflect.FileDescriptor

const file_proto_guild_guild_internal_proto_rawDesc = "" +
	"\n" +
	" proto/guild/guild_internal.proto\x12\aguildpb\"\x93\x02\n" +
	"\x11GuildAssetOpBrief\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\x04R\x04opId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\x12\x19\n" +
	"\bguild_id\x18\x03 \x01(\x04R\aguildId\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\rR\x06stream\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\rR\x04kind\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12\x1f\n" +
	"\vfunds_delta\x18\a \x01(\x04R\n" +
	"fundsDelta\x12-\n" +
	"\x12contribution_delta\x18\b \x01(\x04R\x11contributionDelta\x12\x1d\n" +
	"\n" +
	"updated_ms\x18\t \x01(\x04R\tupdatedMs\"\xaa\x01\n" +
	"\x1fListAppliedAssetOpsSinceRequest\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\rR\x06zoneId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x04R\tplayerIds\x12\x19\n" +
	"\bsince_ms\x18\x03 \x01(\x04R\asinceMs\x12\x1e\n" +
	"\vafter_op_id\x18\x04 \x01(\x04R\tafterOpId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"y\n" +
	" ListAppliedAssetOpsSinceResponse\x12,\n" +
	"\x03ops\x18\x01 \x03(\v2\x1a.guildpb.GuildAssetOpBriefR\x03ops\x12'\n" +
	"\x10next_after_op_id\x18\x02 \x01(\x04R\rnextAfterOpId2\x80\x01\n" +
	"\rGuildInternal\x12o\n" +
	"\x18ListAppliedAssetOpsSince\x12(.guildpb.ListAppliedAssetOpsSinceRequest\x1a).guildpb.ListAppliedAssetOpsSinceResponseB\rZ\vproto/guildb\x06proto3"

var (
	file_proto_guild_guild_internal_proto_rawDescOnce sync.Once
	file_proto_guild_guild_internal_proto_rawDescData []byte
)

func file_proto_guild_guild_internal_proto_rawDescGZIP() []byte {
	file_proto_guild_guild_internal_proto_rawDescOnce.Do(func() {
		file_proto_guild_guild_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_guild_guild_internal_proto_rawDesc), len(file_proto_guild_guild_internal_proto_rawDesc)))
	})
	return file_proto_guild_guild_internal_proto_rawDescData
}

var file_proto_guild_guild_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_guild_guild_internal_proto_goTypes = []any{
	(*GuildAssetOpBrief)(nil),                // 0: guildpb.GuildAssetOpBrief
	(*ListAppliedAssetOpsSinceRequest)(nil),  // 1: guildpb.ListAppliedAssetOpsSinceRequest
	(*ListAppliedAssetOpsSinceResponse)(nil), // 2: guildpb.ListAppliedAssetOpsSinceResponse
}
var file_proto_guild_guild_internal_proto_depIdxs = []int32{
	0, // 0: guildpb.ListAppliedAssetOpsSinceResponse.ops:type_name -> guildpb.GuildAssetOpBrief
	1, // 1: guildpb.GuildInternal.ListAppliedAssetOpsSince:input_type -> guildpb.ListAppliedAssetOpsSinceRequest
	2, // 2: guildpb.GuildInternal.ListAppliedAssetOpsSince:output_type -> guildpb.ListAppliedAssetOpsSinceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_guild_guild_internal_proto_init() }
func file_proto_guild_guild_internal_proto_init() {
	if File_proto_guild_guild_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_guild_guild_internal_proto_rawDesc), len(file_proto_guild_guild_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_guild_guild_internal_proto_goTypes,
		DependencyIndexes: file_proto_guild_guild_internal_proto_depIdxs,
		MessageInfos:      file_proto_guild_guild_internal_proto_msgTypes,
	}.Build()
	File_proto_guild_guild_internal_proto = out.File
	file_proto_guild_guild_internal_proto_goTypes = nil
	file_proto_guild_guild_internal_proto_depIdxs = nil
}
