// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: attributepool_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

/**
 * Protobuf type {@code AttributePoolTable}
 */
@com.google.protobuf.Generated
public final class AttributePoolTable extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AttributePoolTable)
    AttributePoolTableOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AttributePoolTable");
  }
  // Use AttributePoolTable.newBuilder() to construct.
  private AttributePoolTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AttributePoolTable() {
    name_ = "";
    desc_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.table.AttributePoolTable.class, com.game.table.AttributePoolTable.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNLOCK_LEVEL_FIELD_NUMBER = 3;
  private int unlockLevel_ = 0;
  /**
   * <code>uint32 unlock_level = 3;</code>
   * @return The unlockLevel.
   */
  @java.lang.Override
  public int getUnlockLevel() {
    return unlockLevel_;
  }

  public static final int POINTS_PER_LEVEL_FIELD_NUMBER = 4;
  private int pointsPerLevel_ = 0;
  /**
   * <code>uint32 points_per_level = 4;</code>
   * @return The pointsPerLevel.
   */
  @java.lang.Override
  public int getPointsPerLevel() {
    return pointsPerLevel_;
  }

  public static final int BASE_POINTS_FIELD_NUMBER = 5;
  private int basePoints_ = 0;
  /**
   * <code>uint32 base_points = 5;</code>
   * @return The basePoints.
   */
  @java.lang.Override
  public int getBasePoints() {
    return basePoints_;
  }

  public static final int DIMENSION_CAP_FIELD_NUMBER = 6;
  private int dimensionCap_ = 0;
  /**
   * <code>uint32 dimension_cap = 6;</code>
   * @return The dimensionCap.
   */
  @java.lang.Override
  public int getDimensionCap() {
    return dimensionCap_;
  }

  public static final int RESET_COST_GOLD_FIELD_NUMBER = 7;
  private long resetCostGold_ = 0L;
  /**
   * <code>uint64 reset_cost_gold = 7;</code>
   * @return The resetCostGold.
   */
  @java.lang.Override
  public long getResetCostGold() {
    return resetCostGold_;
  }

  public static final int RESET_FREE_BELOW_LEVEL_FIELD_NUMBER = 8;
  private int resetFreeBelowLevel_ = 0;
  /**
   * <code>uint32 reset_free_below_level = 8;</code>
   * @return The resetFreeBelowLevel.
   */
  @java.lang.Override
  public int getResetFreeBelowLevel() {
    return resetFreeBelowLevel_;
  }

  public static final int DESC_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 9;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 9;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (unlockLevel_ != 0) {
      output.writeUInt32(3, unlockLevel_);
    }
    if (pointsPerLevel_ != 0) {
      output.writeUInt32(4, pointsPerLevel_);
    }
    if (basePoints_ != 0) {
      output.writeUInt32(5, basePoints_);
    }
    if (dimensionCap_ != 0) {
      output.writeUInt32(6, dimensionCap_);
    }
    if (resetCostGold_ != 0L) {
      output.writeUInt64(7, resetCostGold_);
    }
    if (resetFreeBelowLevel_ != 0) {
      output.writeUInt32(8, resetFreeBelowLevel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, desc_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (unlockLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, unlockLevel_);
    }
    if (pointsPerLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, pointsPerLevel_);
    }
    if (basePoints_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, basePoints_);
    }
    if (dimensionCap_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, dimensionCap_);
    }
    if (resetCostGold_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, resetCostGold_);
    }
    if (resetFreeBelowLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, resetFreeBelowLevel_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, desc_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.table.AttributePoolTable)) {
      return super.equals(obj);
    }
    com.game.table.AttributePoolTable other = (com.game.table.AttributePoolTable) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getUnlockLevel()
        != other.getUnlockLevel()) return false;
    if (getPointsPerLevel()
        != other.getPointsPerLevel()) return false;
    if (getBasePoints()
        != other.getBasePoints()) return false;
    if (getDimensionCap()
        != other.getDimensionCap()) return false;
    if (getResetCostGold()
        != other.getResetCostGold()) return false;
    if (getResetFreeBelowLevel()
        != other.getResetFreeBelowLevel()) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + UNLOCK_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getUnlockLevel();
    hash = (37 * hash) + POINTS_PER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getPointsPerLevel();
    hash = (37 * hash) + BASE_POINTS_FIELD_NUMBER;
    hash = (53 * hash) + getBasePoints();
    hash = (37 * hash) + DIMENSION_CAP_FIELD_NUMBER;
    hash = (53 * hash) + getDimensionCap();
    hash = (37 * hash) + RESET_COST_GOLD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getResetCostGold());
    hash = (37 * hash) + RESET_FREE_BELOW_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getResetFreeBelowLevel();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.table.AttributePoolTable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributePoolTable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributePoolTable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.table.AttributePoolTable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.table.AttributePoolTable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.AttributePoolTable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.table.AttributePoolTable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AttributePoolTable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AttributePoolTable)
      com.game.table.AttributePoolTableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.table.AttributePoolTable.class, com.game.table.AttributePoolTable.Builder.class);
    }

    // Construct using com.game.table.AttributePoolTable.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      name_ = "";
      unlockLevel_ = 0;
      pointsPerLevel_ = 0;
      basePoints_ = 0;
      dimensionCap_ = 0;
      resetCostGold_ = 0L;
      resetFreeBelowLevel_ = 0;
      desc_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.table.AttributePoolTableOuterClass.internal_static_AttributePoolTable_descriptor;
    }

    @java.lang.Override
    public com.game.table.AttributePoolTable getDefaultInstanceForType() {
      return com.game.table.AttributePoolTable.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.table.AttributePoolTable build() {
      com.game.table.AttributePoolTable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.table.AttributePoolTable buildPartial() {
      com.game.table.AttributePoolTable result = new com.game.table.AttributePoolTable(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.table.AttributePoolTable result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.unlockLevel_ = unlockLevel_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.pointsPerLevel_ = pointsPerLevel_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.basePoints_ = basePoints_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dimensionCap_ = dimensionCap_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.resetCostGold_ = resetCostGold_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.resetFreeBelowLevel_ = resetFreeBelowLevel_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.desc_ = desc_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.table.AttributePoolTable) {
        return mergeFrom((com.game.table.AttributePoolTable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.table.AttributePoolTable other) {
      if (other == com.game.table.AttributePoolTable.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getUnlockLevel() != 0) {
        setUnlockLevel(other.getUnlockLevel());
      }
      if (other.getPointsPerLevel() != 0) {
        setPointsPerLevel(other.getPointsPerLevel());
      }
      if (other.getBasePoints() != 0) {
        setBasePoints(other.getBasePoints());
      }
      if (other.getDimensionCap() != 0) {
        setDimensionCap(other.getDimensionCap());
      }
      if (other.getResetCostGold() != 0L) {
        setResetCostGold(other.getResetCostGold());
      }
      if (other.getResetFreeBelowLevel() != 0) {
        setResetFreeBelowLevel(other.getResetFreeBelowLevel());
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              unlockLevel_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              pointsPerLevel_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              basePoints_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              dimensionCap_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              resetCostGold_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              resetFreeBelowLevel_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int unlockLevel_ ;
    /**
     * <code>uint32 unlock_level = 3;</code>
     * @return The unlockLevel.
     */
    @java.lang.Override
    public int getUnlockLevel() {
      return unlockLevel_;
    }
    /**
     * <code>uint32 unlock_level = 3;</code>
     * @param value The unlockLevel to set.
     * @return This builder for chaining.
     */
    public Builder setUnlockLevel(int value) {

      unlockLevel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 unlock_level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnlockLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      unlockLevel_ = 0;
      onChanged();
      return this;
    }

    private int pointsPerLevel_ ;
    /**
     * <code>uint32 points_per_level = 4;</code>
     * @return The pointsPerLevel.
     */
    @java.lang.Override
    public int getPointsPerLevel() {
      return pointsPerLevel_;
    }
    /**
     * <code>uint32 points_per_level = 4;</code>
     * @param value The pointsPerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setPointsPerLevel(int value) {

      pointsPerLevel_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 points_per_level = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointsPerLevel() {
      bitField0_ = (bitField0_ & ~0x00000008);
      pointsPerLevel_ = 0;
      onChanged();
      return this;
    }

    private int basePoints_ ;
    /**
     * <code>uint32 base_points = 5;</code>
     * @return The basePoints.
     */
    @java.lang.Override
    public int getBasePoints() {
      return basePoints_;
    }
    /**
     * <code>uint32 base_points = 5;</code>
     * @param value The basePoints to set.
     * @return This builder for chaining.
     */
    public Builder setBasePoints(int value) {

      basePoints_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 base_points = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBasePoints() {
      bitField0_ = (bitField0_ & ~0x00000010);
      basePoints_ = 0;
      onChanged();
      return this;
    }

    private int dimensionCap_ ;
    /**
     * <code>uint32 dimension_cap = 6;</code>
     * @return The dimensionCap.
     */
    @java.lang.Override
    public int getDimensionCap() {
      return dimensionCap_;
    }
    /**
     * <code>uint32 dimension_cap = 6;</code>
     * @param value The dimensionCap to set.
     * @return This builder for chaining.
     */
    public Builder setDimensionCap(int value) {

      dimensionCap_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 dimension_cap = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDimensionCap() {
      bitField0_ = (bitField0_ & ~0x00000020);
      dimensionCap_ = 0;
      onChanged();
      return this;
    }

    private long resetCostGold_ ;
    /**
     * <code>uint64 reset_cost_gold = 7;</code>
     * @return The resetCostGold.
     */
    @java.lang.Override
    public long getResetCostGold() {
      return resetCostGold_;
    }
    /**
     * <code>uint64 reset_cost_gold = 7;</code>
     * @param value The resetCostGold to set.
     * @return This builder for chaining.
     */
    public Builder setResetCostGold(long value) {

      resetCostGold_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 reset_cost_gold = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResetCostGold() {
      bitField0_ = (bitField0_ & ~0x00000040);
      resetCostGold_ = 0L;
      onChanged();
      return this;
    }

    private int resetFreeBelowLevel_ ;
    /**
     * <code>uint32 reset_free_below_level = 8;</code>
     * @return The resetFreeBelowLevel.
     */
    @java.lang.Override
    public int getResetFreeBelowLevel() {
      return resetFreeBelowLevel_;
    }
    /**
     * <code>uint32 reset_free_below_level = 8;</code>
     * @param value The resetFreeBelowLevel to set.
     * @return This builder for chaining.
     */
    public Builder setResetFreeBelowLevel(int value) {

      resetFreeBelowLevel_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 reset_free_below_level = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearResetFreeBelowLevel() {
      bitField0_ = (bitField0_ & ~0x00000080);
      resetFreeBelowLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 9;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 9;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 9;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 9;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AttributePoolTable)
  }

  // @@protoc_insertion_point(class_scope:AttributePoolTable)
  private static final com.game.table.AttributePoolTable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.table.AttributePoolTable();
  }

  public static com.game.table.AttributePoolTable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttributePoolTable>
      PARSER = new com.google.protobuf.AbstractParser<AttributePoolTable>() {
    @java.lang.Override
    public AttributePoolTable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AttributePoolTable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttributePoolTable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.table.AttributePoolTable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

