// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: attributedimension_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class AttributeDimensionTableOuterClass extends com.google.protobuf.GeneratedFile {
  private AttributeDimensionTableOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AttributeDimensionTableOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttributeDimensionTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AttributeDimensionTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttributeDimensionTableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AttributeDimensionTableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036attributedimension_table.proto\"\355\001\n\027Att" +
      "ributeDimensionTable\022\n\n\002id\030\001 \001(\r\022\017\n\007pool" +
      "_id\030\002 \001(\r\022\014\n\004name\030\003 \001(\t\022\014\n\004desc\030\004 \001(\t\022\014\n" +
      "\004sort\030\005 \001(\r\022\026\n\016base_per_level\030\006 \001(\r\022\022\n\nm" +
      "ax_health\030\007 \001(\001\022\020\n\010max_mana\030\010 \001(\001\022\027\n\017phy" +
      "sical_attack\030\t \001(\001\022\024\n\014magic_attack\030\n \001(\001" +
      "\022\r\n\005speed\030\013 \001(\001\022\017\n\007defense\030\014 \001(\001\"E\n\033Attr" +
      "ibuteDimensionTableData\022&\n\004data\030\001 \003(\0132\030." +
      "AttributeDimensionTableBI\n\016com.game.tabl" +
      "eB!AttributeDimensionTableOuterClassP\001Z\022" +
      "generated/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AttributeDimensionTable_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_AttributeDimensionTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AttributeDimensionTable_descriptor,
        new java.lang.String[] { "Id", "PoolId", "Name", "Desc", "Sort", "BasePerLevel", "MaxHealth", "MaxMana", "PhysicalAttack", "MagicAttack", "Speed", "Defense", });
    internal_static_AttributeDimensionTableData_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_AttributeDimensionTableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AttributeDimensionTableData_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
