// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: attribute_error_tip.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class AttributeErrorTip extends com.google.protobuf.GeneratedFile {
  private AttributeErrorTip() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AttributeErrorTip");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code attribute_error}
   */
  public enum attribute_error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kAttribute_errorOK = 0;</code>
     */
    kAttribute_errorOK(0),
    /**
     * <code>kAttributePoolNotFound = 25000;</code>
     */
    kAttributePoolNotFound(25000),
    /**
     * <code>kAttributePoolLocked = 25001;</code>
     */
    kAttributePoolLocked(25001),
    /**
     * <code>kAttributeDimensionNotFound = 25002;</code>
     */
    kAttributeDimensionNotFound(25002),
    /**
     * <code>kAttributePointsNotEnough = 25003;</code>
     */
    kAttributePointsNotEnough(25003),
    /**
     * <code>kAttributePointsCannotDecrease = 25004;</code>
     */
    kAttributePointsCannotDecrease(25004),
    /**
     * <code>kAttributeDimensionCapExceeded = 25005;</code>
     */
    kAttributeDimensionCapExceeded(25005),
    /**
     * <code>kAttributeSchemeNotFound = 25006;</code>
     */
    kAttributeSchemeNotFound(25006),
    /**
     * <code>kAttributeSchemeLimitReached = 25007;</code>
     */
    kAttributeSchemeLimitReached(25007),
    /**
     * <code>kAttributeSchemeSwitchCooldown = 25008;</code>
     */
    kAttributeSchemeSwitchCooldown(25008),
    /**
     * <code>kAttributeSchemeNameInvalid = 25009;</code>
     */
    kAttributeSchemeNameInvalid(25009),
    /**
     * <code>kAttributeSchemeAlreadyActive = 25010;</code>
     */
    kAttributeSchemeAlreadyActive(25010),
    /**
     * <code>kAttributeInBattle = 25011;</code>
     */
    kAttributeInBattle(25011),
    /**
     * <code>kAttributeGoldNotEnough = 25012;</code>
     */
    kAttributeGoldNotEnough(25012),
    /**
     * <code>kAttributeNoAutoPlan = 25013;</code>
     */
    kAttributeNoAutoPlan(25013),
    /**
     * <code>kAttributeNothingToChange = 25014;</code>
     */
    kAttributeNothingToChange(25014),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "attribute_error");
    }
    /**
     * <code>kAttribute_errorOK = 0;</code>
     */
    public static final int kAttribute_errorOK_VALUE = 0;
    /**
     * <code>kAttributePoolNotFound = 25000;</code>
     */
    public static final int kAttributePoolNotFound_VALUE = 25000;
    /**
     * <code>kAttributePoolLocked = 25001;</code>
     */
    public static final int kAttributePoolLocked_VALUE = 25001;
    /**
     * <code>kAttributeDimensionNotFound = 25002;</code>
     */
    public static final int kAttributeDimensionNotFound_VALUE = 25002;
    /**
     * <code>kAttributePointsNotEnough = 25003;</code>
     */
    public static final int kAttributePointsNotEnough_VALUE = 25003;
    /**
     * <code>kAttributePointsCannotDecrease = 25004;</code>
     */
    public static final int kAttributePointsCannotDecrease_VALUE = 25004;
    /**
     * <code>kAttributeDimensionCapExceeded = 25005;</code>
     */
    public static final int kAttributeDimensionCapExceeded_VALUE = 25005;
    /**
     * <code>kAttributeSchemeNotFound = 25006;</code>
     */
    public static final int kAttributeSchemeNotFound_VALUE = 25006;
    /**
     * <code>kAttributeSchemeLimitReached = 25007;</code>
     */
    public static final int kAttributeSchemeLimitReached_VALUE = 25007;
    /**
     * <code>kAttributeSchemeSwitchCooldown = 25008;</code>
     */
    public static final int kAttributeSchemeSwitchCooldown_VALUE = 25008;
    /**
     * <code>kAttributeSchemeNameInvalid = 25009;</code>
     */
    public static final int kAttributeSchemeNameInvalid_VALUE = 25009;
    /**
     * <code>kAttributeSchemeAlreadyActive = 25010;</code>
     */
    public static final int kAttributeSchemeAlreadyActive_VALUE = 25010;
    /**
     * <code>kAttributeInBattle = 25011;</code>
     */
    public static final int kAttributeInBattle_VALUE = 25011;
    /**
     * <code>kAttributeGoldNotEnough = 25012;</code>
     */
    public static final int kAttributeGoldNotEnough_VALUE = 25012;
    /**
     * <code>kAttributeNoAutoPlan = 25013;</code>
     */
    public static final int kAttributeNoAutoPlan_VALUE = 25013;
    /**
     * <code>kAttributeNothingToChange = 25014;</code>
     */
    public static final int kAttributeNothingToChange_VALUE = 25014;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static attribute_error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static attribute_error forNumber(int value) {
      switch (value) {
        case 0: return kAttribute_errorOK;
        case 25000: return kAttributePoolNotFound;
        case 25001: return kAttributePoolLocked;
        case 25002: return kAttributeDimensionNotFound;
        case 25003: return kAttributePointsNotEnough;
        case 25004: return kAttributePointsCannotDecrease;
        case 25005: return kAttributeDimensionCapExceeded;
        case 25006: return kAttributeSchemeNotFound;
        case 25007: return kAttributeSchemeLimitReached;
        case 25008: return kAttributeSchemeSwitchCooldown;
        case 25009: return kAttributeSchemeNameInvalid;
        case 25010: return kAttributeSchemeAlreadyActive;
        case 25011: return kAttributeInBattle;
        case 25012: return kAttributeGoldNotEnough;
        case 25013: return kAttributeNoAutoPlan;
        case 25014: return kAttributeNothingToChange;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<attribute_error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        attribute_error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<attribute_error>() {
            public attribute_error findValueByNumber(int number) {
              return attribute_error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.table.AttributeErrorTip.getDescriptor().getEnumType(0);
    }

    private static final attribute_error[] VALUES = values();

    public static attribute_error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private attribute_error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:attribute_error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031attribute_error_tip.proto*\233\004\n\017attribut" +
      "e_error\022\026\n\022kAttribute_errorOK\020\000\022\034\n\026kAttr" +
      "ibutePoolNotFound\020\250\303\001\022\032\n\024kAttributePoolL" +
      "ocked\020\251\303\001\022!\n\033kAttributeDimensionNotFound" +
      "\020\252\303\001\022\037\n\031kAttributePointsNotEnough\020\253\303\001\022$\n" +
      "\036kAttributePointsCannotDecrease\020\254\303\001\022$\n\036k" +
      "AttributeDimensionCapExceeded\020\255\303\001\022\036\n\030kAt" +
      "tributeSchemeNotFound\020\256\303\001\022\"\n\034kAttributeS" +
      "chemeLimitReached\020\257\303\001\022$\n\036kAttributeSchem" +
      "eSwitchCooldown\020\260\303\001\022!\n\033kAttributeSchemeN" +
      "ameInvalid\020\261\303\001\022#\n\035kAttributeSchemeAlread" +
      "yActive\020\262\303\001\022\030\n\022kAttributeInBattle\020\263\303\001\022\035\n" +
      "\027kAttributeGoldNotEnough\020\264\303\001\022\032\n\024kAttribu" +
      "teNoAutoPlan\020\265\303\001\022\037\n\031kAttributeNothingToC" +
      "hange\020\266\303\001B$\n\016com.game.tableZ\022generated/p" +
      "b/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
