// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: attributedimension_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

/**
 * Protobuf type {@code AttributeDimensionTable}
 */
@com.google.protobuf.Generated
public final class AttributeDimensionTable extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:AttributeDimensionTable)
    AttributeDimensionTableOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AttributeDimensionTable");
  }
  // Use AttributeDimensionTable.newBuilder() to construct.
  private AttributeDimensionTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AttributeDimensionTable() {
    name_ = "";
    desc_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.table.AttributeDimensionTable.class, com.game.table.AttributeDimensionTable.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int POOL_ID_FIELD_NUMBER = 2;
  private int poolId_ = 0;
  /**
   * <code>uint32 pool_id = 2;</code>
   * @return The poolId.
   */
  @java.lang.Override
  public int getPoolId() {
    return poolId_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 4;</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 4;</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SORT_FIELD_NUMBER = 5;
  private int sort_ = 0;
  /**
   * <code>uint32 sort = 5;</code>
   * @return The sort.
   */
  @java.lang.Override
  public int getSort() {
    return sort_;
  }

  public static final int BASE_PER_LEVEL_FIELD_NUMBER = 6;
  private int basePerLevel_ = 0;
  /**
   * <code>uint32 base_per_level = 6;</code>
   * @return The basePerLevel.
   */
  @java.lang.Override
  public int getBasePerLevel() {
    return basePerLevel_;
  }

  public static final int MAX_HEALTH_FIELD_NUMBER = 7;
  private double maxHealth_ = 0D;
  /**
   * <code>double max_health = 7;</code>
   * @return The maxHealth.
   */
  @java.lang.Override
  public double getMaxHealth() {
    return maxHealth_;
  }

  public static final int MAX_MANA_FIELD_NUMBER = 8;
  private double maxMana_ = 0D;
  /**
   * <code>double max_mana = 8;</code>
   * @return The maxMana.
   */
  @java.lang.Override
  public double getMaxMana() {
    return maxMana_;
  }

  public static final int PHYSICAL_ATTACK_FIELD_NUMBER = 9;
  private double physicalAttack_ = 0D;
  /**
   * <code>double physical_attack = 9;</code>
   * @return The physicalAttack.
   */
  @java.lang.Override
  public double getPhysicalAttack() {
    return physicalAttack_;
  }

  public static final int MAGIC_ATTACK_FIELD_NUMBER = 10;
  private double magicAttack_ = 0D;
  /**
   * <code>double magic_attack = 10;</code>
   * @return The magicAttack.
   */
  @java.lang.Override
  public double getMagicAttack() {
    return magicAttack_;
  }

  public static final int SPEED_FIELD_NUMBER = 11;
  private double speed_ = 0D;
  /**
   * <code>double speed = 11;</code>
   * @return The speed.
   */
  @java.lang.Override
  public double getSpeed() {
    return speed_;
  }

  public static final int DEFENSE_FIELD_NUMBER = 12;
  private double defense_ = 0D;
  /**
   * <code>double defense = 12;</code>
   * @return The defense.
   */
  @java.lang.Override
  public double getDefense() {
    return defense_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (poolId_ != 0) {
      output.writeUInt32(2, poolId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(desc_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, desc_);
    }
    if (sort_ != 0) {
      output.writeUInt32(5, sort_);
    }
    if (basePerLevel_ != 0) {
      output.writeUInt32(6, basePerLevel_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxHealth_) != 0) {
      output.writeDouble(7, maxHealth_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxMana_) != 0) {
      output.writeDouble(8, maxMana_);
    }
    if (java.lang.Double.doubleToRawLongBits(physicalAttack_) != 0) {
      output.writeDouble(9, physicalAttack_);
    }
    if (java.lang.Double.doubleToRawLongBits(magicAttack_) != 0) {
      output.writeDouble(10, magicAttack_);
    }
    if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
      output.writeDouble(11, speed_);
    }
    if (java.lang.Double.doubleToRawLongBits(defense_) != 0) {
      output.writeDouble(12, defense_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (poolId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, poolId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(desc_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, desc_);
    }
    if (sort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, sort_);
    }
    if (basePerLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, basePerLevel_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxHealth_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, maxHealth_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxMana_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, maxMana_);
    }
    if (java.lang.Double.doubleToRawLongBits(physicalAttack_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, physicalAttack_);
    }
    if (java.lang.Double.doubleToRawLongBits(magicAttack_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, magicAttack_);
    }
    if (java.lang.Double.doubleToRawLongBits(speed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, speed_);
    }
    if (java.lang.Double.doubleToRawLongBits(defense_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, defense_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.table.AttributeDimensionTable)) {
      return super.equals(obj);
    }
    com.game.table.AttributeDimensionTable other = (com.game.table.AttributeDimensionTable) obj;

    if (getId()
        != other.getId()) return false;
    if (getPoolId()
        != other.getPoolId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDesc()
        .equals(other.getDesc())) return false;
    if (getSort()
        != other.getSort()) return false;
    if (getBasePerLevel()
        != other.getBasePerLevel()) return false;
    if (java.lang.Double.doubleToLongBits(getMaxHealth())
        != java.lang.Double.doubleToLongBits(
            other.getMaxHealth())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxMana())
        != java.lang.Double.doubleToLongBits(
            other.getMaxMana())) return false;
    if (java.lang.Double.doubleToLongBits(getPhysicalAttack())
        != java.lang.Double.doubleToLongBits(
            other.getPhysicalAttack())) return false;
    if (java.lang.Double.doubleToLongBits(getMagicAttack())
        != java.lang.Double.doubleToLongBits(
            other.getMagicAttack())) return false;
    if (java.lang.Double.doubleToLongBits(getSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getSpeed())) return false;
    if (java.lang.Double.doubleToLongBits(getDefense())
        != java.lang.Double.doubleToLongBits(
            other.getDefense())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + POOL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPoolId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    hash = (37 * hash) + SORT_FIELD_NUMBER;
    hash = (53 * hash) + getSort();
    hash = (37 * hash) + BASE_PER_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getBasePerLevel();
    hash = (37 * hash) + MAX_HEALTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxHealth()));
    hash = (37 * hash) + MAX_MANA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxMana()));
    hash = (37 * hash) + PHYSICAL_ATTACK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPhysicalAttack()));
    hash = (37 * hash) + MAGIC_ATTACK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMagicAttack()));
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSpeed()));
    hash = (37 * hash) + DEFENSE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDefense()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.table.AttributeDimensionTable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.table.AttributeDimensionTable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.table.AttributeDimensionTable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.AttributeDimensionTable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.table.AttributeDimensionTable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AttributeDimensionTable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AttributeDimensionTable)
      com.game.table.AttributeDimensionTableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.table.AttributeDimensionTable.class, com.game.table.AttributeDimensionTable.Builder.class);
    }

    // Construct using com.game.table.AttributeDimensionTable.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      poolId_ = 0;
      name_ = "";
      desc_ = "";
      sort_ = 0;
      basePerLevel_ = 0;
      maxHealth_ = 0D;
      maxMana_ = 0D;
      physicalAttack_ = 0D;
      magicAttack_ = 0D;
      speed_ = 0D;
      defense_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.table.AttributeDimensionTableOuterClass.internal_static_AttributeDimensionTable_descriptor;
    }

    @java.lang.Override
    public com.game.table.AttributeDimensionTable getDefaultInstanceForType() {
      return com.game.table.AttributeDimensionTable.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.table.AttributeDimensionTable build() {
      com.game.table.AttributeDimensionTable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.table.AttributeDimensionTable buildPartial() {
      com.game.table.AttributeDimensionTable result = new com.game.table.AttributeDimensionTable(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.table.AttributeDimensionTable result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.poolId_ = poolId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.desc_ = desc_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sort_ = sort_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.basePerLevel_ = basePerLevel_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.maxHealth_ = maxHealth_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.maxMana_ = maxMana_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.physicalAttack_ = physicalAttack_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.magicAttack_ = magicAttack_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.speed_ = speed_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.defense_ = defense_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.table.AttributeDimensionTable) {
        return mergeFrom((com.game.table.AttributeDimensionTable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.table.AttributeDimensionTable other) {
      if (other == com.game.table.AttributeDimensionTable.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getPoolId() != 0) {
        setPoolId(other.getPoolId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getSort() != 0) {
        setSort(other.getSort());
      }
      if (other.getBasePerLevel() != 0) {
        setBasePerLevel(other.getBasePerLevel());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getMaxHealth()) != 0) {
        setMaxHealth(other.getMaxHealth());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getMaxMana()) != 0) {
        setMaxMana(other.getMaxMana());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getPhysicalAttack()) != 0) {
        setPhysicalAttack(other.getPhysicalAttack());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getMagicAttack()) != 0) {
        setMagicAttack(other.getMagicAttack());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getSpeed()) != 0) {
        setSpeed(other.getSpeed());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getDefense()) != 0) {
        setDefense(other.getDefense());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              poolId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              sort_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              basePerLevel_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 57: {
              maxHealth_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 65: {
              maxMana_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              physicalAttack_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 81: {
              magicAttack_ = input.readDouble();
              bitField0_ |= 0x00000200;
              break;
            } // case 81
            case 89: {
              speed_ = input.readDouble();
              bitField0_ |= 0x00000400;
              break;
            } // case 89
            case 97: {
              defense_ = input.readDouble();
              bitField0_ |= 0x00000800;
              break;
            } // case 97
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int poolId_ ;
    /**
     * <code>uint32 pool_id = 2;</code>
     * @return The poolId.
     */
    @java.lang.Override
    public int getPoolId() {
      return poolId_;
    }
    /**
     * <code>uint32 pool_id = 2;</code>
     * @param value The poolId to set.
     * @return This builder for chaining.
     */
    public Builder setPoolId(int value) {

      poolId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 pool_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPoolId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      poolId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 4;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 4;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 4;</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 4;</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int sort_ ;
    /**
     * <code>uint32 sort = 5;</code>
     * @return The sort.
     */
    @java.lang.Override
    public int getSort() {
      return sort_;
    }
    /**
     * <code>uint32 sort = 5;</code>
     * @param value The sort to set.
     * @return This builder for chaining.
     */
    public Builder setSort(int value) {

      sort_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 sort = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSort() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sort_ = 0;
      onChanged();
      return this;
    }

    private int basePerLevel_ ;
    /**
     * <code>uint32 base_per_level = 6;</code>
     * @return The basePerLevel.
     */
    @java.lang.Override
    public int getBasePerLevel() {
      return basePerLevel_;
    }
    /**
     * <code>uint32 base_per_level = 6;</code>
     * @param value The basePerLevel to set.
     * @return This builder for chaining.
     */
    public Builder setBasePerLevel(int value) {

      basePerLevel_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 base_per_level = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBasePerLevel() {
      bitField0_ = (bitField0_ & ~0x00000020);
      basePerLevel_ = 0;
      onChanged();
      return this;
    }

    private double maxHealth_ ;
    /**
     * <code>double max_health = 7;</code>
     * @return The maxHealth.
     */
    @java.lang.Override
    public double getMaxHealth() {
      return maxHealth_;
    }
    /**
     * <code>double max_health = 7;</code>
     * @param value The maxHealth to set.
     * @return This builder for chaining.
     */
    public Builder setMaxHealth(double value) {

      maxHealth_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double max_health = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxHealth() {
      bitField0_ = (bitField0_ & ~0x00000040);
      maxHealth_ = 0D;
      onChanged();
      return this;
    }

    private double maxMana_ ;
    /**
     * <code>double max_mana = 8;</code>
     * @return The maxMana.
     */
    @java.lang.Override
    public double getMaxMana() {
      return maxMana_;
    }
    /**
     * <code>double max_mana = 8;</code>
     * @param value The maxMana to set.
     * @return This builder for chaining.
     */
    public Builder setMaxMana(double value) {

      maxMana_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>double max_mana = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxMana() {
      bitField0_ = (bitField0_ & ~0x00000080);
      maxMana_ = 0D;
      onChanged();
      return this;
    }

    private double physicalAttack_ ;
    /**
     * <code>double physical_attack = 9;</code>
     * @return The physicalAttack.
     */
    @java.lang.Override
    public double getPhysicalAttack() {
      return physicalAttack_;
    }
    /**
     * <code>double physical_attack = 9;</code>
     * @param value The physicalAttack to set.
     * @return This builder for chaining.
     */
    public Builder setPhysicalAttack(double value) {

      physicalAttack_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>double physical_attack = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhysicalAttack() {
      bitField0_ = (bitField0_ & ~0x00000100);
      physicalAttack_ = 0D;
      onChanged();
      return this;
    }

    private double magicAttack_ ;
    /**
     * <code>double magic_attack = 10;</code>
     * @return The magicAttack.
     */
    @java.lang.Override
    public double getMagicAttack() {
      return magicAttack_;
    }
    /**
     * <code>double magic_attack = 10;</code>
     * @param value The magicAttack to set.
     * @return This builder for chaining.
     */
    public Builder setMagicAttack(double value) {

      magicAttack_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>double magic_attack = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMagicAttack() {
      bitField0_ = (bitField0_ & ~0x00000200);
      magicAttack_ = 0D;
      onChanged();
      return this;
    }

    private double speed_ ;
    /**
     * <code>double speed = 11;</code>
     * @return The speed.
     */
    @java.lang.Override
    public double getSpeed() {
      return speed_;
    }
    /**
     * <code>double speed = 11;</code>
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    public Builder setSpeed(double value) {

      speed_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>double speed = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeed() {
      bitField0_ = (bitField0_ & ~0x00000400);
      speed_ = 0D;
      onChanged();
      return this;
    }

    private double defense_ ;
    /**
     * <code>double defense = 12;</code>
     * @return The defense.
     */
    @java.lang.Override
    public double getDefense() {
      return defense_;
    }
    /**
     * <code>double defense = 12;</code>
     * @param value The defense to set.
     * @return This builder for chaining.
     */
    public Builder setDefense(double value) {

      defense_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>double defense = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefense() {
      bitField0_ = (bitField0_ & ~0x00000800);
      defense_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AttributeDimensionTable)
  }

  // @@protoc_insertion_point(class_scope:AttributeDimensionTable)
  private static final com.game.table.AttributeDimensionTable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.table.AttributeDimensionTable();
  }

  public static com.game.table.AttributeDimensionTable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttributeDimensionTable>
      PARSER = new com.google.protobuf.AbstractParser<AttributeDimensionTable>() {
    @java.lang.Override
    public AttributeDimensionTable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AttributeDimensionTable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AttributeDimensionTable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.table.AttributeDimensionTable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

