// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: attributeautoplan_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public interface AttributeAutoPlanTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AttributeAutoPlanTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>uint32 class_id = 2;</code>
   * @return The classId.
   */
  int getClassId();

  /**
   * <code>uint32 pool_id = 3;</code>
   * @return The poolId.
   */
  int getPoolId();

  /**
   * <code>repeated uint32 dimension = 4;</code>
   * @return A list containing the dimension.
   */
  java.util.List<java.lang.Integer> getDimensionList();
  /**
   * <code>repeated uint32 dimension = 4;</code>
   * @return The count of dimension.
   */
  int getDimensionCount();
  /**
   * <code>repeated uint32 dimension = 4;</code>
   * @param index The index of the element to return.
   * @return The dimension at the given index.
   */
  int getDimension(int index);

  /**
   * <code>repeated uint32 weight = 5;</code>
   * @return A list containing the weight.
   */
  java.util.List<java.lang.Integer> getWeightList();
  /**
   * <code>repeated uint32 weight = 5;</code>
   * @return The count of weight.
   */
  int getWeightCount();
  /**
   * <code>repeated uint32 weight = 5;</code>
   * @param index The index of the element to return.
   * @return The weight at the given index.
   */
  int getWeight(int index);

  /**
   * <code>string desc = 6;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 6;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
