// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bag_error_tip.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class BagErrorTip extends com.google.protobuf.GeneratedFile {
  private BagErrorTip() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BagErrorTip");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code bag_error}
   */
  public enum bag_error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kBag_errorOK = 0;</code>
     */
    kBag_errorOK(0),
    /**
     * <code>kBagDeleteItemFindGuid = 6000;</code>
     */
    kBagDeleteItemFindGuid(6000),
    /**
     * <code>kBagDeleteItemAlreadyHasGuid = 6001;</code>
     */
    kBagDeleteItemAlreadyHasGuid(6001),
    /**
     * <code>kBagAddItemHasNotBaseComponent = 6002;</code>
     */
    kBagAddItemHasNotBaseComponent(6002),
    /**
     * <code>kBagAddItemInvalidGuid = 6003;</code>
     */
    kBagAddItemInvalidGuid(6003),
    /**
     * <code>kBagAddItemInvalidParam = 6004;</code>
     */
    kBagAddItemInvalidParam(6004),
    /**
     * <code>kBagAddItemBagFull = 6005;</code>
     */
    kBagAddItemBagFull(6005),
    /**
     * <code>kBagItemNotStacked = 6006;</code>
     */
    kBagItemNotStacked(6006),
    /**
     * <code>kBagInsufficientItems = 6007;</code>
     */
    kBagInsufficientItems(6007),
    /**
     * <code>kBagDelItemPos = 6008;</code>
     */
    kBagDelItemPos(6008),
    /**
     * <code>kBagDelItemConfig = 6009;</code>
     */
    kBagDelItemConfig(6009),
    /**
     * <code>kBagDelItemGuid = 6010;</code>
     */
    kBagDelItemGuid(6010),
    /**
     * <code>kBagDelItemFindItem = 6011;</code>
     */
    kBagDelItemFindItem(6011),
    /**
     * <code>kBagDelItemSize = 6012;</code>
     */
    kBagDelItemSize(6012),
    /**
     * <code>kBagItemDeletionSizeMismatch = 6013;</code>
     */
    kBagItemDeletionSizeMismatch(6013),
    /**
     * <code>kBagInsufficientBagSpace = 6014;</code>
     */
    kBagInsufficientBagSpace(6014),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "bag_error");
    }
    /**
     * <code>kBag_errorOK = 0;</code>
     */
    public static final int kBag_errorOK_VALUE = 0;
    /**
     * <code>kBagDeleteItemFindGuid = 6000;</code>
     */
    public static final int kBagDeleteItemFindGuid_VALUE = 6000;
    /**
     * <code>kBagDeleteItemAlreadyHasGuid = 6001;</code>
     */
    public static final int kBagDeleteItemAlreadyHasGuid_VALUE = 6001;
    /**
     * <code>kBagAddItemHasNotBaseComponent = 6002;</code>
     */
    public static final int kBagAddItemHasNotBaseComponent_VALUE = 6002;
    /**
     * <code>kBagAddItemInvalidGuid = 6003;</code>
     */
    public static final int kBagAddItemInvalidGuid_VALUE = 6003;
    /**
     * <code>kBagAddItemInvalidParam = 6004;</code>
     */
    public static final int kBagAddItemInvalidParam_VALUE = 6004;
    /**
     * <code>kBagAddItemBagFull = 6005;</code>
     */
    public static final int kBagAddItemBagFull_VALUE = 6005;
    /**
     * <code>kBagItemNotStacked = 6006;</code>
     */
    public static final int kBagItemNotStacked_VALUE = 6006;
    /**
     * <code>kBagInsufficientItems = 6007;</code>
     */
    public static final int kBagInsufficientItems_VALUE = 6007;
    /**
     * <code>kBagDelItemPos = 6008;</code>
     */
    public static final int kBagDelItemPos_VALUE = 6008;
    /**
     * <code>kBagDelItemConfig = 6009;</code>
     */
    public static final int kBagDelItemConfig_VALUE = 6009;
    /**
     * <code>kBagDelItemGuid = 6010;</code>
     */
    public static final int kBagDelItemGuid_VALUE = 6010;
    /**
     * <code>kBagDelItemFindItem = 6011;</code>
     */
    public static final int kBagDelItemFindItem_VALUE = 6011;
    /**
     * <code>kBagDelItemSize = 6012;</code>
     */
    public static final int kBagDelItemSize_VALUE = 6012;
    /**
     * <code>kBagItemDeletionSizeMismatch = 6013;</code>
     */
    public static final int kBagItemDeletionSizeMismatch_VALUE = 6013;
    /**
     * <code>kBagInsufficientBagSpace = 6014;</code>
     */
    public static final int kBagInsufficientBagSpace_VALUE = 6014;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static bag_error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static bag_error forNumber(int value) {
      switch (value) {
        case 0: return kBag_errorOK;
        case 6000: return kBagDeleteItemFindGuid;
        case 6001: return kBagDeleteItemAlreadyHasGuid;
        case 6002: return kBagAddItemHasNotBaseComponent;
        case 6003: return kBagAddItemInvalidGuid;
        case 6004: return kBagAddItemInvalidParam;
        case 6005: return kBagAddItemBagFull;
        case 6006: return kBagItemNotStacked;
        case 6007: return kBagInsufficientItems;
        case 6008: return kBagDelItemPos;
        case 6009: return kBagDelItemConfig;
        case 6010: return kBagDelItemGuid;
        case 6011: return kBagDelItemFindItem;
        case 6012: return kBagDelItemSize;
        case 6013: return kBagItemDeletionSizeMismatch;
        case 6014: return kBagInsufficientBagSpace;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<bag_error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        bag_error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<bag_error>() {
            public bag_error findValueByNumber(int number) {
              return bag_error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.table.BagErrorTip.getDescriptor().getEnumType(0);
    }

    private static final bag_error[] VALUES = values();

    public static bag_error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private bag_error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:bag_error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bag_error_tip.proto*\300\003\n\tbag_error\022\020\n\014k" +
      "Bag_errorOK\020\000\022\033\n\026kBagDeleteItemFindGuid\020" +
      "\360.\022!\n\034kBagDeleteItemAlreadyHasGuid\020\361.\022#\n" +
      "\036kBagAddItemHasNotBaseComponent\020\362.\022\033\n\026kB" +
      "agAddItemInvalidGuid\020\363.\022\034\n\027kBagAddItemIn" +
      "validParam\020\364.\022\027\n\022kBagAddItemBagFull\020\365.\022\027" +
      "\n\022kBagItemNotStacked\020\366.\022\032\n\025kBagInsuffici" +
      "entItems\020\367.\022\023\n\016kBagDelItemPos\020\370.\022\026\n\021kBag" +
      "DelItemConfig\020\371.\022\024\n\017kBagDelItemGuid\020\372.\022\030" +
      "\n\023kBagDelItemFindItem\020\373.\022\024\n\017kBagDelItemS" +
      "ize\020\374.\022!\n\034kBagItemDeletionSizeMismatch\020\375" +
      ".\022\035\n\030kBagInsufficientBagSpace\020\376.B$\n\016com." +
      "game.tableZ\022generated/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
