// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: buff_error_tip.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class BuffErrorTip extends com.google.protobuf.GeneratedFile {
  private BuffErrorTip() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BuffErrorTip");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code buff_error}
   */
  public enum buff_error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kBuff_errorOK = 0;</code>
     */
    kBuff_errorOK(0),
    /**
     * <code>kBuffMaxBuffStack = 8000;</code>
     */
    kBuffMaxBuffStack(8000),
    /**
     * <code>kBuffTargetImmuneToBuff = 8001;</code>
     */
    kBuffTargetImmuneToBuff(8001),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "buff_error");
    }
    /**
     * <code>kBuff_errorOK = 0;</code>
     */
    public static final int kBuff_errorOK_VALUE = 0;
    /**
     * <code>kBuffMaxBuffStack = 8000;</code>
     */
    public static final int kBuffMaxBuffStack_VALUE = 8000;
    /**
     * <code>kBuffTargetImmuneToBuff = 8001;</code>
     */
    public static final int kBuffTargetImmuneToBuff_VALUE = 8001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static buff_error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static buff_error forNumber(int value) {
      switch (value) {
        case 0: return kBuff_errorOK;
        case 8000: return kBuffMaxBuffStack;
        case 8001: return kBuffTargetImmuneToBuff;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<buff_error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        buff_error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<buff_error>() {
            public buff_error findValueByNumber(int number) {
              return buff_error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.table.BuffErrorTip.getDescriptor().getEnumType(0);
    }

    private static final buff_error[] VALUES = values();

    public static buff_error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private buff_error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:buff_error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024buff_error_tip.proto*U\n\nbuff_error\022\021\n\r" +
      "kBuff_errorOK\020\000\022\026\n\021kBuffMaxBuffStack\020\300>\022" +
      "\034\n\027kBuffTargetImmuneToBuff\020\301>B$\n\016com.gam" +
      "e.tableZ\022generated/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
