// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guilddonate_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class GuildDonateTableOuterClass extends com.google.protobuf.GeneratedFile {
  private GuildDonateTableOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GuildDonateTableOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildDonateTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildDonateTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildDonateTableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildDonateTableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027guilddonate_table.proto\"\265\001\n\020GuildDonat" +
      "eTable\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\t\022\025\n\rcurr" +
      "ency_type\030\003 \001(\r\022\023\n\013cost_amount\030\004 \001(\004\022\031\n\021" +
      "contribution_gain\030\005 \001(\004\022\022\n\nfunds_gain\030\006 " +
      "\001(\004\022\023\n\013daily_limit\030\007 \001(\r\022\027\n\017min_guild_le" +
      "vel\030\010 \001(\r\"7\n\024GuildDonateTableData\022\037\n\004dat" +
      "a\030\001 \003(\0132\021.GuildDonateTableBB\n\016com.game.t" +
      "ableB\032GuildDonateTableOuterClassP\001Z\022gene" +
      "rated/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GuildDonateTable_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_GuildDonateTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildDonateTable_descriptor,
        new java.lang.String[] { "Id", "Name", "CurrencyType", "CostAmount", "ContributionGain", "FundsGain", "DailyLimit", "MinGuildLevel", });
    internal_static_GuildDonateTableData_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_GuildDonateTableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildDonateTableData_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
