// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guildlevel_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class GuildLevelTableOuterClass extends com.google.protobuf.GeneratedFile {
  private GuildLevelTableOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GuildLevelTableOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildLevelTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildLevelTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildLevelTableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildLevelTableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026guildlevel_table.proto\"d\n\017GuildLevelTa" +
      "ble\022\n\n\002id\030\001 \001(\r\022\023\n\013max_members\030\002 \001(\r\022\024\n\014" +
      "max_officers\030\003 \001(\r\022\032\n\022upgrade_cost_funds" +
      "\030\004 \001(\004\"5\n\023GuildLevelTableData\022\036\n\004data\030\001 " +
      "\003(\0132\020.GuildLevelTableBA\n\016com.game.tableB" +
      "\031GuildLevelTableOuterClassP\001Z\022generated/" +
      "pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GuildLevelTable_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_GuildLevelTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildLevelTable_descriptor,
        new java.lang.String[] { "Id", "MaxMembers", "MaxOfficers", "UpgradeCostFunds", });
    internal_static_GuildLevelTableData_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_GuildLevelTableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildLevelTableData_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
