// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guildlevel_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

/**
 * Protobuf type {@code GuildLevelTable}
 */
@com.google.protobuf.Generated
public final class GuildLevelTable extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:GuildLevelTable)
    GuildLevelTableOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GuildLevelTable");
  }
  // Use GuildLevelTable.newBuilder() to construct.
  private GuildLevelTable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GuildLevelTable() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.game.table.GuildLevelTable.class, com.game.table.GuildLevelTable.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int MAX_MEMBERS_FIELD_NUMBER = 2;
  private int maxMembers_ = 0;
  /**
   * <code>uint32 max_members = 2;</code>
   * @return The maxMembers.
   */
  @java.lang.Override
  public int getMaxMembers() {
    return maxMembers_;
  }

  public static final int MAX_OFFICERS_FIELD_NUMBER = 3;
  private int maxOfficers_ = 0;
  /**
   * <code>uint32 max_officers = 3;</code>
   * @return The maxOfficers.
   */
  @java.lang.Override
  public int getMaxOfficers() {
    return maxOfficers_;
  }

  public static final int UPGRADE_COST_FUNDS_FIELD_NUMBER = 4;
  private long upgradeCostFunds_ = 0L;
  /**
   * <code>uint64 upgrade_cost_funds = 4;</code>
   * @return The upgradeCostFunds.
   */
  @java.lang.Override
  public long getUpgradeCostFunds() {
    return upgradeCostFunds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (maxMembers_ != 0) {
      output.writeUInt32(2, maxMembers_);
    }
    if (maxOfficers_ != 0) {
      output.writeUInt32(3, maxOfficers_);
    }
    if (upgradeCostFunds_ != 0L) {
      output.writeUInt64(4, upgradeCostFunds_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (maxMembers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, maxMembers_);
    }
    if (maxOfficers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, maxOfficers_);
    }
    if (upgradeCostFunds_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, upgradeCostFunds_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.game.table.GuildLevelTable)) {
      return super.equals(obj);
    }
    com.game.table.GuildLevelTable other = (com.game.table.GuildLevelTable) obj;

    if (getId()
        != other.getId()) return false;
    if (getMaxMembers()
        != other.getMaxMembers()) return false;
    if (getMaxOfficers()
        != other.getMaxOfficers()) return false;
    if (getUpgradeCostFunds()
        != other.getUpgradeCostFunds()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + MAX_MEMBERS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxMembers();
    hash = (37 * hash) + MAX_OFFICERS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxOfficers();
    hash = (37 * hash) + UPGRADE_COST_FUNDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpgradeCostFunds());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.game.table.GuildLevelTable parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.GuildLevelTable parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.game.table.GuildLevelTable parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.game.table.GuildLevelTable parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.game.table.GuildLevelTable parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.game.table.GuildLevelTable parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.game.table.GuildLevelTable prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GuildLevelTable}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GuildLevelTable)
      com.game.table.GuildLevelTableOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.table.GuildLevelTable.class, com.game.table.GuildLevelTable.Builder.class);
    }

    // Construct using com.game.table.GuildLevelTable.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      maxMembers_ = 0;
      maxOfficers_ = 0;
      upgradeCostFunds_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.game.table.GuildLevelTableOuterClass.internal_static_GuildLevelTable_descriptor;
    }

    @java.lang.Override
    public com.game.table.GuildLevelTable getDefaultInstanceForType() {
      return com.game.table.GuildLevelTable.getDefaultInstance();
    }

    @java.lang.Override
    public com.game.table.GuildLevelTable build() {
      com.game.table.GuildLevelTable result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.game.table.GuildLevelTable buildPartial() {
      com.game.table.GuildLevelTable result = new com.game.table.GuildLevelTable(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.game.table.GuildLevelTable result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxMembers_ = maxMembers_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.maxOfficers_ = maxOfficers_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.upgradeCostFunds_ = upgradeCostFunds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.game.table.GuildLevelTable) {
        return mergeFrom((com.game.table.GuildLevelTable)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.game.table.GuildLevelTable other) {
      if (other == com.game.table.GuildLevelTable.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getMaxMembers() != 0) {
        setMaxMembers(other.getMaxMembers());
      }
      if (other.getMaxOfficers() != 0) {
        setMaxOfficers(other.getMaxOfficers());
      }
      if (other.getUpgradeCostFunds() != 0L) {
        setUpgradeCostFunds(other.getUpgradeCostFunds());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              maxMembers_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              maxOfficers_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              upgradeCostFunds_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int maxMembers_ ;
    /**
     * <code>uint32 max_members = 2;</code>
     * @return The maxMembers.
     */
    @java.lang.Override
    public int getMaxMembers() {
      return maxMembers_;
    }
    /**
     * <code>uint32 max_members = 2;</code>
     * @param value The maxMembers to set.
     * @return This builder for chaining.
     */
    public Builder setMaxMembers(int value) {

      maxMembers_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 max_members = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxMembers() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxMembers_ = 0;
      onChanged();
      return this;
    }

    private int maxOfficers_ ;
    /**
     * <code>uint32 max_officers = 3;</code>
     * @return The maxOfficers.
     */
    @java.lang.Override
    public int getMaxOfficers() {
      return maxOfficers_;
    }
    /**
     * <code>uint32 max_officers = 3;</code>
     * @param value The maxOfficers to set.
     * @return This builder for chaining.
     */
    public Builder setMaxOfficers(int value) {

      maxOfficers_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 max_officers = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxOfficers() {
      bitField0_ = (bitField0_ & ~0x00000004);
      maxOfficers_ = 0;
      onChanged();
      return this;
    }

    private long upgradeCostFunds_ ;
    /**
     * <code>uint64 upgrade_cost_funds = 4;</code>
     * @return The upgradeCostFunds.
     */
    @java.lang.Override
    public long getUpgradeCostFunds() {
      return upgradeCostFunds_;
    }
    /**
     * <code>uint64 upgrade_cost_funds = 4;</code>
     * @param value The upgradeCostFunds to set.
     * @return This builder for chaining.
     */
    public Builder setUpgradeCostFunds(long value) {

      upgradeCostFunds_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 upgrade_cost_funds = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpgradeCostFunds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      upgradeCostFunds_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:GuildLevelTable)
  }

  // @@protoc_insertion_point(class_scope:GuildLevelTable)
  private static final com.game.table.GuildLevelTable DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.game.table.GuildLevelTable();
  }

  public static com.game.table.GuildLevelTable getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GuildLevelTable>
      PARSER = new com.google.protobuf.AbstractParser<GuildLevelTable>() {
    @java.lang.Override
    public GuildLevelTable parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GuildLevelTable> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GuildLevelTable> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.game.table.GuildLevelTable getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

