// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guilddonate_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public interface GuildDonateTableDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuildDonateTableData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GuildDonateTable data = 1;</code>
   */
  java.util.List<com.game.table.GuildDonateTable> 
      getDataList();
  /**
   * <code>repeated .GuildDonateTable data = 1;</code>
   */
  com.game.table.GuildDonateTable getData(int index);
  /**
   * <code>repeated .GuildDonateTable data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .GuildDonateTable data = 1;</code>
   */
  java.util.List<? extends com.game.table.GuildDonateTableOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .GuildDonateTable data = 1;</code>
   */
  com.game.table.GuildDonateTableOrBuilder getDataOrBuilder(
      int index);
}
