// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: guildrule_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class GuildRuleTableOuterClass extends com.google.protobuf.GeneratedFile {
  private GuildRuleTableOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GuildRuleTableOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildRuleTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildRuleTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuildRuleTableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GuildRuleTableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025guildrule_table.proto\"\376\001\n\016GuildRuleTab" +
      "le\022\n\n\002id\030\001 \001(\r\022 \n\030application_expire_hou" +
      "rs\030\002 \001(\r\022+\n#max_pending_applications_per" +
      "_player\030\003 \001(\r\022*\n\"max_pending_application" +
      "s_per_guild\030\004 \001(\r\022!\n\031asset_op_deadline_s" +
      "econds\030\005 \001(\r\022\036\n\026asset_op_retry_base_ms\030\006" +
      " \001(\r\022\"\n\032reunion_min_online_members\030\007 \001(\r" +
      "\"3\n\022GuildRuleTableData\022\035\n\004data\030\001 \003(\0132\017.G" +
      "uildRuleTableB@\n\016com.game.tableB\030GuildRu" +
      "leTableOuterClassP\001Z\022generated/pb/tableb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GuildRuleTable_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_GuildRuleTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildRuleTable_descriptor,
        new java.lang.String[] { "Id", "ApplicationExpireHours", "MaxPendingApplicationsPerPlayer", "MaxPendingApplicationsPerGuild", "AssetOpDeadlineSeconds", "AssetOpRetryBaseMs", "ReunionMinOnlineMembers", });
    internal_static_GuildRuleTableData_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_GuildRuleTableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GuildRuleTableData_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
