// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pet_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public interface PetTableDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PetTableData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PetTable data = 1;</code>
   */
  java.util.List<com.game.table.PetTable> 
      getDataList();
  /**
   * <code>repeated .PetTable data = 1;</code>
   */
  com.game.table.PetTable getData(int index);
  /**
   * <code>repeated .PetTable data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .PetTable data = 1;</code>
   */
  java.util.List<? extends com.game.table.PetTableOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .PetTable data = 1;</code>
   */
  com.game.table.PetTableOrBuilder getDataOrBuilder(
      int index);
}
