// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: rolenamerule_table.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class RoleNameRuleTableOuterClass extends com.google.protobuf.GeneratedFile {
  private RoleNameRuleTableOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "RoleNameRuleTableOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleNameRuleTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoleNameRuleTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoleNameRuleTableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RoleNameRuleTableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030rolenamerule_table.proto\"\252\001\n\021RoleNameR" +
      "uleTable\022\n\n\002id\030\001 \001(\r\022\021\n\tmin_chars\030\002 \001(\r\022" +
      "\021\n\tmax_chars\030\003 \001(\r\022\030\n\020generated_prefix\030\004" +
      " \001(\t\022\034\n\024generated_suffix_len\030\005 \001(\r\022\035\n\025ma" +
      "x_generate_attempts\030\006 \001(\r\022\014\n\004desc\030\007 \001(\t\"" +
      "9\n\025RoleNameRuleTableData\022 \n\004data\030\001 \003(\0132\022" +
      ".RoleNameRuleTableBC\n\016com.game.tableB\033Ro" +
      "leNameRuleTableOuterClassP\001Z\022generated/p" +
      "b/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RoleNameRuleTable_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_RoleNameRuleTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoleNameRuleTable_descriptor,
        new java.lang.String[] { "Id", "MinChars", "MaxChars", "GeneratedPrefix", "GeneratedSuffixLen", "MaxGenerateAttempts", "Desc", });
    internal_static_RoleNameRuleTableData_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_RoleNameRuleTableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_RoleNameRuleTableData_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
