// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: skill_error_tip.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class SkillErrorTip extends com.google.protobuf.GeneratedFile {
  private SkillErrorTip() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "SkillErrorTip");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code skill_error}
   */
  public enum skill_error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kSkill_errorOK = 0;</code>
     */
    kSkill_errorOK(0),
    /**
     * <code>kSkillUnInterruptible = 7000;</code>
     */
    kSkillUnInterruptible(7000),
    /**
     * <code>kSkillInvalidTargetId = 7001;</code>
     */
    kSkillInvalidTargetId(7001),
    /**
     * <code>kSkillInvalidTarget = 7002;</code>
     */
    kSkillInvalidTarget(7002),
    /**
     * <code>kSkillCooldownNotReady = 7003;</code>
     */
    kSkillCooldownNotReady(7003),
    /**
     * <code>kSkillCannotBeCastInCurrentState = 7004;</code>
     */
    kSkillCannotBeCastInCurrentState(7004),
    /**
     * <code>kSkillCannotBeCastSilenceRestriction = 7005;</code>
     */
    kSkillCannotBeCastSilenceRestriction(7005),
    /**
     * <code>kSkillCannotBeCastStunRestriction = 7006;</code>
     */
    kSkillCannotBeCastStunRestriction(7006),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "skill_error");
    }
    /**
     * <code>kSkill_errorOK = 0;</code>
     */
    public static final int kSkill_errorOK_VALUE = 0;
    /**
     * <code>kSkillUnInterruptible = 7000;</code>
     */
    public static final int kSkillUnInterruptible_VALUE = 7000;
    /**
     * <code>kSkillInvalidTargetId = 7001;</code>
     */
    public static final int kSkillInvalidTargetId_VALUE = 7001;
    /**
     * <code>kSkillInvalidTarget = 7002;</code>
     */
    public static final int kSkillInvalidTarget_VALUE = 7002;
    /**
     * <code>kSkillCooldownNotReady = 7003;</code>
     */
    public static final int kSkillCooldownNotReady_VALUE = 7003;
    /**
     * <code>kSkillCannotBeCastInCurrentState = 7004;</code>
     */
    public static final int kSkillCannotBeCastInCurrentState_VALUE = 7004;
    /**
     * <code>kSkillCannotBeCastSilenceRestriction = 7005;</code>
     */
    public static final int kSkillCannotBeCastSilenceRestriction_VALUE = 7005;
    /**
     * <code>kSkillCannotBeCastStunRestriction = 7006;</code>
     */
    public static final int kSkillCannotBeCastStunRestriction_VALUE = 7006;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static skill_error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static skill_error forNumber(int value) {
      switch (value) {
        case 0: return kSkill_errorOK;
        case 7000: return kSkillUnInterruptible;
        case 7001: return kSkillInvalidTargetId;
        case 7002: return kSkillInvalidTarget;
        case 7003: return kSkillCooldownNotReady;
        case 7004: return kSkillCannotBeCastInCurrentState;
        case 7005: return kSkillCannotBeCastSilenceRestriction;
        case 7006: return kSkillCannotBeCastStunRestriction;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<skill_error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        skill_error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<skill_error>() {
            public skill_error findValueByNumber(int number) {
              return skill_error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.table.SkillErrorTip.getDescriptor().getEnumType(0);
    }

    private static final skill_error[] VALUES = values();

    public static skill_error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private skill_error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:skill_error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025skill_error_tip.proto*\212\002\n\013skill_error\022" +
      "\022\n\016kSkill_errorOK\020\000\022\032\n\025kSkillUnInterrupt" +
      "ible\020\3306\022\032\n\025kSkillInvalidTargetId\020\3316\022\030\n\023k" +
      "SkillInvalidTarget\020\3326\022\033\n\026kSkillCooldownN" +
      "otReady\020\3336\022%\n kSkillCannotBeCastInCurren" +
      "tState\020\3346\022)\n$kSkillCannotBeCastSilenceRe" +
      "striction\020\3356\022&\n!kSkillCannotBeCastStunRe" +
      "striction\020\3366B$\n\016com.game.tableZ\022generate" +
      "d/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
