// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: team_error_tip.proto
// Protobuf Java Version: 4.35.1

package com.game.table;

@com.google.protobuf.Generated
public final class TeamErrorTip extends com.google.protobuf.GeneratedFile {
  private TeamErrorTip() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TeamErrorTip");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code team_error}
   */
  public enum team_error
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>kTeam_errorOK = 0;</code>
     */
    kTeam_errorOK(0),
    /**
     * <code>kTeamNotInApplicants = 4000;</code>
     */
    kTeamNotInApplicants(4000),
    /**
     * <code>kTeamPlayerId = 4001;</code>
     */
    kTeamPlayerId(4001),
    /**
     * <code>kTeamMembersFull = 4002;</code>
     */
    kTeamMembersFull(4002),
    /**
     * <code>kTeamMemberInTeam = 4003;</code>
     */
    kTeamMemberInTeam(4003),
    /**
     * <code>kTeamMemberNotInTeam = 4004;</code>
     */
    kTeamMemberNotInTeam(4004),
    /**
     * <code>kTeamKickSelf = 4005;</code>
     */
    kTeamKickSelf(4005),
    /**
     * <code>kTeamKickNotLeader = 4006;</code>
     */
    kTeamKickNotLeader(4006),
    /**
     * <code>kTeamAppointSelf = 4007;</code>
     */
    kTeamAppointSelf(4007),
    /**
     * <code>kTeamAppointLeaderNotLeader = 4008;</code>
     */
    kTeamAppointLeaderNotLeader(4008),
    /**
     * <code>kTeamFull = 4009;</code>
     */
    kTeamFull(4009),
    /**
     * <code>kTeamInApplicantList = 4010;</code>
     */
    kTeamInApplicantList(4010),
    /**
     * <code>kTeamNotInApplicantList = 4011;</code>
     */
    kTeamNotInApplicantList(4011),
    /**
     * <code>kTeamListMaxSize = 4012;</code>
     */
    kTeamListMaxSize(4012),
    /**
     * <code>kTeamHasNotTeamId = 4013;</code>
     */
    kTeamHasNotTeamId(4013),
    /**
     * <code>kTeamDismissNotLeader = 4014;</code>
     */
    kTeamDismissNotLeader(4014),
    /**
     * <code>kTeamMemberListFull = 4015;</code>
     */
    kTeamMemberListFull(4015),
    /**
     * <code>kTeamCreateTeamMaxMemberSize = 4016;</code>
     */
    kTeamCreateTeamMaxMemberSize(4016),
    /**
     * <code>kTeamPlayerNotFound = 4017;</code>
     */
    kTeamPlayerNotFound(4017),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "team_error");
    }
    /**
     * <code>kTeam_errorOK = 0;</code>
     */
    public static final int kTeam_errorOK_VALUE = 0;
    /**
     * <code>kTeamNotInApplicants = 4000;</code>
     */
    public static final int kTeamNotInApplicants_VALUE = 4000;
    /**
     * <code>kTeamPlayerId = 4001;</code>
     */
    public static final int kTeamPlayerId_VALUE = 4001;
    /**
     * <code>kTeamMembersFull = 4002;</code>
     */
    public static final int kTeamMembersFull_VALUE = 4002;
    /**
     * <code>kTeamMemberInTeam = 4003;</code>
     */
    public static final int kTeamMemberInTeam_VALUE = 4003;
    /**
     * <code>kTeamMemberNotInTeam = 4004;</code>
     */
    public static final int kTeamMemberNotInTeam_VALUE = 4004;
    /**
     * <code>kTeamKickSelf = 4005;</code>
     */
    public static final int kTeamKickSelf_VALUE = 4005;
    /**
     * <code>kTeamKickNotLeader = 4006;</code>
     */
    public static final int kTeamKickNotLeader_VALUE = 4006;
    /**
     * <code>kTeamAppointSelf = 4007;</code>
     */
    public static final int kTeamAppointSelf_VALUE = 4007;
    /**
     * <code>kTeamAppointLeaderNotLeader = 4008;</code>
     */
    public static final int kTeamAppointLeaderNotLeader_VALUE = 4008;
    /**
     * <code>kTeamFull = 4009;</code>
     */
    public static final int kTeamFull_VALUE = 4009;
    /**
     * <code>kTeamInApplicantList = 4010;</code>
     */
    public static final int kTeamInApplicantList_VALUE = 4010;
    /**
     * <code>kTeamNotInApplicantList = 4011;</code>
     */
    public static final int kTeamNotInApplicantList_VALUE = 4011;
    /**
     * <code>kTeamListMaxSize = 4012;</code>
     */
    public static final int kTeamListMaxSize_VALUE = 4012;
    /**
     * <code>kTeamHasNotTeamId = 4013;</code>
     */
    public static final int kTeamHasNotTeamId_VALUE = 4013;
    /**
     * <code>kTeamDismissNotLeader = 4014;</code>
     */
    public static final int kTeamDismissNotLeader_VALUE = 4014;
    /**
     * <code>kTeamMemberListFull = 4015;</code>
     */
    public static final int kTeamMemberListFull_VALUE = 4015;
    /**
     * <code>kTeamCreateTeamMaxMemberSize = 4016;</code>
     */
    public static final int kTeamCreateTeamMaxMemberSize_VALUE = 4016;
    /**
     * <code>kTeamPlayerNotFound = 4017;</code>
     */
    public static final int kTeamPlayerNotFound_VALUE = 4017;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static team_error valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static team_error forNumber(int value) {
      switch (value) {
        case 0: return kTeam_errorOK;
        case 4000: return kTeamNotInApplicants;
        case 4001: return kTeamPlayerId;
        case 4002: return kTeamMembersFull;
        case 4003: return kTeamMemberInTeam;
        case 4004: return kTeamMemberNotInTeam;
        case 4005: return kTeamKickSelf;
        case 4006: return kTeamKickNotLeader;
        case 4007: return kTeamAppointSelf;
        case 4008: return kTeamAppointLeaderNotLeader;
        case 4009: return kTeamFull;
        case 4010: return kTeamInApplicantList;
        case 4011: return kTeamNotInApplicantList;
        case 4012: return kTeamListMaxSize;
        case 4013: return kTeamHasNotTeamId;
        case 4014: return kTeamDismissNotLeader;
        case 4015: return kTeamMemberListFull;
        case 4016: return kTeamCreateTeamMaxMemberSize;
        case 4017: return kTeamPlayerNotFound;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<team_error>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        team_error> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<team_error>() {
            public team_error findValueByNumber(int number) {
              return team_error.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.game.table.TeamErrorTip.getDescriptor().getEnumType(0);
    }

    private static final team_error[] VALUES = values();

    public static team_error valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private team_error(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:team_error)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024team_error_tip.proto*\351\003\n\nteam_error\022\021\n" +
      "\rkTeam_errorOK\020\000\022\031\n\024kTeamNotInApplicants" +
      "\020\240\037\022\022\n\rkTeamPlayerId\020\241\037\022\025\n\020kTeamMembersF" +
      "ull\020\242\037\022\026\n\021kTeamMemberInTeam\020\243\037\022\031\n\024kTeamM" +
      "emberNotInTeam\020\244\037\022\022\n\rkTeamKickSelf\020\245\037\022\027\n" +
      "\022kTeamKickNotLeader\020\246\037\022\025\n\020kTeamAppointSe" +
      "lf\020\247\037\022 \n\033kTeamAppointLeaderNotLeader\020\250\037\022" +
      "\016\n\tkTeamFull\020\251\037\022\031\n\024kTeamInApplicantList\020" +
      "\252\037\022\034\n\027kTeamNotInApplicantList\020\253\037\022\025\n\020kTea" +
      "mListMaxSize\020\254\037\022\026\n\021kTeamHasNotTeamId\020\255\037\022" +
      "\032\n\025kTeamDismissNotLeader\020\256\037\022\030\n\023kTeamMemb" +
      "erListFull\020\257\037\022!\n\034kTeamCreateTeamMaxMembe" +
      "rSize\020\260\037\022\030\n\023kTeamPlayerNotFound\020\261\037B$\n\016co" +
      "m.game.tableZ\022generated/pb/tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
