// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: proto/client_rpc_router/client_rpc_router.proto

package client_rpc_router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	base "proto/common/base"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientRpcRouter_Forward_FullMethodName = "/client_rpc_router.ClientRpcRouter/Forward"
)

// ClientRpcRouterClient is the client API for ClientRpcRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientRpcRouter:gate 与业务 Go 服务之间唯一的 gRPC 目标(设计文档 docs/design/client-rpc-router.md)。
//
// 不是客户端协议(刻意不挂 OptionIsClientProtocolService):只有 gate 调用。
// gate 收到客户端 ClientRequest 后不解析 body、不挑业务实例,原样放进 ForwardRequest 发来;
// 会话身份照旧走 gRPC metadata `x-session-detail-bin`(base64 SessionDetails),
// 路由服原样透传给目标服务,并在响应头回写同一段 metadata 供 gate 找回客户端会话。
// 路由服按生成的路由表(message_id → 目标 gRPC 方法 / 节点类型)以原始字节转发,
// 把目标服务的响应包成 MessageContent{id, message_id, serialized_message} 返回;
// 目标不可达 / 未知消息号 / 非客户端协议 → MessageContent.error_message 填 tip 码,body 为空。
//
// 响应直接用 MessageContent:gate 的回包桥接对 MessageContent 类型原样下发,
// 不需要为路由服再加任何 gate 侧代码。
type ClientRpcRouterClient interface {
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*base.MessageContent, error)
}

type clientRpcRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewClientRpcRouterClient(cc grpc.ClientConnInterface) ClientRpcRouterClient {
	return &clientRpcRouterClient{cc}
}

func (c *clientRpcRouterClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*base.MessageContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.MessageContent)
	err := c.cc.Invoke(ctx, ClientRpcRouter_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientRpcRouterServer is the server API for ClientRpcRouter service.
// All implementations must embed UnimplementedClientRpcRouterServer
// for forward compatibility.
//
// ClientRpcRouter:gate 与业务 Go 服务之间唯一的 gRPC 目标(设计文档 docs/design/client-rpc-router.md)。
//
// 不是客户端协议(刻意不挂 OptionIsClientProtocolService):只有 gate 调用。
// gate 收到客户端 ClientRequest 后不解析 body、不挑业务实例,原样放进 ForwardRequest 发来;
// 会话身份照旧走 gRPC metadata `x-session-detail-bin`(base64 SessionDetails),
// 路由服原样透传给目标服务,并在响应头回写同一段 metadata 供 gate 找回客户端会话。
// 路由服按生成的路由表(message_id → 目标 gRPC 方法 / 节点类型)以原始字节转发,
// 把目标服务的响应包成 MessageContent{id, message_id, serialized_message} 返回;
// 目标不可达 / 未知消息号 / 非客户端协议 → MessageContent.error_message 填 tip 码,body 为空。
//
// 响应直接用 MessageContent:gate 的回包桥接对 MessageContent 类型原样下发,
// 不需要为路由服再加任何 gate 侧代码。
type ClientRpcRouterServer interface {
	Forward(context.Context, *ForwardRequest) (*base.MessageContent, error)
	mustEmbedUnimplementedClientRpcRouterServer()
}

// UnimplementedClientRpcRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientRpcRouterServer struct{}

func (UnimplementedClientRpcRouterServer) Forward(context.Context, *ForwardRequest) (*base.MessageContent, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedClientRpcRouterServer) mustEmbedUnimplementedClientRpcRouterServer() {}
func (UnimplementedClientRpcRouterServer) testEmbeddedByValue()                         {}

// UnsafeClientRpcRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientRpcRouterServer will
// result in compilation errors.
type UnsafeClientRpcRouterServer interface {
	mustEmbedUnimplementedClientRpcRouterServer()
}

func RegisterClientRpcRouterServer(s grpc.ServiceRegistrar, srv ClientRpcRouterServer) {
	// If the following call panics, it indicates UnimplementedClientRpcRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientRpcRouter_ServiceDesc, srv)
}

func _ClientRpcRouter_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientRpcRouterServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientRpcRouter_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientRpcRouterServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientRpcRouter_ServiceDesc is the grpc.ServiceDesc for ClientRpcRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientRpcRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client_rpc_router.ClientRpcRouter",
	HandlerType: (*ClientRpcRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _ClientRpcRouter_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/client_rpc_router/client_rpc_router.proto",
}
