// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.1
// source: proto/match/match_internal.proto

package match

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchInternal_StartActivityBattle_FullMethodName = "/match.MatchInternal/StartActivityBattle"
)

// MatchInternalClient is the client API for MatchInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchInternalClient interface {
	StartActivityBattle(ctx context.Context, in *StartActivityBattleRequest, opts ...grpc.CallOption) (*StartActivityBattleResponse, error)
}

type matchInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchInternalClient(cc grpc.ClientConnInterface) MatchInternalClient {
	return &matchInternalClient{cc}
}

func (c *matchInternalClient) StartActivityBattle(ctx context.Context, in *StartActivityBattleRequest, opts ...grpc.CallOption) (*StartActivityBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartActivityBattleResponse)
	err := c.cc.Invoke(ctx, MatchInternal_StartActivityBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchInternalServer is the server API for MatchInternal service.
// All implementations must embed UnimplementedMatchInternalServer
// for forward compatibility.
type MatchInternalServer interface {
	StartActivityBattle(context.Context, *StartActivityBattleRequest) (*StartActivityBattleResponse, error)
	mustEmbedUnimplementedMatchInternalServer()
}

// UnimplementedMatchInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchInternalServer struct{}

func (UnimplementedMatchInternalServer) StartActivityBattle(context.Context, *StartActivityBattleRequest) (*StartActivityBattleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartActivityBattle not implemented")
}
func (UnimplementedMatchInternalServer) mustEmbedUnimplementedMatchInternalServer() {}
func (UnimplementedMatchInternalServer) testEmbeddedByValue()                       {}

// UnsafeMatchInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchInternalServer will
// result in compilation errors.
type UnsafeMatchInternalServer interface {
	mustEmbedUnimplementedMatchInternalServer()
}

func RegisterMatchInternalServer(s grpc.ServiceRegistrar, srv MatchInternalServer) {
	// If the following call panics, it indicates UnimplementedMatchInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchInternal_ServiceDesc, srv)
}

func _MatchInternal_StartActivityBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartActivityBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchInternalServer).StartActivityBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchInternal_StartActivityBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchInternalServer).StartActivityBattle(ctx, req.(*StartActivityBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchInternal_ServiceDesc is the grpc.ServiceDesc for MatchInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match.MatchInternal",
	HandlerType: (*MatchInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartActivityBattle",
			Handler:    _MatchInternal_StartActivityBattle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/match/match_internal.proto",
}
