// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/match/match_service.proto

package match

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	base "proto/common/base"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchService_JoinQueue_FullMethodName             = "/match.MatchService/JoinQueue"
	MatchService_CancelQueue_FullMethodName           = "/match.MatchService/CancelQueue"
	MatchService_GetQueueStatus_FullMethodName        = "/match.MatchService/GetQueueStatus"
	MatchService_ChallengePlayer_FullMethodName       = "/match.MatchService/ChallengePlayer"
	MatchService_RespondChallenge_FullMethodName      = "/match.MatchService/RespondChallenge"
	MatchService_NotifyChallengeInvite_FullMethodName = "/match.MatchService/NotifyChallengeInvite"
	MatchService_NotifyChallengeResult_FullMethodName = "/match.MatchService/NotifyChallengeResult"
	MatchService_WatchBattle_FullMethodName           = "/match.MatchService/WatchBattle"
	MatchService_ListWatchableBattles_FullMethodName  = "/match.MatchService/ListWatchableBattles"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchService:统一开局入口(回合制战斗一期启用,设计文档 turn-based-battle-server.md D3)。
// 客户端经 gate 按文件路由选项直达 match 服务(照 login 模式,权威 player_id 取自
// session metadata,请求内 player_id 仅内部调用使用)。
// 凑单成功后走 gather 协议:scene.PrepareBattle 收快照 -> battle.CreateBattle,
// 失败按补偿矩阵回滚(设计文档 §3.2)。
type MatchServiceClient interface {
	// Player requests to join a match queue.
	JoinQueue(ctx context.Context, in *JoinQueueRequest, opts ...grpc.CallOption) (*JoinQueueResponse, error)
	// Player cancels their queued match request.
	CancelQueue(ctx context.Context, in *CancelQueueRequest, opts ...grpc.CallOption) (*base.Empty, error)
	// Query current queue status for a player.
	GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*GetQueueStatusResponse, error)
	// ---- 场景发起 PK(切磋):点名成局入口,与队列匹配汇入同一条 gather 开局管线 ----
	ChallengePlayer(ctx context.Context, in *ChallengePlayerRequest, opts ...grpc.CallOption) (*ChallengePlayerResponse, error)
	RespondChallenge(ctx context.Context, in *RespondChallengeRequest, opts ...grpc.CallOption) (*RespondChallengeResponse, error)
	NotifyChallengeInvite(ctx context.Context, in *ChallengeInviteS2C, opts ...grpc.CallOption) (*base.Empty, error)
	NotifyChallengeResult(ctx context.Context, in *ChallengeResultS2C, opts ...grpc.CallOption) (*base.Empty, error)
	// ---- 二期:观战匹配(设计文档 §10) ----
	// battle_id=0 表示随机观战(从活跃战斗索引里随机挑一场);成功后由 battle 节点
	// 经 Kafka 推 NotifySpectateState 首帧,客户端收到首帧才算进入观战。
	WatchBattle(ctx context.Context, in *WatchBattleRequest, opts ...grpc.CallOption) (*WatchBattleResponse, error)
	ListWatchableBattles(ctx context.Context, in *ListWatchableBattlesRequest, opts ...grpc.CallOption) (*ListWatchableBattlesResponse, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) JoinQueue(ctx context.Context, in *JoinQueueRequest, opts ...grpc.CallOption) (*JoinQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinQueueResponse)
	err := c.cc.Invoke(ctx, MatchService_JoinQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) CancelQueue(ctx context.Context, in *CancelQueueRequest, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, MatchService_CancelQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetQueueStatus(ctx context.Context, in *GetQueueStatusRequest, opts ...grpc.CallOption) (*GetQueueStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueStatusResponse)
	err := c.cc.Invoke(ctx, MatchService_GetQueueStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) ChallengePlayer(ctx context.Context, in *ChallengePlayerRequest, opts ...grpc.CallOption) (*ChallengePlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengePlayerResponse)
	err := c.cc.Invoke(ctx, MatchService_ChallengePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) RespondChallenge(ctx context.Context, in *RespondChallengeRequest, opts ...grpc.CallOption) (*RespondChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondChallengeResponse)
	err := c.cc.Invoke(ctx, MatchService_RespondChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) NotifyChallengeInvite(ctx context.Context, in *ChallengeInviteS2C, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, MatchService_NotifyChallengeInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) NotifyChallengeResult(ctx context.Context, in *ChallengeResultS2C, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, MatchService_NotifyChallengeResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) WatchBattle(ctx context.Context, in *WatchBattleRequest, opts ...grpc.CallOption) (*WatchBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchBattleResponse)
	err := c.cc.Invoke(ctx, MatchService_WatchBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) ListWatchableBattles(ctx context.Context, in *ListWatchableBattlesRequest, opts ...grpc.CallOption) (*ListWatchableBattlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchableBattlesResponse)
	err := c.cc.Invoke(ctx, MatchService_ListWatchableBattles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
//
// MatchService:统一开局入口(回合制战斗一期启用,设计文档 turn-based-battle-server.md D3)。
// 客户端经 gate 按文件路由选项直达 match 服务(照 login 模式,权威 player_id 取自
// session metadata,请求内 player_id 仅内部调用使用)。
// 凑单成功后走 gather 协议:scene.PrepareBattle 收快照 -> battle.CreateBattle,
// 失败按补偿矩阵回滚(设计文档 §3.2)。
type MatchServiceServer interface {
	// Player requests to join a match queue.
	JoinQueue(context.Context, *JoinQueueRequest) (*JoinQueueResponse, error)
	// Player cancels their queued match request.
	CancelQueue(context.Context, *CancelQueueRequest) (*base.Empty, error)
	// Query current queue status for a player.
	GetQueueStatus(context.Context, *GetQueueStatusRequest) (*GetQueueStatusResponse, error)
	// ---- 场景发起 PK(切磋):点名成局入口,与队列匹配汇入同一条 gather 开局管线 ----
	ChallengePlayer(context.Context, *ChallengePlayerRequest) (*ChallengePlayerResponse, error)
	RespondChallenge(context.Context, *RespondChallengeRequest) (*RespondChallengeResponse, error)
	NotifyChallengeInvite(context.Context, *ChallengeInviteS2C) (*base.Empty, error)
	NotifyChallengeResult(context.Context, *ChallengeResultS2C) (*base.Empty, error)
	// ---- 二期:观战匹配(设计文档 §10) ----
	// battle_id=0 表示随机观战(从活跃战斗索引里随机挑一场);成功后由 battle 节点
	// 经 Kafka 推 NotifySpectateState 首帧,客户端收到首帧才算进入观战。
	WatchBattle(context.Context, *WatchBattleRequest) (*WatchBattleResponse, error)
	ListWatchableBattles(context.Context, *ListWatchableBattlesRequest) (*ListWatchableBattlesResponse, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) JoinQueue(context.Context, *JoinQueueRequest) (*JoinQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinQueue not implemented")
}
func (UnimplementedMatchServiceServer) CancelQueue(context.Context, *CancelQueueRequest) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQueue not implemented")
}
func (UnimplementedMatchServiceServer) GetQueueStatus(context.Context, *GetQueueStatusRequest) (*GetQueueStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueStatus not implemented")
}
func (UnimplementedMatchServiceServer) ChallengePlayer(context.Context, *ChallengePlayerRequest) (*ChallengePlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChallengePlayer not implemented")
}
func (UnimplementedMatchServiceServer) RespondChallenge(context.Context, *RespondChallengeRequest) (*RespondChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RespondChallenge not implemented")
}
func (UnimplementedMatchServiceServer) NotifyChallengeInvite(context.Context, *ChallengeInviteS2C) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyChallengeInvite not implemented")
}
func (UnimplementedMatchServiceServer) NotifyChallengeResult(context.Context, *ChallengeResultS2C) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyChallengeResult not implemented")
}
func (UnimplementedMatchServiceServer) WatchBattle(context.Context, *WatchBattleRequest) (*WatchBattleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchBattle not implemented")
}
func (UnimplementedMatchServiceServer) ListWatchableBattles(context.Context, *ListWatchableBattlesRequest) (*ListWatchableBattlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatchableBattles not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_JoinQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).JoinQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_JoinQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).JoinQueue(ctx, req.(*JoinQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_CancelQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).CancelQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_CancelQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).CancelQueue(ctx, req.(*CancelQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetQueueStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetQueueStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_GetQueueStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetQueueStatus(ctx, req.(*GetQueueStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_ChallengePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).ChallengePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_ChallengePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).ChallengePlayer(ctx, req.(*ChallengePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_RespondChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).RespondChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_RespondChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).RespondChallenge(ctx, req.(*RespondChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_NotifyChallengeInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeInviteS2C)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).NotifyChallengeInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_NotifyChallengeInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).NotifyChallengeInvite(ctx, req.(*ChallengeInviteS2C))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_NotifyChallengeResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeResultS2C)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).NotifyChallengeResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_NotifyChallengeResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).NotifyChallengeResult(ctx, req.(*ChallengeResultS2C))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_WatchBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).WatchBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_WatchBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).WatchBattle(ctx, req.(*WatchBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_ListWatchableBattles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchableBattlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).ListWatchableBattles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_ListWatchableBattles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).ListWatchableBattles(ctx, req.(*ListWatchableBattlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinQueue",
			Handler:    _MatchService_JoinQueue_Handler,
		},
		{
			MethodName: "CancelQueue",
			Handler:    _MatchService_CancelQueue_Handler,
		},
		{
			MethodName: "GetQueueStatus",
			Handler:    _MatchService_GetQueueStatus_Handler,
		},
		{
			MethodName: "ChallengePlayer",
			Handler:    _MatchService_ChallengePlayer_Handler,
		},
		{
			MethodName: "RespondChallenge",
			Handler:    _MatchService_RespondChallenge_Handler,
		},
		{
			MethodName: "NotifyChallengeInvite",
			Handler:    _MatchService_NotifyChallengeInvite_Handler,
		},
		{
			MethodName: "NotifyChallengeResult",
			Handler:    _MatchService_NotifyChallengeResult_Handler,
		},
		{
			MethodName: "WatchBattle",
			Handler:    _MatchService_WatchBattle_Handler,
		},
		{
			MethodName: "ListWatchableBattles",
			Handler:    _MatchService_ListWatchableBattles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/match/match_service.proto",
}
