// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/match/match_internal.proto

package match

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	battle "proto/battle"
	_ "proto/db"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 拒绝原因。业务拒绝一律走响应里的 reject,不回 gRPC 错误;
// gRPC 错误只用于 PermissionDenied(带会话调用)与传输层故障,guild 统一映射为 GuildTrialServiceBusy。
type ActivityBattleReject int32

const (
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_NONE             ActivityBattleReject = 0 // 成功:battle_id 非 0,gather 已异步启动
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_INVALID_ARGUMENT ActivityBattleReject = 1 // 人数越界 / 0 或重复 id / battle_config_id 为 0 / 上下文缺失或字段为 0 / 发起人不在首位
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_MEMBER_OFFLINE   ActivityBattleReject = 2 // offender 无在线会话
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_MEMBER_IN_BATTLE ActivityBattleReject = 3 // offender 持有 battle:lock(已在战斗中)
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_MEMBER_NOT_READY ActivityBattleReject = 4 // offender 无场景位置 / 有未自愈的在途票据 / 建 matched 票失败
	ActivityBattleReject_ACTIVITY_BATTLE_REJECT_INTERNAL         ActivityBattleReject = 5 // match 内部故障:发号失败 / Redis 读写出错(guild 映射为 GuildTrialServiceBusy)
)

// Enum value maps for ActivityBattleReject.
var (
	ActivityBattleReject_name = map[int32]string{
		0: "ACTIVITY_BATTLE_REJECT_NONE",
		1: "ACTIVITY_BATTLE_REJECT_INVALID_ARGUMENT",
		2: "ACTIVITY_BATTLE_REJECT_MEMBER_OFFLINE",
		3: "ACTIVITY_BATTLE_REJECT_MEMBER_IN_BATTLE",
		4: "ACTIVITY_BATTLE_REJECT_MEMBER_NOT_READY",
		5: "ACTIVITY_BATTLE_REJECT_INTERNAL",
	}
	ActivityBattleReject_value = map[string]int32{
		"ACTIVITY_BATTLE_REJECT_NONE":             0,
		"ACTIVITY_BATTLE_REJECT_INVALID_ARGUMENT": 1,
		"ACTIVITY_BATTLE_REJECT_MEMBER_OFFLINE":   2,
		"ACTIVITY_BATTLE_REJECT_MEMBER_IN_BATTLE": 3,
		"ACTIVITY_BATTLE_REJECT_MEMBER_NOT_READY": 4,
		"ACTIVITY_BATTLE_REJECT_INTERNAL":         5,
	}
)

func (x ActivityBattleReject) Enum() *ActivityBattleReject {
	p := new(ActivityBattleReject)
	*p = x
	return p
}

func (x ActivityBattleReject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityBattleReject) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_match_match_internal_proto_enumTypes[0].Descriptor()
}

func (ActivityBattleReject) Type() protoreflect.EnumType {
	return &file_proto_match_match_internal_proto_enumTypes[0]
}

func (x ActivityBattleReject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityBattleReject.Descriptor instead.
func (ActivityBattleReject) EnumDescriptor() ([]byte, []int) {
	return file_proto_match_match_internal_proto_rawDescGZIP(), []int{0}
}

type StartActivityBattleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BattleConfigId uint32                 `protobuf:"varint,1,opt,name=battle_config_id,json=battleConfigId,proto3" json:"battle_config_id,omitempty"` // DungeonTable id(= GuildActivity.dungeon_id);非 0
	// 站位顺序即队伍顺序,发起人在首位;1..kMaxBattleTeamSize(5)人、非 0、不重复。
	// 名单是 guild 邀请房间里全员已同意的同帮成员,match 只做在线 / 战斗锁 / 位置 / 在途票的只读预检,不复核帮会归属。
	MemberPlayerIds []uint64 `protobuf:"varint,2,rep,packed,name=member_player_ids,json=memberPlayerIds,proto3" json:"member_player_ids,omitempty"`
	// 活动上下文:kind 必须非 NONE,guild_id / activity_id / period_key / guild_period_key 非 0,
	// initiator_player_id == member_player_ids[0]。match 深拷贝后原样放进 CreateBattleRequest.activity_context。
	ActivityContext *battle.BattleActivityContext `protobuf:"bytes,3,opt,name=activity_context,json=activityContext,proto3" json:"activity_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartActivityBattleRequest) Reset() {
	*x = StartActivityBattleRequest{}
	mi := &file_proto_match_match_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartActivityBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartActivityBattleRequest) ProtoMessage() {}

func (x *StartActivityBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartActivityBattleRequest.ProtoReflect.Descriptor instead.
func (*StartActivityBattleRequest) Descriptor() ([]byte, []int) {
	return file_proto_match_match_internal_proto_rawDescGZIP(), []int{0}
}

func (x *StartActivityBattleRequest) GetBattleConfigId() uint32 {
	if x != nil {
		return x.BattleConfigId
	}
	return 0
}

func (x *StartActivityBattleRequest) GetMemberPlayerIds() []uint64 {
	if x != nil {
		return x.MemberPlayerIds
	}
	return nil
}

func (x *StartActivityBattleRequest) GetActivityContext() *battle.BattleActivityContext {
	if x != nil {
		return x.ActivityContext
	}
	return nil
}

type StartActivityBattleResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Reject           ActivityBattleReject   `protobuf:"varint,1,opt,name=reject,proto3,enum=match.ActivityBattleReject" json:"reject,omitempty"`
	OffenderPlayerId uint64                 `protobuf:"varint,2,opt,name=offender_player_id,json=offenderPlayerId,proto3" json:"offender_player_id,omitempty"` // reject 为 MEMBER_OFFLINE / MEMBER_IN_BATTLE / MEMBER_NOT_READY 时非 0(名单顺序里第一个不满足的人);其余为 0
	// reject == NONE 时非 0:match 同步生成(shared/snowflake,battle_id 唯一生产者)并已为全员建好 matched 票、
	// 异步启动 gather;guild 据此登记 guild_trial_battle。gather 之后失败时全员删票、不回队列,
	// 该 battle_id 不会产生结果事件,由 guild 巡检器兜底判 EXPIRED。
	BattleId      uint64 `protobuf:"varint,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartActivityBattleResponse) Reset() {
	*x = StartActivityBattleResponse{}
	mi := &file_proto_match_match_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartActivityBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartActivityBattleResponse) ProtoMessage() {}

func (x *StartActivityBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_match_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartActivityBattleResponse.ProtoReflect.Descriptor instead.
func (*StartActivityBattleResponse) Descriptor() ([]byte, []int) {
	return file_proto_match_match_internal_proto_rawDescGZIP(), []int{1}
}

func (x *StartActivityBattleResponse) GetReject() ActivityBattleReject {
	if x != nil {
		return x.Reject
	}
	return ActivityBattleReject_ACTIVITY_BATTLE_REJECT_NONE
}

func (x *StartActivityBattleResponse) GetOffenderPlayerId() uint64 {
	if x != nil {
		return x.OffenderPlayerId
	}
	return 0
}

func (x *StartActivityBattleResponse) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

var File_proto_match_match_internal_proto protoreflect.FileDescriptor

const file_proto_match_match_internal_proto_rawDesc = "" +
	"\n" +
	" proto/match/match_internal.proto\x12\x05match\x1a\x1bproto/db/proto_option.proto\x1a\x1eproto/battle/battle_data.proto\"\xb5\x01\n" +
	"\x1aStartActivityBattleRequest\x12(\n" +
	"\x10battle_config_id\x18\x01 \x01(\rR\x0ebattleConfigId\x12*\n" +
	"\x11member_player_ids\x18\x02 \x03(\x04R\x0fmemberPlayerIds\x12A\n" +
	"\x10activity_context\x18\x03 \x01(\v2\x16.BattleActivityContextR\x0factivityContext\"\x9d\x01\n" +
	"\x1bStartActivityBattleResponse\x123\n" +
	"\x06reject\x18\x01 \x01(\x0e2\x1b.match.ActivityBattleRejectR\x06reject\x12,\n" +
	"\x12offender_player_id\x18\x02 \x01(\x04R\x10offenderPlayerId\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\x04R\bbattleId*\x8e\x02\n" +
	"\x14ActivityBattleReject\x12\x1f\n" +
	"\x1bACTIVITY_BATTLE_REJECT_NONE\x10\x00\x12+\n" +
	"'ACTIVITY_BATTLE_REJECT_INVALID_ARGUMENT\x10\x01\x12)\n" +
	"%ACTIVITY_BATTLE_REJECT_MEMBER_OFFLINE\x10\x02\x12+\n" +
	"'ACTIVITY_BATTLE_REJECT_MEMBER_IN_BATTLE\x10\x03\x12+\n" +
	"'ACTIVITY_BATTLE_REJECT_MEMBER_NOT_READY\x10\x04\x12#\n" +
	"\x1fACTIVITY_BATTLE_REJECT_INTERNAL\x10\x052m\n" +
	"\rMatchInternal\x12\\\n" +
	"\x13StartActivityBattle\x12!.match.StartActivityBattleRequest\x1a\".match.StartActivityBattleResponseB\x14\x98\xd4a\x15Z\vproto/match\x80\x01\x00b\x06proto3"

var (
	file_proto_match_match_internal_proto_rawDescOnce sync.Once
	file_proto_match_match_internal_proto_rawDescData []byte
)

func file_proto_match_match_internal_proto_rawDescGZIP() []byte {
	file_proto_match_match_internal_proto_rawDescOnce.Do(func() {
		file_proto_match_match_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_match_match_internal_proto_rawDesc), len(file_proto_match_match_internal_proto_rawDesc)))
	})
	return file_proto_match_match_internal_proto_rawDescData
}

var file_proto_match_match_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_match_match_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_match_match_internal_proto_goTypes = []any{
	(ActivityBattleReject)(0),            // 0: match.ActivityBattleReject
	(*StartActivityBattleRequest)(nil),   // 1: match.StartActivityBattleRequest
	(*StartActivityBattleResponse)(nil),  // 2: match.StartActivityBattleResponse
	(*battle.BattleActivityContext)(nil), // 3: BattleActivityContext
}
var file_proto_match_match_internal_proto_depIdxs = []int32{
	3, // 0: match.StartActivityBattleRequest.activity_context:type_name -> BattleActivityContext
	0, // 1: match.StartActivityBattleResponse.reject:type_name -> match.ActivityBattleReject
	1, // 2: match.MatchInternal.StartActivityBattle:input_type -> match.StartActivityBattleRequest
	2, // 3: match.MatchInternal.StartActivityBattle:output_type -> match.StartActivityBattleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_match_match_internal_proto_init() }
func file_proto_match_match_internal_proto_init() {
	if File_proto_match_match_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_match_match_internal_proto_rawDesc), len(file_proto_match_match_internal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_match_match_internal_proto_goTypes,
		DependencyIndexes: file_proto_match_match_internal_proto_depIdxs,
		EnumInfos:         file_proto_match_match_internal_proto_enumTypes,
		MessageInfos:      file_proto_match_match_internal_proto_msgTypes,
	}.Build()
	File_proto_match_match_internal_proto = out.File
	file_proto_match_match_internal_proto_goTypes = nil
	file_proto_match_match_internal_proto_depIdxs = nil
}
