// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/common/component/player_comp.proto

package component

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Normal login
type NormalLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalLogin) Reset() {
	*x = NormalLogin{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalLogin) ProtoMessage() {}

func (x *NormalLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalLogin.ProtoReflect.Descriptor instead.
func (*NormalLogin) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{0}
}

// Session takeover login
type CoverLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverLogin) Reset() {
	*x = CoverLogin{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverLogin) ProtoMessage() {}

func (x *CoverLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverLogin.ProtoReflect.Descriptor instead.
func (*CoverLogin) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{1}
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{2}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type UnregisterPlayer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall-clock millis when HandleExitGameNode was called (and SavePlayerToRedis
	// was enqueued). Used to detect saves that outrun the player_locator
	// reconnect lease (30s). See todo.md #280 / NOTES Part 2 P0.
	LogoutInitiatedMs int64 `protobuf:"varint,1,opt,name=logout_initiated_ms,json=logoutInitiatedMs,proto3" json:"logout_initiated_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnregisterPlayer) Reset() {
	*x = UnregisterPlayer{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterPlayer) ProtoMessage() {}

func (x *UnregisterPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterPlayer.ProtoReflect.Descriptor instead.
func (*UnregisterPlayer) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterPlayer) GetLogoutInitiatedMs() int64 {
	if x != nil {
		return x.LogoutInitiatedMs
	}
	return 0
}

type PlayerUint64Comp struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RegistrationTimestamp uint64                 `protobuf:"varint,1,opt,name=registration_timestamp,json=registrationTimestamp,proto3" json:"registration_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerUint64Comp) Reset() {
	*x = PlayerUint64Comp{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUint64Comp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUint64Comp) ProtoMessage() {}

func (x *PlayerUint64Comp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUint64Comp.ProtoReflect.Descriptor instead.
func (*PlayerUint64Comp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerUint64Comp) GetRegistrationTimestamp() uint64 {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return 0
}

type PlayerUint32Comp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         uint32                 `protobuf:"varint,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUint32Comp) Reset() {
	*x = PlayerUint32Comp{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUint32Comp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUint32Comp) ProtoMessage() {}

func (x *PlayerUint32Comp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUint32Comp.ProtoReflect.Descriptor instead.
func (*PlayerUint32Comp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerUint32Comp) GetClass() uint32 {
	if x != nil {
		return x.Class
	}
	return 0
}

// 角色展示资料(名字)。
// 真源是 data_service 全局库的 player_name 表(全服唯一,docs/design/guild-phase2/03-names.md §3.0);
// 这里是随 player_database 一起走的只读副本,由 login 首次入场补齐
// (go/login/.../player_class_backfill.go backfillPlayerIdentity)。
// scene 只读、只原样存回:战斗快照 player_battle.cpp 取的就是这一份,
// 组件缺失 / name 为空时快照留空,battle 照常结算(名字是展示数据,fail-open)。
// v1 无改名,所以副本内容不会变;但副本可能缺失(self-heal 恢复出的空记录、
// 早于首次入场的回档快照),任何"要拿到名字"的读侧都必须能回源 BatchGetPlayerName。
type PlayerProfileComp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 随存档原样往返；login 首次入场从账号补空，scene/战斗/队伍只读。
	AppearanceId  string `protobuf:"bytes,2,opt,name=appearance_id,json=appearanceId,proto3" json:"appearance_id,omitempty"`
	Gender        uint32 `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"` // 1=男 2=女；0=旧存档未补齐，与外观 ID 独立。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerProfileComp) Reset() {
	*x = PlayerProfileComp{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProfileComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProfileComp) ProtoMessage() {}

func (x *PlayerProfileComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProfileComp.ProtoReflect.Descriptor instead.
func (*PlayerProfileComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerProfileComp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerProfileComp) GetAppearanceId() string {
	if x != nil {
		return x.AppearanceId
	}
	return ""
}

func (x *PlayerProfileComp) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

// Stress-test instrumentation for player-data persistence.
//
// Stamped by the producer (Scene's SavePlayerToRedis when an env-var probe
// is enabled, or by the data_stress driver / robot data-stress mode) and
// verified by tools/cmd/verifier so we can prove "last write wins" through
// the Kafka -> DB -> MySQL+Redis pipeline without doing per-field deep
// diffs. Fields default-empty in normal play, so they cost nothing on disk
// or wire when unused.
type PlayerStressTestProbe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic per-(player_id, msg_type) sequence. Verifier asserts
	// MySQL.test_seq == Redis.test_seq == max(test_seq) ever published.
	TestSeq uint64 `protobuf:"varint,1,opt,name=test_seq,json=testSeq,proto3" json:"test_seq,omitempty"`
	// HMAC-style signature over (player_id || msg_type || test_seq || nonce).
	// Used to detect torn / mis-routed / replayed payloads — if test_sig
	// matches the recomputed value we know the row was not silently
	// reassembled or fed from a different stream.
	TestSig       []byte `protobuf:"bytes,2,opt,name=test_sig,json=testSig,proto3" json:"test_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStressTestProbe) Reset() {
	*x = PlayerStressTestProbe{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStressTestProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStressTestProbe) ProtoMessage() {}

func (x *PlayerStressTestProbe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStressTestProbe.ProtoReflect.Descriptor instead.
func (*PlayerStressTestProbe) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerStressTestProbe) GetTestSeq() uint64 {
	if x != nil {
		return x.TestSeq
	}
	return 0
}

func (x *PlayerStressTestProbe) GetTestSig() []byte {
	if x != nil {
		return x.TestSig
	}
	return nil
}

// Server-merge state attached to a player whose home zone was folded into
// another zone. Both fields default to zero / false during normal play and
// only get populated by `tools/merge_zone/` (P0-G stamp + P3-H notice
// stamp) right before the merge maintenance window ends.
//
// Why a dedicated component instead of stuffing the flags into
// PlayerUint32Comp:
//  1. Persistence locality — these fields live and die with the merge
//     lifecycle (set during merge → cleared on first post-merge action).
//     Co-locating them with `class` would mix transient migration state
//     with permanent identity state, making the field-level history
//     harder to read in audit logs.
//  2. Clear ownership — `tools/merge_zone/` is the only writer for set,
//     `go/login/internal/logic/clientplayerlogin/` is the only writer
//     for clear. Anchoring the schema to a separate component lets us
//     grep for "merge state writer" without false hits.
//  3. Forward-compat — if the merge story grows additional flags
//     (post-merge guild-membership reconciliation, post-merge auction
//     payout receipt, etc.) they belong here, not bolted onto unrelated
//     components.
//
// See:
//   - docs/design/server-merge-gap-fixes.md §1 (force_rename design)
//   - docs/design/server-merge-gap-fixes.md §5 (post-merge notice)
//   - docs/ops/merge-zone-runbook.md §4.4 / §7
type PlayerMergeStateComp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stamped to true by tools/merge_zone/ when this player's nickname
	// collides with an existing nickname in the merge target zone (the
	// schema is per-zone UNIQUE, see server-merge-gap-fixes.md §1.2).
	//
	// Login flow contract: when a client's player blob has this flag set,
	// the client MUST surface a forced-rename UI before the player can
	// enter the world. The server-side rename RPC clears the flag on a
	// successful name change. CLAUDE.md §9 forbids adding a 5th
	// `enter_gs_type`, so the gating happens client-side; see
	// server-merge-gap-fixes.md §1.4 for why.
	ForceRenameRequired bool `protobuf:"varint,1,opt,name=force_rename_required,json=forceRenameRequired,proto3" json:"force_rename_required,omitempty"`
	// Wall-clock millis when force_rename_required was stamped. Used by
	// the merge runbook (§7.1) to monitor the post-merge improvement
	// curve — if a stamp is older than 7 days the player has been
	// dodging the rename UI and ops should reach out. Audit-only field;
	// no game logic should branch on it.
	ForceRenameStampedMs int64 `protobuf:"varint,2,opt,name=force_rename_stamped_ms,json=forceRenameStampedMs,proto3" json:"force_rename_stamped_ms,omitempty"`
	// Wall-clock millis the post-merge notice was last shown to the
	// player. Zero means "never shown / not stamped". Stamped by
	// tools/merge_zone/ to (now - 1) so the very next login triggers
	// the notice exactly once; the login pipeline updates it to the
	// current ms once the client ACKs the notice. This is the P3-H
	// (post-merge announcement) hook — see server-merge-gap-fixes.md §5.
	//
	// We deliberately use a timestamp (not a bool) so future merges
	// re-stamp the same field instead of needing a new flag — a player
	// surviving two merges (zone1→zone2→zone3) gets two notices, not
	// one bool that flips.
	PostMergeNoticeSeenMs int64 `protobuf:"varint,3,opt,name=post_merge_notice_seen_ms,json=postMergeNoticeSeenMs,proto3" json:"post_merge_notice_seen_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerMergeStateComp) Reset() {
	*x = PlayerMergeStateComp{}
	mi := &file_proto_common_component_player_comp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMergeStateComp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMergeStateComp) ProtoMessage() {}

func (x *PlayerMergeStateComp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_component_player_comp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMergeStateComp.ProtoReflect.Descriptor instead.
func (*PlayerMergeStateComp) Descriptor() ([]byte, []int) {
	return file_proto_common_component_player_comp_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerMergeStateComp) GetForceRenameRequired() bool {
	if x != nil {
		return x.ForceRenameRequired
	}
	return false
}

func (x *PlayerMergeStateComp) GetForceRenameStampedMs() int64 {
	if x != nil {
		return x.ForceRenameStampedMs
	}
	return 0
}

func (x *PlayerMergeStateComp) GetPostMergeNoticeSeenMs() int64 {
	if x != nil {
		return x.PostMergeNoticeSeenMs
	}
	return 0
}

var File_proto_common_component_player_comp_proto protoreflect.FileDescriptor

const file_proto_common_component_player_comp_proto_rawDesc = "" +
	"\n" +
	"(proto/common/component/player_comp.proto\"\r\n" +
	"\vNormalLogin\"\f\n" +
	"\n" +
	"CoverLogin\"\b\n" +
	"\x06Player\"#\n" +
	"\aAccount\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"B\n" +
	"\x10UnregisterPlayer\x12.\n" +
	"\x13logout_initiated_ms\x18\x01 \x01(\x03R\x11logoutInitiatedMs\"I\n" +
	"\x10PlayerUint64Comp\x125\n" +
	"\x16registration_timestamp\x18\x01 \x01(\x04R\x15registrationTimestamp\"(\n" +
	"\x10PlayerUint32Comp\x12\x14\n" +
	"\x05class\x18\x01 \x01(\rR\x05class\"d\n" +
	"\x11PlayerProfileComp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rappearance_id\x18\x02 \x01(\tR\fappearanceId\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\rR\x06gender\"M\n" +
	"\x15PlayerStressTestProbe\x12\x19\n" +
	"\btest_seq\x18\x01 \x01(\x04R\atestSeq\x12\x19\n" +
	"\btest_sig\x18\x02 \x01(\fR\atestSig\"\xbb\x01\n" +
	"\x14PlayerMergeStateComp\x122\n" +
	"\x15force_rename_required\x18\x01 \x01(\bR\x13forceRenameRequired\x125\n" +
	"\x17force_rename_stamped_ms\x18\x02 \x01(\x03R\x14forceRenameStampedMs\x128\n" +
	"\x19post_merge_notice_seen_ms\x18\x03 \x01(\x03R\x15postMergeNoticeSeenMsB\x12Z\x10common/componentb\x06proto3"

var (
	file_proto_common_component_player_comp_proto_rawDescOnce sync.Once
	file_proto_common_component_player_comp_proto_rawDescData []byte
)

func file_proto_common_component_player_comp_proto_rawDescGZIP() []byte {
	file_proto_common_component_player_comp_proto_rawDescOnce.Do(func() {
		file_proto_common_component_player_comp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_component_player_comp_proto_rawDesc), len(file_proto_common_component_player_comp_proto_rawDesc)))
	})
	return file_proto_common_component_player_comp_proto_rawDescData
}

var file_proto_common_component_player_comp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_common_component_player_comp_proto_goTypes = []any{
	(*NormalLogin)(nil),           // 0: NormalLogin
	(*CoverLogin)(nil),            // 1: CoverLogin
	(*Player)(nil),                // 2: Player
	(*Account)(nil),               // 3: Account
	(*UnregisterPlayer)(nil),      // 4: UnregisterPlayer
	(*PlayerUint64Comp)(nil),      // 5: PlayerUint64Comp
	(*PlayerUint32Comp)(nil),      // 6: PlayerUint32Comp
	(*PlayerProfileComp)(nil),     // 7: PlayerProfileComp
	(*PlayerStressTestProbe)(nil), // 8: PlayerStressTestProbe
	(*PlayerMergeStateComp)(nil),  // 9: PlayerMergeStateComp
}
var file_proto_common_component_player_comp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_component_player_comp_proto_init() }
func file_proto_common_component_player_comp_proto_init() {
	if File_proto_common_component_player_comp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_component_player_comp_proto_rawDesc), len(file_proto_common_component_player_comp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_component_player_comp_proto_goTypes,
		DependencyIndexes: file_proto_common_component_player_comp_proto_depIdxs,
		MessageInfos:      file_proto_common_component_player_comp_proto_msgTypes,
	}.Build()
	File_proto_common_component_player_comp_proto = out.File
	file_proto_common_component_player_comp_proto_goTypes = nil
	file_proto_common_component_player_comp_proto_depIdxs = nil
}
