// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/common/base/config.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service config, avoid conflict with protobuf's Service
type ServiceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Service name
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`   // Health check or access URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type KafkaConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Brokers          []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`                                              // Kafka broker list
	Topics           []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`                                                // Configurable topic list
	GroupId          string                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                               // Consumer group ID
	EnableAutoCommit bool                   `protobuf:"varint,4,opt,name=enable_auto_commit,json=enableAutoCommit,proto3" json:"enable_auto_commit,omitempty"` // Enable auto-commit
	AutoOffsetReset  string                 `protobuf:"bytes,5,opt,name=auto_offset_reset,json=autoOffsetReset,proto3" json:"auto_offset_reset,omitempty"`     // earliest / latest
	// P:分区数。**不可变契约**,与 db_task / 审计 topic 同一套纪律
	// (docs/design/db-task-kafka-partition-contract.md):要改就 +1 代号换一批
	// 新 topic,绝不原地扩分区 —— 扩分区会把 node_id % P 重映射,
	// 命令就发到没人 assign 的分区上,静默全丢。0 = 256。
	CommandTopicPartitions uint32 `protobuf:"varint,6,opt,name=command_topic_partitions,json=commandTopicPartitions,proto3" json:"command_topic_partitions,omitempty"`
	// 代号,进 topic 名:`<类型>-cmd_g<N>`(与 data_service 的
	// transaction_log_topic_g1 同形)。0 = 1。
	CommandTopicGeneration uint32 `protobuf:"varint,7,opt,name=command_topic_generation,json=commandTopicGeneration,proto3" json:"command_topic_generation,omitempty"`
	// 迁移窗口开关:true = **不再**消费旧的 `<类型>-<node_id>` per-node topic。
	// 默认 false(仍消费),因为生产者是分批切的(Go login 由另一路发布切换),
	// producer 还在写老 topic 时把消费端关掉 = 命令全丢。
	// 全部生产者切完后置 true,P1(僵尸进程与继任者共用 consumer group、
	// 分区被判给僵尸导致继任者饿死)才算彻底关闭 —— 老路径仍是 group 订阅。
	DisableLegacyPerNodeTopic bool `protobuf:"varint,8,opt,name=disable_legacy_per_node_topic,json=disableLegacyPerNodeTopic,proto3" json:"disable_legacy_per_node_topic,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *KafkaConfig) Reset() {
	*x = KafkaConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaConfig) ProtoMessage() {}

func (x *KafkaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaConfig.ProtoReflect.Descriptor instead.
func (*KafkaConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{1}
}

func (x *KafkaConfig) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *KafkaConfig) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *KafkaConfig) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *KafkaConfig) GetEnableAutoCommit() bool {
	if x != nil {
		return x.EnableAutoCommit
	}
	return false
}

func (x *KafkaConfig) GetAutoOffsetReset() string {
	if x != nil {
		return x.AutoOffsetReset
	}
	return ""
}

func (x *KafkaConfig) GetCommandTopicPartitions() uint32 {
	if x != nil {
		return x.CommandTopicPartitions
	}
	return 0
}

func (x *KafkaConfig) GetCommandTopicGeneration() uint32 {
	if x != nil {
		return x.CommandTopicGeneration
	}
	return 0
}

func (x *KafkaConfig) GetDisableLegacyPerNodeTopic() bool {
	if x != nil {
		return x.DisableLegacyPerNodeTopic
	}
	return false
}

// 一种永久 guid 的号段配置(docs/design/node-id-overhaul-plan-20260908.md §6 / §7.5)。
// 号段 = scene 经 DataService.AllocateIdSegment 从全局库 id_segment 表领 [lo, hi),
// 值域 [1, 2^55) 与存量 snowflake 号(≥ 6.7e16)不相交,新旧号在同一张表 / 玩家 blob 里共存、不迁数据。
// 一种 GUID 一个客户端实例(C++ GuidSegmentRegistry),kind 名 = 注册表种类名 = id_segment.biz_tag。
type IdSegmentKindConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 种类名:item / txlog / snapshot(以后 pet / guild …)。不认识的名字被忽略并记 ERROR。
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// 关闭 = 这种 guid 在本节点**没有发号源**:没有 snowflake 回退(scene 已退出槽位协议),
	// 每次铸号都 fail-closed。只用于故意停掉某种 guid 的场景,不是回滚开关。
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 动态 step(Leaf 口径):首次领段长度,以及上下限。一段不到 15 分钟用完 → 下次 ×2(≤ max_step),
	// 超过 30 分钟才用完 → 下次 ÷2(≥ min_step)。0 = 钉在 initial_step 上(不扩 / 不缩)。
	InitialStep   uint32 `protobuf:"varint,3,opt,name=initial_step,json=initialStep,proto3" json:"initial_step,omitempty"`
	MinStep       uint32 `protobuf:"varint,4,opt,name=min_step,json=minStep,proto3" json:"min_step,omitempty"`
	MaxStep       uint32 `protobuf:"varint,5,opt,name=max_step,json=maxStep,proto3" json:"max_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdSegmentKindConfig) Reset() {
	*x = IdSegmentKindConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdSegmentKindConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdSegmentKindConfig) ProtoMessage() {}

func (x *IdSegmentKindConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdSegmentKindConfig.ProtoReflect.Descriptor instead.
func (*IdSegmentKindConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{2}
}

func (x *IdSegmentKindConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IdSegmentKindConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *IdSegmentKindConfig) GetInitialStep() uint32 {
	if x != nil {
		return x.InitialStep
	}
	return 0
}

func (x *IdSegmentKindConfig) GetMinStep() uint32 {
	if x != nil {
		return x.MinStep
	}
	return 0
}

func (x *IdSegmentKindConfig) GetMaxStep() uint32 {
	if x != nil {
		return x.MaxStep
	}
	return 0
}

// 永久 guid 号段总配置:每种 guid 一块。只有 scene 读;放在部署配置而不是 GameConfig,
// 因为它是发号基础设施参数,不是玩法参数,而且只有这一份 yaml 不用改两处。
type IdSegmentConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []*IdSegmentKindConfig `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdSegmentConfig) Reset() {
	*x = IdSegmentConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdSegmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdSegmentConfig) ProtoMessage() {}

func (x *IdSegmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdSegmentConfig.ProtoReflect.Descriptor instead.
func (*IdSegmentConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{3}
}

func (x *IdSegmentConfig) GetKinds() []*IdSegmentKindConfig {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// Base deploy config
type BaseDeployConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	EtcdHosts                []string               `protobuf:"bytes,1,rep,name=etcd_hosts,json=etcdHosts,proto3" json:"etcd_hosts,omitempty"`
	LogLevel                 uint32                 `protobuf:"varint,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Services                 []*ServiceConfig       `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	ServiceDiscoveryPrefixes []string               `protobuf:"bytes,4,rep,name=service_discovery_prefixes,json=serviceDiscoveryPrefixes,proto3" json:"service_discovery_prefixes,omitempty"`
	KeepAliveInterval        uint32                 `protobuf:"varint,5,opt,name=keep_alive_interval,json=keepAliveInterval,proto3" json:"keep_alive_interval,omitempty"`
	DeployservicePrefix      string                 `protobuf:"bytes,6,opt,name=deployservice_prefix,json=deployservicePrefix,proto3" json:"deployservice_prefix,omitempty"`
	NodeTtlSeconds           uint32                 `protobuf:"varint,7,opt,name=node_ttl_seconds,json=nodeTtlSeconds,proto3" json:"node_ttl_seconds,omitempty"`
	HealthCheckInterval      uint32                 `protobuf:"varint,8,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	Kafka                    *KafkaConfig           `protobuf:"bytes,9,opt,name=kafka,proto3" json:"kafka,omitempty"` // Kafka config
	// Table data directory path
	TableDataDirectory string `protobuf:"bytes,10,opt,name=table_data_directory,json=tableDataDirectory,proto3" json:"table_data_directory,omitempty"` // Config table directory path
	// Shared HMAC secret for Gate connection tokens (Login signs, Gate verifies).
	// If empty, Gate skips token verification (dev/test mode).
	GateTokenSecret string `protobuf:"bytes,11,opt,name=gate_token_secret,json=gateTokenSecret,proto3" json:"gate_token_secret,omitempty"`
	// Table data loading format: "json" (default) or "binary".
	// "binary" loads .pb files (proto wire format) for faster startup.
	TableDataFormat string `protobuf:"bytes,12,opt,name=table_data_format,json=tableDataFormat,proto3" json:"table_data_format,omitempty"`
	// Grace period (seconds) before actually removing a node after etcd DELETE.
	// During this window, if the node re-registers (PUT), the removal is cancelled.
	// 0 = immediate removal (production default).
	// 300+ = recommended for dev/debug to survive breakpoint pauses.
	NodeRemovalGraceSeconds uint32 `protobuf:"varint,13,opt,name=node_removal_grace_seconds,json=nodeRemovalGraceSeconds,proto3" json:"node_removal_grace_seconds,omitempty"`
	// Root directory for data files (nav meshes, etc.).
	// Nav bin path = data_root_directory + nav_bin_file from table.
	// Local dev: "../"   K8s: "/app/"
	DataRootDirectory string `protobuf:"bytes,14,opt,name=data_root_directory,json=dataRootDirectory,proto3" json:"data_root_directory,omitempty"`
	// Gate 的并发客户端连接上限。生产取值 1..131071;
	// 0 = 关闭运维阈值(仅供显式 dev/test 本地调试,prod 会拒绝启动),
	// 但 session-id 的 131071 硬上限仍然生效。
	//
	// 为什么必须有:gate 是唯一对公网开放的端口,而 muduo 的 TcpServer 无条件
	// accept —— 在此之前全仓没有任何连接数上限,任何人都能一直建连把 gate 的
	// fd、SessionMap 和每连接缓冲吃光,直到 accept 撞 EMFILE 或进程 OOM。
	// 这条限流不需要任何凭证即可触发,是纯粹的资源耗尽面。
	// 超过上限的新连接在分配 session 之前就被拒掉(见 HandleConnectionEstablished)。
	// 131071 上界为所有 node_id 保留 UINT32_MAX 哨兵,并避免 session-id 空间
	// 全部占满后碰撞重试永久自旋。
	GateMaxConnections uint32 `protobuf:"varint,15,opt,name=gate_max_connections,json=gateMaxConnections,proto3" json:"gate_max_connections,omitempty"`
	// battle 节点客户端直连票据的 HMAC 共享密钥(battle 节点签发并校验;全部 battle 实例
	// 必须一致;与 gate_token_secret 分域,任一泄露不影响另一侧)。
	// 空值处置由 BATTLE_RUN_MODE 决定:dev/test 放行并 WARN,prod 拒绝启动
	// (设计文档 turn-based-battle-server.md §18 D24/D27)。
	BattleTokenSecret string `protobuf:"bytes,16,opt,name=battle_token_secret,json=battleTokenSecret,proto3" json:"battle_token_secret,omitempty"`
	// battle 节点客户端面并发直连上限。0 = 关闭运维阈值(仅 dev/test);
	// 语义与 gate_max_connections 相同:超限连接在握手前即被拒。
	BattleMaxConnections uint32 `protobuf:"varint,17,opt,name=battle_max_connections,json=battleMaxConnections,proto3" json:"battle_max_connections,omitempty"`
	// 集群号:部署级常量,由运维一次性设定(ConfigMap / yaml),策划不碰,默认 0。
	// 只有 Go 的 snowflake 槽位协议(login-player / guild / scene-manager / match)消费它,
	// 作为 17 位 worker 字段的高 5 位([cluster5][node12]);C++ 侧 2026-09-08 起没有消费者
	// (scene 的永久 guid 走号段,不编码集群),这里只是同一份 yaml 口径的原样读入。
	// 取值 0..31。见 docs/design/node-id-overhaul-plan-20260908.md §5 / §7.5。
	ClusterId uint32 `protobuf:"varint,18,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// 永久 guid 号段(item / txlog / snapshot 各一块,见 IdSegmentConfig)。
	IdSegment     *IdSegmentConfig `protobuf:"bytes,19,opt,name=id_segment,json=idSegment,proto3" json:"id_segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseDeployConfig) Reset() {
	*x = BaseDeployConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseDeployConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseDeployConfig) ProtoMessage() {}

func (x *BaseDeployConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseDeployConfig.ProtoReflect.Descriptor instead.
func (*BaseDeployConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{4}
}

func (x *BaseDeployConfig) GetEtcdHosts() []string {
	if x != nil {
		return x.EtcdHosts
	}
	return nil
}

func (x *BaseDeployConfig) GetLogLevel() uint32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *BaseDeployConfig) GetServices() []*ServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *BaseDeployConfig) GetServiceDiscoveryPrefixes() []string {
	if x != nil {
		return x.ServiceDiscoveryPrefixes
	}
	return nil
}

func (x *BaseDeployConfig) GetKeepAliveInterval() uint32 {
	if x != nil {
		return x.KeepAliveInterval
	}
	return 0
}

func (x *BaseDeployConfig) GetDeployservicePrefix() string {
	if x != nil {
		return x.DeployservicePrefix
	}
	return ""
}

func (x *BaseDeployConfig) GetNodeTtlSeconds() uint32 {
	if x != nil {
		return x.NodeTtlSeconds
	}
	return 0
}

func (x *BaseDeployConfig) GetHealthCheckInterval() uint32 {
	if x != nil {
		return x.HealthCheckInterval
	}
	return 0
}

func (x *BaseDeployConfig) GetKafka() *KafkaConfig {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *BaseDeployConfig) GetTableDataDirectory() string {
	if x != nil {
		return x.TableDataDirectory
	}
	return ""
}

func (x *BaseDeployConfig) GetGateTokenSecret() string {
	if x != nil {
		return x.GateTokenSecret
	}
	return ""
}

func (x *BaseDeployConfig) GetTableDataFormat() string {
	if x != nil {
		return x.TableDataFormat
	}
	return ""
}

func (x *BaseDeployConfig) GetNodeRemovalGraceSeconds() uint32 {
	if x != nil {
		return x.NodeRemovalGraceSeconds
	}
	return 0
}

func (x *BaseDeployConfig) GetDataRootDirectory() string {
	if x != nil {
		return x.DataRootDirectory
	}
	return ""
}

func (x *BaseDeployConfig) GetGateMaxConnections() uint32 {
	if x != nil {
		return x.GateMaxConnections
	}
	return 0
}

func (x *BaseDeployConfig) GetBattleTokenSecret() string {
	if x != nil {
		return x.BattleTokenSecret
	}
	return ""
}

func (x *BaseDeployConfig) GetBattleMaxConnections() uint32 {
	if x != nil {
		return x.BattleMaxConnections
	}
	return 0
}

func (x *BaseDeployConfig) GetClusterId() uint32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *BaseDeployConfig) GetIdSegment() *IdSegmentConfig {
	if x != nil {
		return x.IdSegment
	}
	return nil
}

// Game config
type GameConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	SceneNodeType uint32                      `protobuf:"varint,1,opt,name=scene_node_type,json=sceneNodeType,proto3" json:"scene_node_type,omitempty"` // Scene node type
	ZoneId        uint32                      `protobuf:"varint,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                        // Zone ID
	ZoneRedis     *GameConfig_ZoneRedisConfig `protobuf:"bytes,7,opt,name=zone_redis,json=zoneRedis,proto3" json:"zone_redis,omitempty"`                // Zone Redis config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{5}
}

func (x *GameConfig) GetSceneNodeType() uint32 {
	if x != nil {
		return x.SceneNodeType
	}
	return 0
}

func (x *GameConfig) GetZoneId() uint32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *GameConfig) GetZoneRedis() *GameConfig_ZoneRedisConfig {
	if x != nil {
		return x.ZoneRedis
	}
	return nil
}

// Zone Redis config
type GameConfig_ZoneRedisConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`         // Redis host
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`        // Redis port
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"` // Redis password (optional)
	Db            uint32                 `protobuf:"varint,6,opt,name=db,proto3" json:"db,omitempty"`            // Redis database number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfig_ZoneRedisConfig) Reset() {
	*x = GameConfig_ZoneRedisConfig{}
	mi := &file_proto_common_base_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig_ZoneRedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig_ZoneRedisConfig) ProtoMessage() {}

func (x *GameConfig_ZoneRedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_base_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig_ZoneRedisConfig.ProtoReflect.Descriptor instead.
func (*GameConfig_ZoneRedisConfig) Descriptor() ([]byte, []int) {
	return file_proto_common_base_config_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GameConfig_ZoneRedisConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GameConfig_ZoneRedisConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GameConfig_ZoneRedisConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GameConfig_ZoneRedisConfig) GetDb() uint32 {
	if x != nil {
		return x.Db
	}
	return 0
}

var File_proto_common_base_config_proto protoreflect.FileDescriptor

const file_proto_common_base_config_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/common/base/config.proto\"5\n" +
	"\rServiceConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xea\x02\n" +
	"\vKafkaConfig\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12,\n" +
	"\x12enable_auto_commit\x18\x04 \x01(\bR\x10enableAutoCommit\x12*\n" +
	"\x11auto_offset_reset\x18\x05 \x01(\tR\x0fautoOffsetReset\x128\n" +
	"\x18command_topic_partitions\x18\x06 \x01(\rR\x16commandTopicPartitions\x128\n" +
	"\x18command_topic_generation\x18\a \x01(\rR\x16commandTopicGeneration\x12@\n" +
	"\x1ddisable_legacy_per_node_topic\x18\b \x01(\bR\x19disableLegacyPerNodeTopic\"\x9c\x01\n" +
	"\x13IdSegmentKindConfig\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12!\n" +
	"\finitial_step\x18\x03 \x01(\rR\vinitialStep\x12\x19\n" +
	"\bmin_step\x18\x04 \x01(\rR\aminStep\x12\x19\n" +
	"\bmax_step\x18\x05 \x01(\rR\amaxStep\"=\n" +
	"\x0fIdSegmentConfig\x12*\n" +
	"\x05kinds\x18\x01 \x03(\v2\x14.IdSegmentKindConfigR\x05kinds\"\xfc\x06\n" +
	"\x10BaseDeployConfig\x12\x1d\n" +
	"\n" +
	"etcd_hosts\x18\x01 \x03(\tR\tetcdHosts\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\rR\blogLevel\x12*\n" +
	"\bservices\x18\x03 \x03(\v2\x0e.ServiceConfigR\bservices\x12<\n" +
	"\x1aservice_discovery_prefixes\x18\x04 \x03(\tR\x18serviceDiscoveryPrefixes\x12.\n" +
	"\x13keep_alive_interval\x18\x05 \x01(\rR\x11keepAliveInterval\x121\n" +
	"\x14deployservice_prefix\x18\x06 \x01(\tR\x13deployservicePrefix\x12(\n" +
	"\x10node_ttl_seconds\x18\a \x01(\rR\x0enodeTtlSeconds\x122\n" +
	"\x15health_check_interval\x18\b \x01(\rR\x13healthCheckInterval\x12\"\n" +
	"\x05kafka\x18\t \x01(\v2\f.KafkaConfigR\x05kafka\x120\n" +
	"\x14table_data_directory\x18\n" +
	" \x01(\tR\x12tableDataDirectory\x12*\n" +
	"\x11gate_token_secret\x18\v \x01(\tR\x0fgateTokenSecret\x12*\n" +
	"\x11table_data_format\x18\f \x01(\tR\x0ftableDataFormat\x12;\n" +
	"\x1anode_removal_grace_seconds\x18\r \x01(\rR\x17nodeRemovalGraceSeconds\x12.\n" +
	"\x13data_root_directory\x18\x0e \x01(\tR\x11dataRootDirectory\x120\n" +
	"\x14gate_max_connections\x18\x0f \x01(\rR\x12gateMaxConnections\x12.\n" +
	"\x13battle_token_secret\x18\x10 \x01(\tR\x11battleTokenSecret\x124\n" +
	"\x16battle_max_connections\x18\x11 \x01(\rR\x14battleMaxConnections\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x12 \x01(\rR\tclusterId\x12/\n" +
	"\n" +
	"id_segment\x18\x13 \x01(\v2\x10.IdSegmentConfigR\tidSegment\"\xf0\x01\n" +
	"\n" +
	"GameConfig\x12&\n" +
	"\x0fscene_node_type\x18\x01 \x01(\rR\rsceneNodeType\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\rR\x06zoneId\x12:\n" +
	"\n" +
	"zone_redis\x18\a \x01(\v2\x1b.GameConfig.ZoneRedisConfigR\tzoneRedis\x1ae\n" +
	"\x0fZoneRedisConfig\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x06 \x01(\rR\x02dbB\x13Z\x11proto/common/baseb\x06proto3"

var (
	file_proto_common_base_config_proto_rawDescOnce sync.Once
	file_proto_common_base_config_proto_rawDescData []byte
)

func file_proto_common_base_config_proto_rawDescGZIP() []byte {
	file_proto_common_base_config_proto_rawDescOnce.Do(func() {
		file_proto_common_base_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_base_config_proto_rawDesc), len(file_proto_common_base_config_proto_rawDesc)))
	})
	return file_proto_common_base_config_proto_rawDescData
}

var file_proto_common_base_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_common_base_config_proto_goTypes = []any{
	(*ServiceConfig)(nil),              // 0: ServiceConfig
	(*KafkaConfig)(nil),                // 1: KafkaConfig
	(*IdSegmentKindConfig)(nil),        // 2: IdSegmentKindConfig
	(*IdSegmentConfig)(nil),            // 3: IdSegmentConfig
	(*BaseDeployConfig)(nil),           // 4: BaseDeployConfig
	(*GameConfig)(nil),                 // 5: GameConfig
	(*GameConfig_ZoneRedisConfig)(nil), // 6: GameConfig.ZoneRedisConfig
}
var file_proto_common_base_config_proto_depIdxs = []int32{
	2, // 0: IdSegmentConfig.kinds:type_name -> IdSegmentKindConfig
	0, // 1: BaseDeployConfig.services:type_name -> ServiceConfig
	1, // 2: BaseDeployConfig.kafka:type_name -> KafkaConfig
	3, // 3: BaseDeployConfig.id_segment:type_name -> IdSegmentConfig
	6, // 4: GameConfig.zone_redis:type_name -> GameConfig.ZoneRedisConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_common_base_config_proto_init() }
func file_proto_common_base_config_proto_init() {
	if File_proto_common_base_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_base_config_proto_rawDesc), len(file_proto_common_base_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_base_config_proto_goTypes,
		DependencyIndexes: file_proto_common_base_config_proto_depIdxs,
		MessageInfos:      file_proto_common_base_config_proto_msgTypes,
	}.Build()
	File_proto_common_base_config_proto = out.File
	file_proto_common_base_config_proto_goTypes = nil
	file_proto_common_base_config_proto_depIdxs = nil
}
