// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/common/event/team_event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// team(match 进程)→ scene:某玩家的组队成员关系可能变了,请自己重读 SharedRedis
// (HMGET team:player:<id> tid epoch → GET team:<tid>)。
// 载荷只是"去刷新一下"的信号,不携带权威数据:乱序、重复、丢失都安全(下次进场会再拉,§F.2)。
type PlayerTeamRefreshEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerTeamRefreshEvent) Reset() {
	*x = PlayerTeamRefreshEvent{}
	mi := &file_proto_common_event_team_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerTeamRefreshEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerTeamRefreshEvent) ProtoMessage() {}

func (x *PlayerTeamRefreshEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_event_team_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerTeamRefreshEvent.ProtoReflect.Descriptor instead.
func (*PlayerTeamRefreshEvent) Descriptor() ([]byte, []int) {
	return file_proto_common_event_team_event_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerTeamRefreshEvent) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_proto_common_event_team_event_proto protoreflect.FileDescriptor

const file_proto_common_event_team_event_proto_rawDesc = "" +
	"\n" +
	"#proto/common/event/team_event.proto\"5\n" +
	"\x16PlayerTeamRefreshEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerIdB\x14Z\x12proto/common/eventb\x06proto3"

var (
	file_proto_common_event_team_event_proto_rawDescOnce sync.Once
	file_proto_common_event_team_event_proto_rawDescData []byte
)

func file_proto_common_event_team_event_proto_rawDescGZIP() []byte {
	file_proto_common_event_team_event_proto_rawDescOnce.Do(func() {
		file_proto_common_event_team_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_event_team_event_proto_rawDesc), len(file_proto_common_event_team_event_proto_rawDesc)))
	})
	return file_proto_common_event_team_event_proto_rawDescData
}

var file_proto_common_event_team_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_common_event_team_event_proto_goTypes = []any{
	(*PlayerTeamRefreshEvent)(nil), // 0: PlayerTeamRefreshEvent
}
var file_proto_common_event_team_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_common_event_team_event_proto_init() }
func file_proto_common_event_team_event_proto_init() {
	if File_proto_common_event_team_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_event_team_event_proto_rawDesc), len(file_proto_common_event_team_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_event_team_event_proto_goTypes,
		DependencyIndexes: file_proto_common_event_team_event_proto_depIdxs,
		MessageInfos:      file_proto_common_event_team_event_proto_msgTypes,
	}.Build()
	File_proto_common_event_team_event_proto = out.File
	file_proto_common_event_team_event_proto_goTypes = nil
	file_proto_common_event_team_event_proto_depIdxs = nil
}
