// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/scene_manager/scene_node_service.proto

package scene_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	base "proto/common/base"
	scene "proto/scene"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SceneNodeGrpc_CreateScene_FullMethodName         = "/scene_node.SceneNodeGrpc/CreateScene"
	SceneNodeGrpc_DestroyScene_FullMethodName        = "/scene_node.SceneNodeGrpc/DestroyScene"
	SceneNodeGrpc_ReleasePlayer_FullMethodName       = "/scene_node.SceneNodeGrpc/ReleasePlayer"
	SceneNodeGrpc_PrepareBattle_FullMethodName       = "/scene_node.SceneNodeGrpc/PrepareBattle"
	SceneNodeGrpc_CancelBattlePrepare_FullMethodName = "/scene_node.SceneNodeGrpc/CancelBattlePrepare"
)

// SceneNodeGrpcClient is the client API for SceneNodeGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dedicated gRPC-only control plane for Scene nodes.
// This avoids the C++ grpc plugin limitation with cc_generic_services=true
// on the legacy Scene RPC proto.
type SceneNodeGrpcClient interface {
	CreateScene(ctx context.Context, in *scene.CreateSceneRequest, opts ...grpc.CallOption) (*scene.CreateSceneResponse, error)
	DestroyScene(ctx context.Context, in *scene.DestroySceneRequest, opts ...grpc.CallOption) (*base.Empty, error)
	// ReleasePlayer is called by SceneManager on the player's previous scene node
	// when the player is being routed to a different scene node (cross-node scene
	// change). The old node persists the player to Redis, drops the entity, and
	// frees the session mapping so the new node can load fresh from Redis.
	ReleasePlayer(ctx context.Context, in *ReleasePlayerRequest, opts ...grpc.CallOption) (*base.Empty, error)
	// ---- 回合制战斗 gather 管线(docs/design/turn-based-battle-server.md §3.1/§5.3)----
	// 消息定义共用 proto/scene/scene.proto 里的那一份(全局包,与 CreateSceneRequest
	// 同款双服务共享模式):muduo Scene 服务与本 gRPC 控制面同签名,match(Go)走本面。
	// match 对每个参战者调用:冻结玩家(挂 InBattleComp)+ 返回战斗快照;
	// error_message.id != 0 即拒绝,且不留任何冻结痕迹。
	PrepareBattle(ctx context.Context, in *scene.PrepareBattleRequest, opts ...grpc.CallOption) (*scene.PrepareBattleResponse, error)
	// gather 失败的逐人回滚:battle_id 匹配才解冻,迟到/重复取消幂等忽略。
	CancelBattlePrepare(ctx context.Context, in *scene.CancelBattlePrepareRequest, opts ...grpc.CallOption) (*base.Empty, error)
}

type sceneNodeGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSceneNodeGrpcClient(cc grpc.ClientConnInterface) SceneNodeGrpcClient {
	return &sceneNodeGrpcClient{cc}
}

func (c *sceneNodeGrpcClient) CreateScene(ctx context.Context, in *scene.CreateSceneRequest, opts ...grpc.CallOption) (*scene.CreateSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(scene.CreateSceneResponse)
	err := c.cc.Invoke(ctx, SceneNodeGrpc_CreateScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneNodeGrpcClient) DestroyScene(ctx context.Context, in *scene.DestroySceneRequest, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, SceneNodeGrpc_DestroyScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneNodeGrpcClient) ReleasePlayer(ctx context.Context, in *ReleasePlayerRequest, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, SceneNodeGrpc_ReleasePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneNodeGrpcClient) PrepareBattle(ctx context.Context, in *scene.PrepareBattleRequest, opts ...grpc.CallOption) (*scene.PrepareBattleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(scene.PrepareBattleResponse)
	err := c.cc.Invoke(ctx, SceneNodeGrpc_PrepareBattle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneNodeGrpcClient) CancelBattlePrepare(ctx context.Context, in *scene.CancelBattlePrepareRequest, opts ...grpc.CallOption) (*base.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(base.Empty)
	err := c.cc.Invoke(ctx, SceneNodeGrpc_CancelBattlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SceneNodeGrpcServer is the server API for SceneNodeGrpc service.
// All implementations must embed UnimplementedSceneNodeGrpcServer
// for forward compatibility.
//
// Dedicated gRPC-only control plane for Scene nodes.
// This avoids the C++ grpc plugin limitation with cc_generic_services=true
// on the legacy Scene RPC proto.
type SceneNodeGrpcServer interface {
	CreateScene(context.Context, *scene.CreateSceneRequest) (*scene.CreateSceneResponse, error)
	DestroyScene(context.Context, *scene.DestroySceneRequest) (*base.Empty, error)
	// ReleasePlayer is called by SceneManager on the player's previous scene node
	// when the player is being routed to a different scene node (cross-node scene
	// change). The old node persists the player to Redis, drops the entity, and
	// frees the session mapping so the new node can load fresh from Redis.
	ReleasePlayer(context.Context, *ReleasePlayerRequest) (*base.Empty, error)
	// ---- 回合制战斗 gather 管线(docs/design/turn-based-battle-server.md §3.1/§5.3)----
	// 消息定义共用 proto/scene/scene.proto 里的那一份(全局包,与 CreateSceneRequest
	// 同款双服务共享模式):muduo Scene 服务与本 gRPC 控制面同签名,match(Go)走本面。
	// match 对每个参战者调用:冻结玩家(挂 InBattleComp)+ 返回战斗快照;
	// error_message.id != 0 即拒绝,且不留任何冻结痕迹。
	PrepareBattle(context.Context, *scene.PrepareBattleRequest) (*scene.PrepareBattleResponse, error)
	// gather 失败的逐人回滚:battle_id 匹配才解冻,迟到/重复取消幂等忽略。
	CancelBattlePrepare(context.Context, *scene.CancelBattlePrepareRequest) (*base.Empty, error)
	mustEmbedUnimplementedSceneNodeGrpcServer()
}

// UnimplementedSceneNodeGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSceneNodeGrpcServer struct{}

func (UnimplementedSceneNodeGrpcServer) CreateScene(context.Context, *scene.CreateSceneRequest) (*scene.CreateSceneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScene not implemented")
}
func (UnimplementedSceneNodeGrpcServer) DestroyScene(context.Context, *scene.DestroySceneRequest) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyScene not implemented")
}
func (UnimplementedSceneNodeGrpcServer) ReleasePlayer(context.Context, *ReleasePlayerRequest) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleasePlayer not implemented")
}
func (UnimplementedSceneNodeGrpcServer) PrepareBattle(context.Context, *scene.PrepareBattleRequest) (*scene.PrepareBattleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareBattle not implemented")
}
func (UnimplementedSceneNodeGrpcServer) CancelBattlePrepare(context.Context, *scene.CancelBattlePrepareRequest) (*base.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBattlePrepare not implemented")
}
func (UnimplementedSceneNodeGrpcServer) mustEmbedUnimplementedSceneNodeGrpcServer() {}
func (UnimplementedSceneNodeGrpcServer) testEmbeddedByValue()                       {}

// UnsafeSceneNodeGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SceneNodeGrpcServer will
// result in compilation errors.
type UnsafeSceneNodeGrpcServer interface {
	mustEmbedUnimplementedSceneNodeGrpcServer()
}

func RegisterSceneNodeGrpcServer(s grpc.ServiceRegistrar, srv SceneNodeGrpcServer) {
	// If the following call pancis, it indicates UnimplementedSceneNodeGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SceneNodeGrpc_ServiceDesc, srv)
}

func _SceneNodeGrpc_CreateScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(scene.CreateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneNodeGrpcServer).CreateScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneNodeGrpc_CreateScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneNodeGrpcServer).CreateScene(ctx, req.(*scene.CreateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneNodeGrpc_DestroyScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(scene.DestroySceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneNodeGrpcServer).DestroyScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneNodeGrpc_DestroyScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneNodeGrpcServer).DestroyScene(ctx, req.(*scene.DestroySceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneNodeGrpc_ReleasePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleasePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneNodeGrpcServer).ReleasePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneNodeGrpc_ReleasePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneNodeGrpcServer).ReleasePlayer(ctx, req.(*ReleasePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneNodeGrpc_PrepareBattle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(scene.PrepareBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneNodeGrpcServer).PrepareBattle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneNodeGrpc_PrepareBattle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneNodeGrpcServer).PrepareBattle(ctx, req.(*scene.PrepareBattleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneNodeGrpc_CancelBattlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(scene.CancelBattlePrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneNodeGrpcServer).CancelBattlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneNodeGrpc_CancelBattlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneNodeGrpcServer).CancelBattlePrepare(ctx, req.(*scene.CancelBattlePrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SceneNodeGrpc_ServiceDesc is the grpc.ServiceDesc for SceneNodeGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SceneNodeGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scene_node.SceneNodeGrpc",
	HandlerType: (*SceneNodeGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScene",
			Handler:    _SceneNodeGrpc_CreateScene_Handler,
		},
		{
			MethodName: "DestroyScene",
			Handler:    _SceneNodeGrpc_DestroyScene_Handler,
		},
		{
			MethodName: "ReleasePlayer",
			Handler:    _SceneNodeGrpc_ReleasePlayer_Handler,
		},
		{
			MethodName: "PrepareBattle",
			Handler:    _SceneNodeGrpc_PrepareBattle_Handler,
		},
		{
			MethodName: "CancelBattlePrepare",
			Handler:    _SceneNodeGrpc_CancelBattlePrepare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scene_manager/scene_node_service.proto",
}
