// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: proto/scene/scene.proto

package scene

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	battle "proto/battle"
	base "proto/common/base"
	_ "proto/db"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerEnterGameNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId     uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EnterGsType   uint32                 `protobuf:"varint,4,opt,name=enter_gs_type,json=enterGsType,proto3" json:"enter_gs_type,omitempty"` // LOGIN_FIRST / LOGIN_RECONNECT / LOGIN_REPLACE
	SceneId       uint64                 `protobuf:"varint,5,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`               // Target scene instance GUID from SceneManager
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEnterGameNodeRequest) Reset() {
	*x = PlayerEnterGameNodeRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEnterGameNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEnterGameNodeRequest) ProtoMessage() {}

func (x *PlayerEnterGameNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEnterGameNodeRequest.ProtoReflect.Descriptor instead.
func (*PlayerEnterGameNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerEnterGameNodeRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEnterGameNodeRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *PlayerEnterGameNodeRequest) GetEnterGsType() uint32 {
	if x != nil {
		return x.EnterGsType
	}
	return 0
}

func (x *PlayerEnterGameNodeRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type ProcessClientPlayerMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageContent *base.MessageContent   `protobuf:"bytes,1,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	SessionId      uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessClientPlayerMessageRequest) Reset() {
	*x = ProcessClientPlayerMessageRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessClientPlayerMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessClientPlayerMessageRequest) ProtoMessage() {}

func (x *ProcessClientPlayerMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessClientPlayerMessageRequest.ProtoReflect.Descriptor instead.
func (*ProcessClientPlayerMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessClientPlayerMessageRequest) GetMessageContent() *base.MessageContent {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

func (x *ProcessClientPlayerMessageRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type ProcessClientPlayerMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageContent *base.MessageContent   `protobuf:"bytes,1,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	SessionId      uint32                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessClientPlayerMessageResponse) Reset() {
	*x = ProcessClientPlayerMessageResponse{}
	mi := &file_proto_scene_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessClientPlayerMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessClientPlayerMessageResponse) ProtoMessage() {}

func (x *ProcessClientPlayerMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessClientPlayerMessageResponse.ProtoReflect.Descriptor instead.
func (*ProcessClientPlayerMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessClientPlayerMessageResponse) GetMessageContent() *base.MessageContent {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

func (x *ProcessClientPlayerMessageResponse) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type SessionDisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionDisconnectRequest) Reset() {
	*x = SessionDisconnectRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionDisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionDisconnectRequest) ProtoMessage() {}

func (x *SessionDisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionDisconnectRequest.ProtoReflect.Descriptor instead.
func (*SessionDisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{3}
}

func (x *SessionDisconnectRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GameNodeConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcClient     *base.NetworkAddress   `protobuf:"bytes,1,opt,name=rpc_client,json=rpcClient,proto3" json:"rpc_client,omitempty"`
	GateNodeId    uint32                 `protobuf:"varint,2,opt,name=gate_node_id,json=gateNodeId,proto3" json:"gate_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameNodeConnectRequest) Reset() {
	*x = GameNodeConnectRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameNodeConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNodeConnectRequest) ProtoMessage() {}

func (x *GameNodeConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNodeConnectRequest.ProtoReflect.Descriptor instead.
func (*GameNodeConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{4}
}

func (x *GameNodeConnectRequest) GetRpcClient() *base.NetworkAddress {
	if x != nil {
		return x.RpcClient
	}
	return nil
}

func (x *GameNodeConnectRequest) GetGateNodeId() uint32 {
	if x != nil {
		return x.GateNodeId
	}
	return 0
}

type RegisterPlayerSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint32                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPlayerSessionRequest) Reset() {
	*x = RegisterPlayerSessionRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPlayerSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayerSessionRequest) ProtoMessage() {}

func (x *RegisterPlayerSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayerSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterPlayerSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterPlayerSessionRequest) GetSessionId() uint32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *RegisterPlayerSessionRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type CreateSceneRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigId        uint32                 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	SceneId         uint64                 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                           // Go-allocated scene ID; C++ dedup by this when > 0.
	MirrorConfigId  uint32                 `protobuf:"varint,3,opt,name=mirror_config_id,json=mirrorConfigId,proto3" json:"mirror_config_id,omitempty"`    // Mirror config ID (0 = not a mirror instance)
	DungeonConfigId uint32                 `protobuf:"varint,4,opt,name=dungeon_config_id,json=dungeonConfigId,proto3" json:"dungeon_config_id,omitempty"` // Dungeon config ID (0 = not a dungeon instance)
	CreatorIds      []uint64               `protobuf:"varint,5,rep,packed,name=creator_ids,json=creatorIds,proto3" json:"creator_ids,omitempty"`           // Creator player IDs (for instance access control)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateSceneRequest) Reset() {
	*x = CreateSceneRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneRequest) ProtoMessage() {}

func (x *CreateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneRequest.ProtoReflect.Descriptor instead.
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSceneRequest) GetConfigId() uint32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *CreateSceneRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CreateSceneRequest) GetMirrorConfigId() uint32 {
	if x != nil {
		return x.MirrorConfigId
	}
	return 0
}

func (x *CreateSceneRequest) GetDungeonConfigId() uint32 {
	if x != nil {
		return x.DungeonConfigId
	}
	return 0
}

func (x *CreateSceneRequest) GetCreatorIds() []uint64 {
	if x != nil {
		return x.CreatorIds
	}
	return nil
}

type CreateSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneInfo     *SceneInfoComp         `protobuf:"bytes,1,opt,name=scene_info,json=sceneInfo,proto3" json:"scene_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSceneResponse) Reset() {
	*x = CreateSceneResponse{}
	mi := &file_proto_scene_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneResponse) ProtoMessage() {}

func (x *CreateSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneResponse.ProtoReflect.Descriptor instead.
func (*CreateSceneResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSceneResponse) GetSceneInfo() *SceneInfoComp {
	if x != nil {
		return x.SceneInfo
	}
	return nil
}

type DestroySceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       uint64                 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySceneRequest) Reset() {
	*x = DestroySceneRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySceneRequest) ProtoMessage() {}

func (x *DestroySceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySceneRequest.ProtoReflect.Descriptor instead.
func (*DestroySceneRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{8}
}

func (x *DestroySceneRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type PrepareBattleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BattleId          uint64                 `protobuf:"varint,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	BattleNodeId      uint32                 `protobuf:"varint,3,opt,name=battle_node_id,json=battleNodeId,proto3" json:"battle_node_id,omitempty"`                // 写进 InBattleComp,重连重挂绑定用
	DeadlineMs        uint64                 `protobuf:"varint,4,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`                        // 战斗作废期限(Unix 毫秒),scene reaper 依据
	PrepareDeadlineMs uint64                 `protobuf:"varint,5,opt,name=prepare_deadline_ms,json=prepareDeadlineMs,proto3" json:"prepare_deadline_ms,omitempty"` // 备战作废期限(Unix 毫秒):CreateBattle 确认前 reaper 按它解冻(二期,设计 cross-zone-matchmaking.md §10);0 = 沿用 deadline_ms
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareBattleRequest) Reset() {
	*x = PrepareBattleRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBattleRequest) ProtoMessage() {}

func (x *PrepareBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBattleRequest.ProtoReflect.Descriptor instead.
func (*PrepareBattleRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareBattleRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PrepareBattleRequest) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *PrepareBattleRequest) GetBattleNodeId() uint32 {
	if x != nil {
		return x.BattleNodeId
	}
	return 0
}

func (x *PrepareBattleRequest) GetDeadlineMs() uint64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *PrepareBattleRequest) GetPrepareDeadlineMs() uint64 {
	if x != nil {
		return x.PrepareDeadlineMs
	}
	return 0
}

type PrepareBattleResponse struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	ErrorMessage     *base.TipInfoMessage         `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`             // 玩家不在/已在战斗等拒绝原因
	Snapshot         *battle.BattlePlayerSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`                                         // 冻结成功时返回战斗快照
	TableFingerprint string                       `protobuf:"bytes,3,opt,name=table_fingerprint,json=tableFingerprint,proto3" json:"table_fingerprint,omitempty"` // scene 侧战斗配表指纹(六张战斗表解析后确定性序列化的 sha256 前 16 字节 hex);match 比对全员一致
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PrepareBattleResponse) Reset() {
	*x = PrepareBattleResponse{}
	mi := &file_proto_scene_scene_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareBattleResponse) ProtoMessage() {}

func (x *PrepareBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareBattleResponse.ProtoReflect.Descriptor instead.
func (*PrepareBattleResponse) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{10}
}

func (x *PrepareBattleResponse) GetErrorMessage() *base.TipInfoMessage {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *PrepareBattleResponse) GetSnapshot() *battle.BattlePlayerSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *PrepareBattleResponse) GetTableFingerprint() string {
	if x != nil {
		return x.TableFingerprint
	}
	return ""
}

type CancelBattlePrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	BattleId      uint64                 `protobuf:"varint,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 不匹配 InBattleComp.battle_id 时忽略(防迟到取消)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBattlePrepareRequest) Reset() {
	*x = CancelBattlePrepareRequest{}
	mi := &file_proto_scene_scene_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBattlePrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBattlePrepareRequest) ProtoMessage() {}

func (x *CancelBattlePrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_scene_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBattlePrepareRequest.ProtoReflect.Descriptor instead.
func (*CancelBattlePrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_scene_scene_proto_rawDescGZIP(), []int{11}
}

func (x *CancelBattlePrepareRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CancelBattlePrepareRequest) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

var File_proto_scene_scene_proto protoreflect.FileDescriptor

const file_proto_scene_scene_proto_rawDesc = "" +
	"\n" +
	"\x17proto/scene/scene.proto\x1a\x1bproto/db/proto_option.proto\x1a\x1dproto/common/base/empty.proto\x1a\x1eproto/common/base/common.proto\x1a\x1fproto/common/base/message.proto\x1a\x1bproto/common/base/tip.proto\x1a\x1cproto/scene/scene_info.proto\x1a\x1eproto/battle/battle_data.proto\"\x97\x01\n" +
	"\x1aPlayerEnterGameNodeRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\x12\"\n" +
	"\renter_gs_type\x18\x04 \x01(\rR\venterGsType\x12\x19\n" +
	"\bscene_id\x18\x05 \x01(\x04R\asceneId\"|\n" +
	"!ProcessClientPlayerMessageRequest\x128\n" +
	"\x0fmessage_content\x18\x01 \x01(\v2\x0f.MessageContentR\x0emessageContent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\"}\n" +
	"\"ProcessClientPlayerMessageResponse\x128\n" +
	"\x0fmessage_content\x18\x01 \x01(\v2\x0f.MessageContentR\x0emessageContent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\rR\tsessionId\"7\n" +
	"\x18SessionDisconnectRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"j\n" +
	"\x16GameNodeConnectRequest\x12.\n" +
	"\n" +
	"rpc_client\x18\x01 \x01(\v2\x0f.NetworkAddressR\trpcClient\x12 \n" +
	"\fgate_node_id\x18\x02 \x01(\rR\n" +
	"gateNodeId\"Z\n" +
	"\x1cRegisterPlayerSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\rR\tsessionId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x04R\bplayerId\"\xc3\x01\n" +
	"\x12CreateSceneRequest\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\rR\bconfigId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x04R\asceneId\x12(\n" +
	"\x10mirror_config_id\x18\x03 \x01(\rR\x0emirrorConfigId\x12*\n" +
	"\x11dungeon_config_id\x18\x04 \x01(\rR\x0fdungeonConfigId\x12\x1f\n" +
	"\vcreator_ids\x18\x05 \x03(\x04R\n" +
	"creatorIds\"D\n" +
	"\x13CreateSceneResponse\x12-\n" +
	"\n" +
	"scene_info\x18\x01 \x01(\v2\x0e.SceneInfoCompR\tsceneInfo\"0\n" +
	"\x13DestroySceneRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\"\xc7\x01\n" +
	"\x14PrepareBattleRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\x04R\bbattleId\x12$\n" +
	"\x0ebattle_node_id\x18\x03 \x01(\rR\fbattleNodeId\x12\x1f\n" +
	"\vdeadline_ms\x18\x04 \x01(\x04R\n" +
	"deadlineMs\x12.\n" +
	"\x13prepare_deadline_ms\x18\x05 \x01(\x04R\x11prepareDeadlineMs\"\xad\x01\n" +
	"\x15PrepareBattleResponse\x124\n" +
	"\rerror_message\x18\x01 \x01(\v2\x0f.TipInfoMessageR\ferrorMessage\x121\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x15.BattlePlayerSnapshotR\bsnapshot\x12+\n" +
	"\x11table_fingerprint\x18\x03 \x01(\tR\x10tableFingerprint\"V\n" +
	"\x1aCancelBattlePrepareRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\x04R\bbattleId2\xbf\x06\n" +
	"\x05Scene\x12:\n" +
	"\x13PlayerEnterGameNode\x12\x1b.PlayerEnterGameNodeRequest\x1a\x06.Empty\x12J\n" +
	"\x13SendMessageToPlayer\x12\x18.NodeRouteMessageRequest\x1a\x19.NodeRouteMessageResponse\x12e\n" +
	"\x1aProcessClientPlayerMessage\x12\".ProcessClientPlayerMessageRequest\x1a#.ProcessClientPlayerMessageResponse\x12J\n" +
	"\x13InvokePlayerService\x12\x18.NodeRouteMessageRequest\x1a\x19.NodeRouteMessageResponse\x12A\n" +
	"\x12RouteNodeStringMsg\x12\x14.RouteMessageRequest\x1a\x15.RouteMessageResponse\x12V\n" +
	"\x14RoutePlayerStringMsg\x12\x1a.RoutePlayerMessageRequest\x1a\x1b.RoutePlayerMessageResponse\"\x05\x80\x99\xc8\x01\x01\x12<\n" +
	"\x13UpdateSessionDetail\x12\x1d.RegisterPlayerSessionRequest\x1a\x06.Empty\x128\n" +
	"\vCreateScene\x12\x13.CreateSceneRequest\x1a\x14.CreateSceneResponse\x12,\n" +
	"\fDestroyScene\x12\x14.DestroySceneRequest\x1a\x06.Empty\x12>\n" +
	"\rPrepareBattle\x12\x15.PrepareBattleRequest\x1a\x16.PrepareBattleResponse\x12:\n" +
	"\x13CancelBattlePrepare\x12\x1b.CancelBattlePrepareRequest\x1a\x06.Empty\x12>\n" +
	"\rNodeHandshake\x12\x15.NodeHandshakeRequest\x1a\x16.NodeHandshakeResponseB\x14\x98\xd4a\x03Z\vproto/scene\x80\x01\x01b\x06proto3"

var (
	file_proto_scene_scene_proto_rawDescOnce sync.Once
	file_proto_scene_scene_proto_rawDescData []byte
)

func file_proto_scene_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scene_scene_proto_rawDesc), len(file_proto_scene_scene_proto_rawDesc)))
	})
	return file_proto_scene_scene_proto_rawDescData
}

var file_proto_scene_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_scene_scene_proto_goTypes = []any{
	(*PlayerEnterGameNodeRequest)(nil),         // 0: PlayerEnterGameNodeRequest
	(*ProcessClientPlayerMessageRequest)(nil),  // 1: ProcessClientPlayerMessageRequest
	(*ProcessClientPlayerMessageResponse)(nil), // 2: ProcessClientPlayerMessageResponse
	(*SessionDisconnectRequest)(nil),           // 3: SessionDisconnectRequest
	(*GameNodeConnectRequest)(nil),             // 4: GameNodeConnectRequest
	(*RegisterPlayerSessionRequest)(nil),       // 5: RegisterPlayerSessionRequest
	(*CreateSceneRequest)(nil),                 // 6: CreateSceneRequest
	(*CreateSceneResponse)(nil),                // 7: CreateSceneResponse
	(*DestroySceneRequest)(nil),                // 8: DestroySceneRequest
	(*PrepareBattleRequest)(nil),               // 9: PrepareBattleRequest
	(*PrepareBattleResponse)(nil),              // 10: PrepareBattleResponse
	(*CancelBattlePrepareRequest)(nil),         // 11: CancelBattlePrepareRequest
	(*base.MessageContent)(nil),                // 12: MessageContent
	(*base.NetworkAddress)(nil),                // 13: NetworkAddress
	(*SceneInfoComp)(nil),                      // 14: SceneInfoComp
	(*base.TipInfoMessage)(nil),                // 15: TipInfoMessage
	(*battle.BattlePlayerSnapshot)(nil),        // 16: BattlePlayerSnapshot
	(*base.NodeRouteMessageRequest)(nil),       // 17: NodeRouteMessageRequest
	(*base.RouteMessageRequest)(nil),           // 18: RouteMessageRequest
	(*base.RoutePlayerMessageRequest)(nil),     // 19: RoutePlayerMessageRequest
	(*base.NodeHandshakeRequest)(nil),          // 20: NodeHandshakeRequest
	(*base.Empty)(nil),                         // 21: Empty
	(*base.NodeRouteMessageResponse)(nil),      // 22: NodeRouteMessageResponse
	(*base.RouteMessageResponse)(nil),          // 23: RouteMessageResponse
	(*base.RoutePlayerMessageResponse)(nil),    // 24: RoutePlayerMessageResponse
	(*base.NodeHandshakeResponse)(nil),         // 25: NodeHandshakeResponse
}
var file_proto_scene_scene_proto_depIdxs = []int32{
	12, // 0: ProcessClientPlayerMessageRequest.message_content:type_name -> MessageContent
	12, // 1: ProcessClientPlayerMessageResponse.message_content:type_name -> MessageContent
	13, // 2: GameNodeConnectRequest.rpc_client:type_name -> NetworkAddress
	14, // 3: CreateSceneResponse.scene_info:type_name -> SceneInfoComp
	15, // 4: PrepareBattleResponse.error_message:type_name -> TipInfoMessage
	16, // 5: PrepareBattleResponse.snapshot:type_name -> BattlePlayerSnapshot
	0,  // 6: Scene.PlayerEnterGameNode:input_type -> PlayerEnterGameNodeRequest
	17, // 7: Scene.SendMessageToPlayer:input_type -> NodeRouteMessageRequest
	1,  // 8: Scene.ProcessClientPlayerMessage:input_type -> ProcessClientPlayerMessageRequest
	17, // 9: Scene.InvokePlayerService:input_type -> NodeRouteMessageRequest
	18, // 10: Scene.RouteNodeStringMsg:input_type -> RouteMessageRequest
	19, // 11: Scene.RoutePlayerStringMsg:input_type -> RoutePlayerMessageRequest
	5,  // 12: Scene.UpdateSessionDetail:input_type -> RegisterPlayerSessionRequest
	6,  // 13: Scene.CreateScene:input_type -> CreateSceneRequest
	8,  // 14: Scene.DestroyScene:input_type -> DestroySceneRequest
	9,  // 15: Scene.PrepareBattle:input_type -> PrepareBattleRequest
	11, // 16: Scene.CancelBattlePrepare:input_type -> CancelBattlePrepareRequest
	20, // 17: Scene.NodeHandshake:input_type -> NodeHandshakeRequest
	21, // 18: Scene.PlayerEnterGameNode:output_type -> Empty
	22, // 19: Scene.SendMessageToPlayer:output_type -> NodeRouteMessageResponse
	2,  // 20: Scene.ProcessClientPlayerMessage:output_type -> ProcessClientPlayerMessageResponse
	22, // 21: Scene.InvokePlayerService:output_type -> NodeRouteMessageResponse
	23, // 22: Scene.RouteNodeStringMsg:output_type -> RouteMessageResponse
	24, // 23: Scene.RoutePlayerStringMsg:output_type -> RoutePlayerMessageResponse
	21, // 24: Scene.UpdateSessionDetail:output_type -> Empty
	7,  // 25: Scene.CreateScene:output_type -> CreateSceneResponse
	21, // 26: Scene.DestroyScene:output_type -> Empty
	10, // 27: Scene.PrepareBattle:output_type -> PrepareBattleResponse
	21, // 28: Scene.CancelBattlePrepare:output_type -> Empty
	25, // 29: Scene.NodeHandshake:output_type -> NodeHandshakeResponse
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_scene_scene_proto_init() }
func file_proto_scene_scene_proto_init() {
	if File_proto_scene_scene_proto != nil {
		return
	}
	file_proto_scene_scene_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scene_scene_proto_rawDesc), len(file_proto_scene_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scene_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_scene_proto = out.File
	file_proto_scene_scene_proto_goTypes = nil
	file_proto_scene_scene_proto_depIdxs = nil
}
